---
title: "cfu_counts"
output: html_document
date: "2024-07-15"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggpubr)
library(ggplot2)
library(qiime2R)
library(tidyverse)
library(ggh4x)
library(viridis)
library(ggrepel)
library(cowplot)
library(grid)
library(gridExtra)
```
**Functions**
```{r}
make_plot <- function(input_table,
                      wanted_experiment,
                      wanted_vendor,
                      x_axis,
                      y_axis,
                      alpha_value,
                      fill_value,
                      shape_value,
                      point_size,
                      y_labels,
                      fill_legend_title,
                      fill_labels,
                      alpha_legend_title,
                      alpha_labels,
                      shape_legend_title,
                      shape_labels,
                      x_name,
                      y_name,
                      wanted_title,
                      wanted_subtitle){
  ifelse(class(wanted_experiment) == "character", 
         filt_input_table <- input_table %>% 
                        mutate(microbe_presence = as.factor(microbe_presence)) %>% 
                        na.omit() %>% 
                        filter(experiment == wanted_experiment,
                               vendor == wanted_vendor),
         filt_input_table <- input_table %>% 
                        mutate(microbe_presence = as.factor(microbe_presence)) %>% 
                        na.omit() %>% 
                        filter(vendor == wanted_vendor))
  
  plot <- filt_input_table %>% 
            ggplot(aes(x = .data[[x_axis]], y = .data[[y_axis]], alpha = .data[[alpha_value]])) +
            theme_bw(base_size = 20) +
            theme(axis.text.x = element_blank()) +
            geom_point(aes(color = .data[[fill_value]], shape = .data[[shape_value]]), 
                       size = point_size) +
            scale_y_discrete(labels = y_labels) +
            scale_color_viridis(option = 'H', 
                               name = fill_legend_title,
                               discrete = TRUE,
                               labels = fill_labels) +
            scale_alpha_discrete(name = alpha_legend_title,
                                 labels = alpha_labels) +
            scale_shape_discrete(name = shape_legend_title,
                                 labels = shape_labels) +
            labs(x = x_name,
                 y = y_name, 
                 title = wanted_title, 
                 subtitle = wanted_subtitle)
  return(plot)
}

put_plots_together <- function(plot1,
                               plot2,
                               y_axis_label){
  legend <- cowplot::get_legend(plot1)
  pre_plot <- plot_grid(plot1 +
                          xlab(' ') +
                          ylab(' ') +
                          theme(legend.position = 'none'),
                        plot2 +
                          ggtitle(' ') +
                          ylab(' ') +
                          theme(legend.position = 'none'),
                        ncol = 1)
  plots_together <- plot_grid(pre_plot, legend,
                              rel_widths = c(1, 0.5))
  plots_together_y <- textGrob(y_axis_label,
                               gp = gpar(fontsize = 20),
                               rot = 90)
  plots_together <- grid.arrange(arrangeGrob(plots_together, left = plots_together_y))
  
  return(plots_together)
}
```

**File Paths**
```{r}
metadata_fp <- '../data/misc/proc_newExp_d15-d3_metadata.tsv'
cfu_count_fp <- '../data/misc/combined_CDD_cfuCounts.txt'
surv_status_fp <- '../data/misc/survival_status.tsv'

location_y_labs <- c('Blood',
                     'Liver',
                     'Spleen')
diet_fill_labs <- c('Chow',
                    'HFt/HFb',
                    'HFt/LFb',
                    'LFt/HFb',
                    'LFt/LFb')
short_diet_fill_labs <- c('Chow',
                          'LFt/LFb')
presAbs_labs <- c('Absent',
                  'Present')
surv_labs <- c("Didn't Survive",
               'Survived')
```

**Reading in Files**
```{r}
meta <- read_tsv(metadata_fp)
cfu_count_table <- read_tsv(cfu_count_fp)
surv_status <- read_tsv(surv_status_fp)
```
**Data Wrangling**
```{r}
cfu_count_inter <- cfu_count_table %>% 
  select(mouse_id, presence_spleen, presence_liver, presence_blood) %>% 
  gather(-mouse_id, key = 'location', value = 'microbe_presence') %>% 
  mutate(location = ifelse(location == 'presence_spleen', 'spleen', location),
         location = ifelse(location == 'presence_liver', 'liver', location),
         location = ifelse(location == 'presence_blood', 'blood', location),
         microbe_presence = ifelse(microbe_presence == TRUE, 1, 0))

proc_cfu_count <- cfu_count_table %>% 
  select(!c('presence_spleen', 'presence_liver', 'presence_blood',
            'CFUs.g_tissueSpleen', 'CFUs.g_tissueLiver', 'CFUs.mL_blood')) %>% 
  separate_wider_delim(cols = 'mouse_id',
                       delim = '.',
                       names = c('takeout1',
                                 'vendor',
                                 'takeout2',
                                 'takeout3'),
                       cols_remove = FALSE) %>% 
  select(!c('takeout1', 'takeout2', 'takeout3')) %>% 
  left_join(cfu_count_inter, by = 'mouse_id') %>% 
  mutate(diet = ifelse(diet == 'LFHF', 'LF/HF', diet),
         diet = ifelse(diet == 'LFLF', 'LF/LF', diet),
         diet = ifelse(diet == 'HFLF', 'HF/LF', diet), 
         diet = ifelse(diet == 'HFHF', 'HF/HF', diet),
         vendor = ifelse(vendor == 'CR', 'charles_river', 'taconic')) %>% 
  rename('mouse_sex' = 'sex') %>% 
  left_join(surv_status, by = "mouse_id")
```

**CDD01 Plots**
```{r, fig.width=10, fig.height=5}
cdd01_cr_plot <- make_plot(input_table = proc_cfu_count,
                           wanted_experiment = 'CDD01',
                           wanted_vendor = 'charles_river',
                           x_axis = 'mouse_id',
                           y_axis = 'location',
                           alpha_value = 'microbe_presence',
                           fill_value = 'diet',
                           shape_value = 'status',
                           point_size = 6,
                           y_labels = location_y_labs,
                           fill_legend_title = 'Diet',
                           fill_labels = short_diet_fill_labs,
                           alpha_legend_title = 'Bacterial CFUs',
                           alpha_labels = presAbs_labs,
                           shape_legend_title = 'Survival Status',
                           shape_labels = surv_labs,
                           x_name = 'Mouse',
                           y_name = 'Location',
                           wanted_title = 'CDD01 Results',
                           wanted_subtitle = 'Charles River Mice')

cdd01_tc_plot <- make_plot(input_table = proc_cfu_count,
                           wanted_experiment = 'CDD01',
                           wanted_vendor = 'taconic',
                           x_axis = 'mouse_id',
                           y_axis = 'location',
                           alpha_value = 'microbe_presence',
                           fill_value = 'diet',
                           shape_value = 'status',
                           point_size = 6,
                           y_labels = location_y_labs,
                           fill_legend_title = 'Diet',
                           fill_labels = short_diet_fill_labs,
                           alpha_legend_title = 'Bacterial CFUs',
                           alpha_labels = presAbs_labs,
                           shape_legend_title = 'Survival Status',
                           shape_labels = surv_labs,
                           x_name = 'Mouse',
                           y_name = 'Location',
                           wanted_title = 'CDD01 Results',
                           wanted_subtitle = 'Taconic Mice')

cdd01_cr_plot
cdd01_tc_plot
```

**CDD02 Plots**
```{r, fig.width=10, fig.height=5}
cdd02_cr_plot <- make_plot(input_table = proc_cfu_count,
                           wanted_experiment = 'CDD02',
                           wanted_vendor = 'charles_river',
                           x_axis = 'mouse_id',
                           y_axis = 'location',
                           alpha_value = 'microbe_presence',
                           fill_value = 'diet',
                           shape_value = 'status',
                           point_size = 6,
                           y_labels = location_y_labs,
                           fill_legend_title = 'Diet',
                           fill_labels = diet_fill_labs,
                           alpha_legend_title = 'Bacterial CFUs',
                           alpha_labels = presAbs_labs,
                           shape_legend_title = 'Survival Status',
                           shape_labels = surv_labs,
                           x_name = 'Mouse',
                           y_name = 'Location',
                           wanted_title = 'CDD02 Results',
                           wanted_subtitle = 'Charles River Mice')

cdd02_tc_plot <- make_plot(input_table = proc_cfu_count,
                           wanted_experiment = 'CDD02',
                           wanted_vendor = 'taconic',
                           x_axis = 'mouse_id',
                           y_axis = 'location',
                           alpha_value = 'microbe_presence',
                           fill_value = 'diet',
                           shape_value = 'status',
                           point_size = 6,
                           y_labels = location_y_labs,
                           fill_legend_title = 'Diet',
                           fill_labels = diet_fill_labs,
                           alpha_legend_title = 'Bacterial CFUs',
                           alpha_labels = presAbs_labs,
                           shape_legend_title = 'Survival Status',
                           shape_labels = surv_labs,
                           x_name = 'Mouse',
                           y_name = 'Location',
                           wanted_title = 'CDD02 Results',
                           wanted_subtitle = 'Taconic Mice')

cdd02_cr_plot
cdd02_tc_plot
```

**CDD03 Plots**
```{r, fig.width=10, fig.height=5}
cdd03_cr_plot <- make_plot(input_table = proc_cfu_count,
                           wanted_experiment = 'CDD03',
                           wanted_vendor = 'charles_river',
                           x_axis = 'mouse_id',
                           y_axis = 'location',
                           alpha_value = 'microbe_presence',
                           fill_value = 'diet',
                           shape_value = 'status',
                           point_size = 6,
                           y_labels = location_y_labs,
                           fill_legend_title = 'Diet',
                           fill_labels = diet_fill_labs,
                           alpha_legend_title = 'Bacterial CFUs',
                           alpha_labels = presAbs_labs,
                           shape_legend_title = 'Survival Status',
                           shape_labels = surv_labs,
                           x_name = 'Mouse',
                           y_name = 'Location',
                           wanted_title = 'CDD03 Results',
                           wanted_subtitle = 'Charles River Mice')

cdd03_tc_plot <- make_plot(input_table = proc_cfu_count,
                           wanted_experiment = 'CDD03',
                           wanted_vendor = 'taconic',
                           x_axis = 'mouse_id',
                           y_axis = 'location',
                           alpha_value = 'microbe_presence',
                           fill_value = 'diet',
                           shape_value = 'status',
                           point_size = 6,
                           y_labels = location_y_labs,
                           fill_legend_title = 'Diet',
                           fill_labels = diet_fill_labs,
                           alpha_legend_title = 'Bacterial CFUs',
                           alpha_labels = presAbs_labs,
                           shape_legend_title = 'Survival Status',
                           shape_labels = surv_labs,
                           x_name = 'Mouse',
                           y_name = 'Location',
                           wanted_title = 'CDD03 Results',
                           wanted_subtitle = 'Taconic Mice')

cdd03_cr_plot
cdd03_tc_plot
```

**Putting all experiments together in one plot**
```{r, fig.width=15, fig.height=5}
## ordering the diet column so all samples of the same diet are next to each other
ordered_proc_cfuCount <- proc_cfu_count[order(proc_cfu_count$diet),]
ordered_proc_cfuCount <- ordered_proc_cfuCount %>% 
  mutate(ord_mouse_id = fct_reorder(mouse_id, diet))

## plots
allExp_cr_plot <- make_plot(input_table = ordered_proc_cfuCount,
                           wanted_experiment = NULL,
                           wanted_vendor = 'charles_river',
                           x_axis = 'ord_mouse_id',
                           y_axis = 'location',
                           alpha_value = 'microbe_presence',
                           fill_value = 'diet',
                           shape_value = 'status',
                           point_size = 6,
                           y_labels = location_y_labs,
                           fill_legend_title = 'Diet',
                           fill_labels = diet_fill_labs,
                           alpha_legend_title = 'Bacterial CFUs',
                           alpha_labels = presAbs_labs,
                           shape_legend_title = 'Survival Status',
                           shape_labels = surv_labs,
                           x_name = 'Mouse',
                           y_name = 'Location',
                           wanted_title = 'All Experiment Results',
                           wanted_subtitle = 'Charles River Mice')

allExp_tc_plot <- make_plot(input_table = ordered_proc_cfuCount,
                           wanted_experiment = NULL,
                           wanted_vendor = 'taconic',
                           x_axis = 'ord_mouse_id',
                           y_axis = 'location',
                           alpha_value = 'microbe_presence',
                           fill_value = 'diet',
                           shape_value = 'status',
                           point_size = 6,
                           y_labels = location_y_labs,
                           fill_legend_title = 'Diet',
                           fill_labels = diet_fill_labs,
                           alpha_legend_title = 'Bacterial CFUs',
                           alpha_labels = presAbs_labs,
                           shape_legend_title = 'Survival Status',
                           shape_labels = surv_labs,
                           x_name = 'Mouse',
                           y_name = 'Location',
                           wanted_title = 'All Experiment Results',
                           wanted_subtitle = 'Taconic Mice')

allExp_cr_plot
allExp_tc_plot
```

**CDD01 Plots Together**
```{r, fig.width=10, fig.height=5.5}
cdd01_together <- put_plots_together(plot1 = cdd01_cr_plot,
                                     plot2 = cdd01_tc_plot,
                                     y_axis_label = 'Location')

cdd01_together
```

**CDD02 Plots Together**
```{r, fig.width=11, fig.height=6}
cdd02_together <- put_plots_together(plot1 = cdd02_cr_plot,
                                     plot2 = cdd02_tc_plot,
                                     y_axis_label = 'Location')

cdd02_together
```

**CDD03 Plots Together**
```{r, fig.width=11, fig.height=6}
cdd03_together <- put_plots_together(plot1 = cdd03_cr_plot,
                                     plot2 = cdd03_tc_plot,
                                     y_axis_label = 'Location')

cdd03_together
```

**All experiments plots together**
```{r, fig.width=17.5, fig.height=7}
allExp_together <- put_plots_together(plot1 = allExp_cr_plot,
                                      plot2 = allExp_tc_plot,
                                      y_axis_label = 'Location')

allExp_together
```


**Saving my Outputs**
```{r}
ggsave('../plots/cdd01_culture_results.pdf',
       plot = cdd01_together,
       width = 10,
       height = 5.5)
ggsave('../plots/cdd02_culture_results.pdf',
       plot = cdd02_together,
       width = 11,
       height = 6)
ggsave('../plots/cdd03_culture_results.pdf',
       plot = cdd03_together,
       width = 11,
       height = 6)
ggsave('../plots/allExp_culture_results.pdf',
       plot = allExp_together,
       width = 17.5,
       height = 7)

## saving processed cfu count table as a .tsv for later analysis
write_tsv(proc_cfu_count,
          '../data/misc/proc_combined_CDD_cfuCounts.tsv')
```

