rule target:
    input:
       "plots/faith_pd.pdf",
       "plots/shannon_entropy.pdf" 


rule alpha_diversity:
    input:
        metadata_FP = "data/misc/processed_metadata.tsv",
        faith_pd_FP = "data/qiime/core_outputs/faith_pd.tsv",
        shannon_FP = "data/qiime/core_outputs/shannon_entropy.tsv"
    output:
        "plots/faith_pd.pdf",
        "plots/shannon_entropy.pdf"
    shell:
        """
        Rscript scripts/alpha_div_plots.R
        """
