---
title: "alpha_div_stats"
output: html_document
date: "2023-11-09"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggpubr)
library(ggplot2)
library(magrittr)
library(qiime2R)
library(tidyverse)
library(broom)
library(cowplot)
library(ape)
library(rstatix)
library(ggh4x)
library(vegan)
library(argparse)
library(apppleplots)
```

**Functions**
```{r}
## 1
## alpha diversity file prep 
alpha_div_prep <- function(file_path1,
                           file_path2,
                           metadata_fp){
  ## faith's pd 
  faith_pd <- read_tsv(file_path1)
  names(faith_pd)[names(faith_pd) == '#SampleID'] <- 'sampleid'
  ## metadata file for both
  stat_meta <- read_tsv(metadata_fp)
  ## joining faith's pd and metadata file together into one table
  stat_meta %>% 
    filter(sampleid %in% faith_pd$sampleid) %>% 
    left_join(faith_pd, by = 'sampleid') %>% 
    filter(!is.na(diet)) %>% 
    mutate(plot_label = paste("Faith's PD by Diet")) -> faith_biom
  ## shannon entropy
  shannon <- read_tsv(file_path2)
  names(shannon)[names(shannon) == '...1'] <- 'sampleid'
  ## joining shannon and metadata file together into one table 
  stat_meta %>% 
    filter(sampleid %in% shannon$sampleid) %>% 
    left_join(shannon, by = 'sampleid') %>% 
    filter(!is.na(diet)) %>% 
    mutate(plot_label = paste('Shannon Entropy by Diet')) -> shannon_biom
  ## creating a list for outputs 
  my_list <- list(FaithPD = faith_biom,
                  Shannon = shannon_biom, 
                  Metadata = stat_meta)
  return(my_list)
}

## 2
## preps dunns post hoc results for statistical visualization
stat_plot_prep <- function(biom_table,
                           dunn_test,
                           value){
  biom_table %>% 
    group_by(diet) %>% 
    summarise(means = mean(.data[[value]])) -> mean_table
  dunn_test %>% 
    merge(mean_table, 
          by.x = c('group1'),
          by.y = c('diet')) %>% 
    rename('group1_means' = 'means') %>% 
    merge(mean_table,
          by.x = c('group2'),
          by.y = c('diet')) %>% 
    rename('group2_means' = 'means') %>% 
    mutate(diff_means = (group1_means - group2_means),
           stat_diff_means = if_else(p.adj > 0.05, 0, diff_means)) -> new_dunn
  return(new_dunn)
}
```

**File Paths**
```{r}
metadata_FP <- '../data/misc/filt_cecal_processed_metadata.tsv'
faith_pd_FP <- '../data/core_outputs/faith_pd.tsv'
shannon_FP <- '../data/core_outputs/shannon_entropy.tsv'


diet_x_labs <- c('Chow',
                 'HFt/\nHFb',
                 'HFt/\nLFb',
                 'LFt/\nHFb')

diet_y_labs <- c('HFt / HFb',
                 'HFt / LFb',
                 'LFt / HFb',
                 'LFt / LFb')
```

**Data Wrangling for Stats**
```{r}
alpha_files <- alpha_div_prep(faith_pd_FP,
                              shannon_FP,
                              metadata_FP)

faith <- alpha_files$FaithPD
shannon <- alpha_files$Shannon
metadata <- alpha_files$Metadata
```

**Faith's PD**
```{r}
## kruskal-wallis and dunns post hoc test
faith_krDunn <- apppleplots::kruskal_dunn_stats(input_table = faith,
                                                grouped_by = 'plot_label',
                                                adjust_method = 'BH',
                                                filter_adj_p_value = FALSE,
                                                formula_left = 'faith_pd',
                                                formula_right = 'diet')
faith_kruskal <- faith_krDunn$KruskalTest
faith_dunn <- faith_krDunn$DunnTest

new_faith_dunn <- stat_plot_prep(faith,
                                 faith_dunn,
                                 'faith_pd')

## linear model
sectioned_faith_lm <- apppleplots::linear_model(input_table = faith,
                                                grouped_by = 'plot_label',
                                                adjust_method = 'BH',
                                                filter_adj_p_value = FALSE,
                                                formula_left = 'faith_pd',
                                                formula_right = '(purified_diet * seq_depth) + high_fat * high_fiber + study')

faith_stat_vis <- apppleplots::stat_heat_plot(input_table = new_faith_dunn,
                                              x_value = 'group1',
                                              y_value = 'group2',
                                              x_value_type = 'discrete',
                                              y_value_type = 'discrete',
                                              pairwise = FALSE,
                                              correlation = TRUE,
                                              tile_fill = 'stat_diff_means',
                                              tile_outline_color = 'black',
                                              tile_alpha = 0.6,
                                              text_value = 'p.adj.signif',
                                              low_color = 'blue',
                                              high_color = 'green',
                                              legend_name = 'Correlation\nCoefficient',
                                              x_labels = diet_x_labs,
                                              y_labels = diet_y_labs,
                                              facet_by = 'plot_label',
                                              facet_labels = NULL,
                                              x_name = 'Group 1',
                                              y_name = 'Group 2',
                                              title_content = "Cecal Sample Faith's PD")
  
faith_stat_vis <- faith_stat_vis +
                    theme_bw(base_size = 16)

faith_stat_vis
```

**Shannon Entropy**
```{r}
## kruskal-wallis and dunns post hoc test
shannon_krDunn <- apppleplots::kruskal_dunn_stats(input_table = shannon,
                                                  grouped_by = 'plot_label',
                                                  adjust_method = 'BH',
                                                  filter_adj_p_value = FALSE,
                                                  formula_left = 'shannon_entropy',
                                                  formula_right = 'diet')
shannon_kruskal <- shannon_krDunn$KruskalTest
shannon_dunn <- shannon_krDunn$DunnTest

new_shannon_dunn <- stat_plot_prep(shannon,
                                   shannon_dunn,
                                   'shannon_entropy')

## linear model
sectioned_shannon_lm <- apppleplots::linear_model(input_table = shannon,
                                                  grouped_by = 'plot_label',
                                                  adjust_method = 'BH',
                                                  filter_adj_p_value = FALSE,
                                                  formula_left = 'shannon_entropy',
                                                  formula_right = '(purified_diet * seq_depth) + high_fat * high_fiber + study')

shannon_stat_vis <- apppleplots::stat_heat_plot(input_table = new_shannon_dunn,
                                                x_value = 'group1',
                                                y_value = 'group2',
                                                x_value_type = 'discrete',
                                                y_value_type = 'discrete',
                                                pairwise = FALSE,
                                                correlation = TRUE,
                                                tile_fill = 'stat_diff_means',
                                                tile_outline_color = 'black',
                                                tile_alpha = 0.6,
                                                text_value = 'p.adj.signif',
                                                low_color = 'blue',
                                                high_color = 'green',
                                                legend_name = 'Correlation\nCoefficient',
                                                x_labels = diet_x_labs,
                                                y_labels = diet_y_labs,
                                                facet_by = 'plot_label',
                                                facet_labels = NULL,
                                                x_name = 'Group 1',
                                                y_name = 'Group 2',
                                                title_content = "Cecal Sample Shannon Entropy")
  
shannon_stat_vis <- shannon_stat_vis +
                      theme_bw(base_size = 16)

shannon_stat_vis
```

**Saving my Outputs**
```{r}
## writing out results as a .tsv file 
write_tsv(sectioned_faith_lm, 
          "../stats/faith_diet_results.tsv")
write_tsv(new_faith_dunn, 
          "../stats/faith_dunn.tsv")
write_tsv(sectioned_shannon_lm, 
          "../stats/shannon_diet_results.tsv")
write_tsv(new_shannon_dunn, 
          "../stats/shannon_dunn.tsv")

## saving my statistical visualizations
ggsave('../plots/faith_stat_vis.pdf',
       plot = faith_stat_vis, 
       width = 4, 
       height = 4)

ggsave('../plots/shannon_stat_vis.pdf',
       plot = shannon_stat_vis, 
       width = 4, 
       height = 4)
```

