---
title: "beta_div_plots"
output: html_document
date: "2023-11-07"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggpubr)
library(ggplot2)
library(magrittr)
library(qiime2R)
library(tidyverse)
library(broom)
library(cowplot)
library(rstatix)
library(ape)
library(vegan)
library(ggh4x)
library(viridis)
library(argparse)
library(apppleplots)
```

**Functions**
```{r}
## 1 
## unweighted/weighted unifrac pcoa result, faith's pd, and shannon entropy file prep 
## going to attempt to return multiple outputs so I can just have one function for file prep
biom_table_prep <- function(unweighted_fp,
                            weighted_fp,
                            faith_fp,
                            shannon_fp,
                            metadata_file){
  ## unweighted pcoa
  unweighted <- read_qza(unweighted_fp)$data
  unweighted_var <- unweighted$ProportionExplained
  unweighted_pcoa <- unweighted$Vectors ##used for pcoa plot
  names(unweighted_pcoa)[names(unweighted_pcoa) == 'SampleID'] <- 'sampleid'
  ## weighted pcoa
  weighted <- read_qza(weighted_fp)$data
  weighted_var <- weighted$ProportionExplained
  weighted_pcoa <- weighted$Vectors
  names(weighted_pcoa)[names(weighted_pcoa) == 'SampleID'] <- 'sampleid'
  ## faith's 
  faith <- read_tsv(faith_fp)
  names(faith)[names(faith) == '#SampleID'] <- 'sampleid'
  ## shannon 
  shannon <- read_tsv(shannon_fp)
  names(shannon)[names(shannon) == '...1'] <- 'sampleid'
  ## unweighted biom 
  unweighted_pcoa %>% 
    left_join(metadata_file, by = 'sampleid') %>% 
    left_join(faith, by = 'sampleid') %>% 
    left_join(shannon, by = 'sampleid') -> unweighted_biom
  ## weighted biom
  weighted_pcoa %>% 
    left_join(metadata_file, by = 'sampleid') %>% 
    left_join(faith, by = 'sampleid') %>% 
    left_join(shannon, by = 'sampleid') -> weighted_biom
  ## creating a list to return multiple outputs 
  my_list <- list(UnweightedVar = unweighted_var, 
                  WeightedVar = weighted_var,
                  UnweightedBiom = unweighted_biom,
                  WeightedBiom = weighted_biom)
  return(my_list)
}

## 2
## this function will pull out the percent variations from a specified column so you can add it to your pcoa plots 
pcoa_ax_lab <- function(unifrac_var, col_name){
  uni_lab <- as.character(round(unifrac_var[col_name] * 100, 2))
  uni_lab <- paste0(col_name, ' - ', uni_lab, '%')
  return(uni_lab)
}
```

**File Paths**
```{r}
metadata_FP <- '../data/misc/filt_cecal_processed_metadata.tsv'
unweighted_FP <- '../data/core_outputs/unweighted_unifrac_pcoa_results.qza'
weighted_FP <- '../data/core_outputs/weighted_unifrac_pcoa_results.qza'
faith_pd_FP <- '../data/core_outputs/faith_pd.tsv'
shannon_FP <- '../data/core_outputs/shannon_entropy.tsv'

diet_labs <- 
  c('Chow', 
    'High Fat / High Fiber', 
    'High Fat / Low Fiber', 
    'Low Fat / High Fiber', 
    'Low Fat / Low Fiber')

names(diet_labs) <- c('Chow', 
                       'HF/HF', 
                       'HF/LF', 
                       'LF/HF', 
                       'LF/LF')
```

**Data Wrangling for my Files**
```{r}
## metadata 
metadata <- read_tsv(metadata_FP)

## preparing core beta diversity files for ggplot
core_files <- biom_table_prep(unweighted_FP,
                              weighted_FP,
                              faith_pd_FP,
                              shannon_FP,
                              metadata)

## extracting core beta diversity files from named list 
uw_var <- core_files$UnweightedVar
w_var <- core_files$WeightedVar
unweighted_biom <- core_files$UnweightedBiom
weighted_biom <- core_files$WeightedBiom
```

**Unweighted UniFrac PCoA**
```{r, fig.height=3.5, fig.width=11}
uw_uni_xlab <- pcoa_ax_lab(uw_var, 'PC1')
uw_uni_ylab <- pcoa_ax_lab(uw_var, 'PC2')

uw_title <- 'Cecal Sample Unweighted UniFrac PCoA Plot'

unweighted_pcoa <- apppleplots::pcoa_plots(input_table = unweighted_biom,
                                           x_value = 'PC1',
                                           y_value = 'PC2',
                                           facet_once = TRUE,
                                           facet_twice = FALSE,
                                           point_fill = 'faith_pd',
                                           point_alpha = 0.7,
                                           point_size = 2,
                                           fill_type = 'continuous',
                                           palette = 'Spectral',
                                           facet_rows = NULL,
                                           facet_cols = 'diet',
                                           row_labs = NULL,
                                           col_labs = diet_labs,
                                           legend_name = "Faith's PD",
                                           x_name = uw_uni_xlab,
                                           y_name = uw_uni_ylab,
                                           title_content = uw_title)
  
unweighted_pcoa <- unweighted_pcoa +
                    theme_bw(base_size = 14)

unweighted_pcoa
```

**Weighted UniFrac PCoA Plot**
```{r, fig.height=3.5, fig.width=11}
w_uni_xlab <- pcoa_ax_lab(w_var, 'PC1')
w_uni_ylab <- pcoa_ax_lab(w_var, 'PC2')

w_title <- 'Cecal Sample Weighted UniFrac PCoA Plot'

weighted_pcoa <- apppleplots::pcoa_plots(input_table = weighted_biom,
                                         x_value = 'PC1',
                                         y_value = 'PC2',
                                         facet_once = TRUE,
                                         facet_twice = FALSE,
                                         point_fill = 'faith_pd',
                                         point_alpha = 0.7,
                                         point_size = 2,
                                         fill_type = 'continuous',
                                         palette = 'Spectral',
                                         facet_rows = NULL,
                                         facet_cols = 'diet',
                                         row_labs = NULL,
                                         col_labs = diet_labs,
                                         legend_name = "Faith's PD",
                                         x_name = w_uni_xlab,
                                         y_name = w_uni_ylab,
                                         title_content = w_title)
  
weighted_pcoa <- weighted_pcoa +
                    theme_bw(base_size = 14)
  
weighted_pcoa
```

**Saving my Outputs**
```{r}
ggsave('../plots/unweighted_unifrac_pcoa.pdf',
       plot = unweighted_pcoa, 
       width = 11, 
       height = 3.5)

ggsave('../plots/weighted_unifrac_pcoa.pdf',
       plot = weighted_pcoa, 
       width = 11, 
       height = 3.5)
```

