---
title: "histo_percentages"
output: html_document
date: "2024-03-29"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(magrittr)
library(tidyverse)
library(broom)
library(cowplot)
library(rstatix)
library(ggpubr)
library(glue)
library(apppleplots)
```

**Functions**
```{r}
## combining histo percentages file with metadata
file_prep <- function(histo_perc_fp,
                      histo_fp){
  ## histo percentages file
  histo_perc <- read_tsv(histo_perc_fp)
  ## processed histopathology file
  histo <- read_tsv(histo_fp)
  histo %>% 
    filter(tissue == 'cecum') -> histo
  ## merging the two tables together for metadata info
  histo %>% 
    left_join(histo_perc, by = 'mouse_id') %>% 
    gather(contains(c('perc')), key = category, value = percentage) -> big_histo
  return(big_histo)
}
```

**File Paths**
Can use processed histopathology file for this since it already contains the needed metadata!
```{r}
histo_perc_FP <- '../data/misc/cecum_histo_percentages.txt'
histo_FP <- '../data/misc/processed_histopathology.tsv'

## plot relabeling lists
perc_labs <- c('Epithelial Integrity',
               'Number of Goblet Cells',
               'Neutrophil Infiltration',
               'Submucosal Edema')
names(perc_labs) <- c('perc_epithelial_integrity',
                      'perc_goblet_cells',
                      'perc_PNM_infil',
                      'perc_submuc_edema')
diet_x_labs <- c('Chow',
                 'HFt/\nHFb',
                 'HFt/\nLFb',
                 'LFt/\nHFb',
                 'LFt/\nLFb')
```

**Data Wrangling**
```{r}
proc_histo_perc <- file_prep(histo_perc_FP,
                             histo_FP)
```
**Stats**
```{r}
perc_stats <- apppleplots::kruskal_dunn_stats(input_table = proc_histo_perc,
                                              grouped_by = 'category',
                                              adjust_method = 'BH',
                                              filter_adj_p_value = FALSE,
                                              formula_left = 'percentage',
                                              formula_right = 'diet')
  
histo_perc_kruskal <- perc_stats$KruskalTest
histo_perc_dunn <- perc_stats$DunnTest
```

**Plot**
```{r, fig.width=15, fig.height=5}
histo_perc_plot <- apppleplots::facet_once_plots(input_table = proc_histo_perc,
                                                 stat_on_plot = TRUE,
                                                 x_value = 'diet',
                                                 y_value = 'percentage',
                                                 x_value_type = 'discrete',
                                                 grouped_by = 'diet',
                                                 point_alpha = 0.4,
                                                 x_labels = diet_x_labs,
                                                 facet_by = 'category',
                                                 facet_labels = perc_labs,
                                                 stat_table = histo_perc_dunn,
                                                 x_name = 'Diet',
                                                 y_name = 'Percentage',
                                                 title_content = 'Cecal High Histopathology Scores per Diet')
  
histo_perc_plot <- histo_perc_plot +
                    theme_bw(base_size = 20)

histo_perc_plot
```

**Saving my Outputs**
```{r}
## as a pdf
ggsave('../plots/cecum_histoPerc.pdf',
       plot = histo_perc_plot,
       width = 15,
       height = 5)

## as an rdata object 
save(histo_perc_plot,
     file = '../../figures/cecum_histo_percent.rdat')

## stats 
write_tsv(histo_perc_dunn,
          '../stats/cecum_histoPerc_dunn.tsv')
```

