---
title: "histo_part_two"
output: html_document
date: "2023-12-21"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(magrittr)
library(tidyverse)
library(broom)
library(cowplot)
library(rstatix)
library(ggpubr)
```

**Functions**
```{r}
## prepping all of my files for downstream analysis
file_prep <- function(histo_fp,
                      histo_cat_fp,
                      metadata_fp, 
                      hypoxia_fp){
  ## reading in histo and histo categories file
  histo <- read_csv(histo_fp)
  colnames(histo) <- c('mouse_id',
                       'cecum_total',
                       'colon_total')
  histo_cat <- read_tsv(histo_cat_fp)
  histo %>% 
    left_join(histo_cat, by = 'mouse_id') %>% 
    na.omit() -> histo
  ## reading in metadata file
  metadata <- read_tsv(metadata_fp) %>% 
    select(!c(tube_num, date, day_post_inf, sample_type, corr_sample_num))
  ## putting them together
  metadata %>% 
    left_join(histo, by = 'mouse_id') %>% 
    gather(contains(c('cecum', 'colon')), key = category, value = score) %>% 
    separate_wider_delim(cols = 'category',
                         delim = '_',
                         names = c('tissue',
                                   'category'),
                         cols_remove = FALSE,
                         too_many = 'merge') -> big_histo
  ## reading in hypoxia file
  hypoxia <- read_csv(hypoxia_fp)
  hypoxia %>% 
    mutate(order = ifelse(location == 'Cecum', 1, location),
           order = ifelse(order == 'Prox_colon', 2, order),
           order = ifelse(order == 'Dist_colon', 3, order)) %>% 
    arrange(order) %>% 
    select(-diet) -> hypoxia
  ## putting them all together into one big table
  big_histo %>% 
    left_join(hypoxia, by = 'mouse_id') %>% 
    na.omit() -> histo_hypox_table
  ## creating a list of outputs
  my_list <- list(Histopathology = histo,
                  Metadata = metadata,
                  Hypoxia = hypoxia,
                  HistoTable = big_histo,
                  HistoHypoxTable = histo_hypox_table)
  return(my_list)
}

## this function creates the hypoxia and histopathology score comparison plot
histo_comp_plot <- function(comp_table,
                            histo_facet_labs,
                            title){
  comp_table %>% 
    ggplot(aes(x = score, y = fluorescence)) +
    geom_jitter(alpha = 0.4, width = 0.1, height = 0) +
    geom_smooth(method = 'lm', se = FALSE) +
    facet_grid(category~diet,
               labeller = labeller(category = histo_facet_labs,
                                   diet = diet_labs)) +
    theme_bw() +
    theme(strip.text.y = element_text(angle = 0)) +
    labs(x = 'Score',
         y = 'Fluorescence',
         title = title) -> comp_plot
  return(comp_plot)
}

## runs linear modeling on the table, diet, location, and toxin/metabolite wanted and returns full results 
## along with a table containing the r2 and p-value 
## this goes into the following function with a for loop 
r2_value <- function(biom_table,
                     wanted_diet,
                     category_col,
                     wanted_category,
                     wanted_conc_value){
  ## to get r squared value and p value
  biom_table %>% 
    filter(diet == wanted_diet,
           .data[[category_col]] == wanted_category) %>%
    do(glance(lm(fluorescence ~ .data[[wanted_conc_value]],
                 data = .))) -> lm_glance
  output <- list(r_squared = lm_glance$r.squared,
                 p_value = lm_glance$p.value)
  ## to get estimate and place it with the overall output table
  biom_table %>% 
    filter(diet == wanted_diet,
           .data[[category_col]] == wanted_category) %>%
    do(tidy(lm(fluorescence ~ .data[[wanted_conc_value]],
                 data = .))) %>% 
    filter(term != '(Intercept)') -> lm_full
  output <- as_tibble(output) %>%
            mutate(diet = paste(wanted_diet),
                   category = paste(wanted_category),
                   just_r = sqrt(r_squared),
                   estimate = lm_full$estimate,
                   r_direct = if_else(estimate < 0, just_r * -1, just_r))
  my_list <- list(LinearModel = lm_full,
                  WantedStats = output)
  return(my_list)
}

## creating a nested for loop since running this function individually is a nightmare
r2_value_for_loop <- function(biom_table,
                              wanted_col,
                              wanted_conc) {
  ## nested for loop for the r squared and p values 
  output <- tibble()
  for(i in unique(unlist(biom_table$diet))) {
    for(j in unique(unlist(biom_table[wanted_col]))) {
        tmp_output <- r2_value(biom_table,
                               i,
                               wanted_col,
                               j,
                               wanted_conc)$WantedStats
        output <- bind_rows(output, tmp_output)
      }
    }
  return(output)
}

## statistical visualization plot function
stat_plot <- function(stat_table,
                      x_lab_list,
                      y_lab_list,
                      facet_labels){
  stat_table %>% 
    ggplot(aes(x = category, y = diet)) +
    geom_tile(aes(fill = r_direct), color = 'black', alpha = 0.6) +
    geom_text(aes(label = signif)) +
    scale_fill_gradient2(low = 'blue', high = 'green', name = "Correlation\nCoefficient", limits = c(-0.7, 0.7)) +
    scale_x_discrete(labels = x_lab_list) +
    scale_y_discrete(labels = y_lab_list) +
    facet_wrap(~tissue,
               labeller = labeller(tissue = facet_labels)) +
    theme_bw() +
    xlab("Category") +
    ylab("Diet") -> plot
  return(plot)
}
```

**File Paths**
```{r}
histo_cat_FP <- '../data/misc/histo_categories.txt'
histo_FP <- '../data/misc/histo_data.csv'
metadata_FP <- '../data/misc/filt_cecal_processed_metadata.tsv'
hypoxia_FP <- '../data/misc/pimid_fluor.csv'

diet_x_labs <- c('Chow',
                 'HFt/\nHFb',
                 'HFt/\nLFb',
                 'LFt/\nHFb',
                 'LFt/\nLFb')

diet_y_labs <- c('Chow',
                  'HFt/HFb',
                  'HFt/LFb',
                  'LFt/HFb',
                  'LFt/LFb')

diet_labs <- 
    c('Chow', 
      'High Fat / High Fiber', 
      'High Fat / Low Fiber', 
      'Low Fat / High Fiber', 
      'Low Fat / Low Fiber')

names(diet_labs) <- c('Chow', 
                      'HF/HF', 
                      'HF/LF', 
                      'LF/HF', 
                      'LF/LF')

cecum_labels <- c('Total',
                  'Submucosal Edema',
                  'Neutrophil Infiltration',
                  'Number of Goblet Cells',
                  'Epithelial Integrity')
names(cecum_labels) <- c('cecum_total',
                         'cecum_submuc_edema',
                        'cecum_PNM_infil',
                        'cecum_num_gobletCells',
                        'cecum_epithelial_integrity')

colon_labels <- c('Total',
                  'Severity of Inflammation',
                  'Extent of Injury',
                  'Epithelial Regeneration',
                  'Crypt Damage')
names(colon_labels) <- c('colon_total',
                         'colon_inflamm_sev',
                        'colon_injury_extent',
                        'colon_epithelial_regen',
                        'colon_crypt_damage')

tissue_labs <- c('Cecum',
                 'Colon')
names(tissue_labs) <- c('cecum',
                        'colon')
```

**Data Wrangling**
This data does not contain replicate one!
```{r}
wanted_files <- file_prep(histo_FP,
                          histo_cat_FP,
                          metadata_FP,
                          hypoxia_FP)

histo <- wanted_files$Histopathology
metadata <- wanted_files$Metadata
hypoxia <- wanted_files$Hypoxia
big_histo <- wanted_files$HistoTable
histo_hypox_table <- wanted_files$HistoHypoxTable
```


**Hypoxia and Histopathology Comparison Plots**
```{r, fig.height=5, fig.width=10}
## cecum
histo_hypox_table %>% 
  filter(location == 'Cecum',
         tissue == 'cecum') -> cecum_hypox_table 

cecal_hypox_plot <- histo_comp_plot(cecum_hypox_table,
                                    cecum_labels,
                                    'Cecum Tissue Damage by Hypoxia')
## colon
histo_hypox_table %>% 
  filter(location != 'Cecum',
         tissue == 'colon') -> colon_hypox_table

colon_hypox_plot <- histo_comp_plot(colon_hypox_table,
                                    colon_labels,
                                    'Colon Tissue Damage by Hypoxia')


cecal_hypox_plot
colon_hypox_plot
```

**Comparison Plots Together**
```{r, fig.width=10, fig.height=9}
plot_grid(cecal_hypox_plot,
          colon_hypox_plot,
          nrow = 2,
          labels = c('a)', 'b)'),
          align = c('hv'),
          axis = c('tblr')) -> comp_plots

comp_plots
```

**Histo and Hypoxia Comparison Stats**
Cecum
```{r}
cecum_comp_stat_table <- r2_value_for_loop(cecum_hypox_table,
                                            'category',
                                            'score')

cecum_comp_stat_table['signif'] <- symnum(cecum_comp_stat_table$p_value,
                                           cutpoints = c(0, 0.0001, 0.001, 0.01, 0.05, 1),
                                           symbols = c("****", "***", "**", "*", "ns"),
                                           abbr.colnames = FALSE,
                                           na = "")
cecum_comp_stat_table %>% 
  mutate(tissue = paste('cecum')) -> cecum_comp_stat_table
```

Colon
```{r}
colon_comp_stat_table <- r2_value_for_loop(colon_hypox_table,
                                            'category',
                                            'score')
colon_comp_stat_table %>% 
  mutate(p_value = ifelse(is.na(p_value), 1, p_value),
         estimate = ifelse(is.na(estimate), 1, estimate),
         r_direct = ifelse(is.na(r_direct), 0, r_direct)) -> colon_comp_stat_table

colon_comp_stat_table['signif'] <- symnum(colon_comp_stat_table$p_value,
                                           cutpoints = c(0, 0.0001, 0.001, 0.01, 0.05, 1),
                                           symbols = c("****", "***", "**", "*", "ns"),
                                           abbr.colnames = FALSE,
                                           na = "")
colon_comp_stat_table %>% 
  mutate(tissue = paste('colon')) -> colon_comp_stat_table
```

**Visualization** 
```{r}
colon_x_labs <- c('Crypt\nDamage',
                  'Epithelial\nRegeneration',
                  'Severity of\nInflammation',
                  'Extent of\nInjury',
                  'Total')

cecum_x_labs <- c('Epithelial\nIntegrity',
                  'Number of\nGoblet Cells',
                  'Neutrophil\nInfiltration',
                  'Submucosal\nEdema',
                  'Total')

colon_stat_vis <- stat_plot(colon_comp_stat_table,
                            colon_x_labs,
                           diet_y_labs,
                           tissue_labs)

cecum_stat_vis <- stat_plot(cecum_comp_stat_table,
                            cecum_x_labs,
                           diet_y_labs,
                           tissue_labs)
colon_stat_vis
cecum_stat_vis
```

**Stat Plots Together**
```{r, fig.width=10, fig.height=3.3}
title <- ggdraw() +
  draw_label('Histopathology and Hypoxia Concentration Comparisons',
             size = 14,
             hjust = 0.86,
             vjust = 0.3)

pre_comp_stat_vis <- plot_grid(cecum_stat_vis +
                             theme(legend.position = "none",
                                   axis.title.x = element_blank()), 
                           colon_stat_vis +
                             theme(axis.title.y = element_blank(),
                                   axis.text.y = element_blank(),
                                   axis.ticks.y = element_blank(),
                                   axis.title.x = element_blank()),
                           rel_widths = c(0.95, 1))

comp_stat_vis <- plot_grid(title,
                           pre_comp_stat_vis,
                           ncol = 1,
                           rel_heights = c(0.065, 1),
                           align = c('hv'),
                           axis = c('tblr'))

comp_stat_vis
```

**Comp Plots Together**
```{r, fig.width=10, fig.height=12}
plot_grid(comp_plots, comp_stat_vis,
          nrow = 2,
          labels = c(' ', 'c)'),
          rel_heights = c(1, 0.3),
          axis = c('tblr'),
          align = c('hv')) -> comp_plots_together

comp_plots_together
```

**Saving my Outputs**
```{r}
ggsave('../plots/histo_categories_hypox.pdf',
       plot = comp_plots_together,
       width = 10,
       height = 12)

## as an rdata object 
save(cecal_hypox_plot,
     file = '../../figures/cecum_histo_hypox.rdata')
save(colon_hypox_plot,
     file = '../../figures/colon_histo_hypox.rdata')

## stats
write_tsv(comp_stat_table,
          '../stats/histo_categories_hypox.tsv')
```

