---
title: "beta_div_stats"
output: html_document
date: "2023-09-14"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(qiime2R)
library(tidyverse)
library(cowplot)
library(magrittr)
library(vegan)
library(viridis)
library(microshades)
library(phyloseq)
library(ggh4x)
library(broom)
library(rstatix)
library(dunn.test)
```

**Beta Diversity Functions**
```{r}
## for distance matrix processing
## for beta diversity statistical analysis 
dist_matrix_prep <- function(metadata_file,
                             dist_matrix_fp){
  ## metadata
  metadata <- metadata_file
  ## distance matrix
  dist <- read_tsv(dist_matrix_fp)
  names(dist)[names(dist) == '...1'] <- 'sampleid'
  dist %>% 
    gather(-sampleid, key = sample_col, value = dist) %>% 
    filter(sampleid %in% metadata$sampleid) %>% 
    filter(sample_col %in% metadata$sampleid) %>% 
    spread(sample_col, dist) -> dist_long
  dist_long %>% 
    select(-sampleid) -> dist_proc
  metadata %>% 
    arrange(sampleid) -> metadata
  metadata %>% 
    filter(sampleid %in% dist_long$sampleid) -> filt_meta
  dist_proc <- as.matrix(dist_proc)
  row.names(dist_proc) <- colnames(dist_proc)
  filt_meta <- filt_meta[order(filt_meta$sampleid),]
  ## list of outputs
  my_list <- list(Metadata = filt_meta,
                  DistanceMatrix = dist_proc)
  return(my_list)
}



## beta diversity adonis2 testing function
adonis_test <- function(dist_matrix,
                        metadata_file){
  adonis_results <- adonis2(as.dist(dist_matrix) ~ (purified_diet * high_fat * high_fiber * low_fiber) + study,
                            data = metadata_file,
                            permutations = 999, 
                            parallel = 4)
  adonis_results <- tidy(adonis_results)
  adonis_results['signif'] <- symnum(adonis_results$p.value,
                                     cutpoints = c(0, 0.0001, 0.001, 0.01, 0.05, 0.1, 1),
                                     symbols = c("****", "***", "**", "*", "+", "ns"),
                                     abbr.colnames = FALSE,
                                     na = "")
  return(adonis_results)
}

## to run an adonis test by day relative to infection
adonis_per_day <- function(metadata_file,
                           day_filter,
                           dist_fp){
  metadata_file %>% 
    filter(day_post_inf == day_filter) -> day_metadata
  dist_files <- dist_matrix_prep(day_metadata,
                                 dist_fp)
  dist <- dist_files$DistanceMatrix
  filt_meta <- dist_files$Metadata
  adonis_results <- adonis_test(dist,
                                filt_meta)
  adonis_results$day_post_inf <- day_filter
  return(adonis_results)
}

## function that will run a for loop to stratify the adonis test by a certain variable
adonis_for_loop <- function(metadata_file,
                            dist_matrix_fp,
                            strat_column){
  output <- list()
  for (i in unique(unlist(metadata_file[strat_column]))) {
    tmp_output <- adonis_per_day(metadata_file,
                                 i,
                                 dist_matrix_fp)
    tmp_output[strat_column] <- i
    # when saving something as a named list in R, 
    # we need to use the double brackets
    # output[[as.character(i)]] <- tmp_output
    
    # if we're appending a higher dimensional object (df, matrix, vector,) 
    # to a list, we need to wrap it in a list() within the append function.
    output <- append(output, list(tmp_output))
  }
  output <- bind_rows(output)
  return(output)
}
```

**File paths for all needed files**
```{r}
metadata_FP <- '../data/misc/s1_filt_comp_metadata.tsv'
uw_dist_fp <- '../data/s1_filt_core/uw_dist_matrix.tsv'
w_dist_fp <- '../data/s1_filt_core/w_dist_matrix.tsv'

## for adonis for loop function
day_strat <- 'day_post_inf'
```

**Beta Diversity Statistical Analysis**
```{r}
## weighted unifrac 
stat_meta <- read_tsv(metadata_FP)
names(stat_meta)[names(stat_meta) == '#SampleID'] <- 'sampleid'

## adding a low fiber diet column for the adonis testing 
stat_meta %>% 
  mutate(diet_true = diet,
         diet_true = if_else(day_post_inf == -15, "Chow", diet_true),
         low_fiber = case_when(
            diet_true == 'HF/LF' ~ 1,
            diet_true == 'LF/LF' ~ 1,
            .default = 0
          )) %>% 
  select(-diet_true) -> stat_meta

w_dist_files <- dist_matrix_prep(stat_meta,
                                 w_dist_fp)

w_dist <- w_dist_files$DistanceMatrix
filt_stat_meta <- w_dist_files$Metadata

 
w_adonis <- adonis_test(w_dist,
                        filt_stat_meta)


## unweighted unifrac
uw_dist_files <- dist_matrix_prep(stat_meta,
                                  uw_dist_fp)

uw_dist <- uw_dist_files$DistanceMatrix
filt_stat_meta <- uw_dist_files$Metadata
 
uw_adonis <- adonis_test(uw_dist,
                         filt_stat_meta)
```

**Adonis Test by Days Relative to Mouse Infection**
running Adonis tests based on the days relative to mouse infection to get a better idea of what is going on in our beta diversity.
```{r}
unweighted_by_day <- adonis_for_loop(filt_stat_meta,
                                     uw_dist_fp,
                                     day_strat)



weighted_by_day <- adonis_for_loop(filt_stat_meta,
                                   w_dist_fp,
                                   day_strat)
```

**Saving my Outputs**
```{r}
write_tsv(w_adonis, '../stats/w_adonis_results.tsv')
write_tsv(uw_adonis, '../stats/uw_adonis_results.tsv')
write_tsv(unweighted_by_day, '../stats/uw_adonis_by_day.tsv')
write_tsv(weighted_by_day, '../stats/w_adonis_by_day.tsv')

## as an rdata object
save(w_adonis,
     file = '../../figures/w_adonis_results.rdata')
save(uw_adonis,
     file = '../../figures/uw_adonis_results.rdata')
save(unweighted_by_day,
     file = '../../figures/uw_adonis_by_day.rdata')
save(weighted_by_day,
     file = '../../figures/w_adonis_by_day.rdata')
```

