---
title: "bile_acid"
output: html_document
date: "2023-12-18"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(rstatix)
library(ggplot2)
library(ggpubr)
library(ggh4x)
library(cowplot)
library(magrittr)
```

**Functions**
```{r}
there will be functions here eventually
```

**File Paths**
```{r}
bile_acid_FP <- '../../colon/data/misc/bile_acid.txt'

inhibitor_list <- c('_a-MCA',
                    '_b-MCA',
                    '_LCA',
                    '_DCA',
                    '_CDCA',
                    '_UDCA')

promoter_list <- c('_T-CA',
                   '_CA')
```

**Reading in Bile Acid File and Adding what I want to it**
```{r}
bile_acid <- read_tsv(bile_acid_FP)

bile_acid %>% 
 mutate(temp_id = paste(tube_label, reisdorph_lab_id, sep = ".")) %>% 
 select(temp_id, tube_label, reisdorph_lab_id, collection_date, sample_type, contains(unlist(inhibitor_list))) %>% 
 gather(contains('acid'), key = bile_acid, value = concentration) %>% 
 mutate(c_diff_effect = paste('inhibitor')) %>% 
 filter(concentration != '#VALUE!') -> inhibit_bile

bile_acid %>% 
 mutate(temp_id = paste(tube_label, reisdorph_lab_id, sep = ".")) %>% 
 select(temp_id, tube_label, reisdorph_lab_id, collection_date, sample_type, contains(unlist(promoter_list))) %>% 
 gather(contains('acid'), key = bile_acid, value = concentration) %>% 
 mutate(c_diff_effect = paste('promoter')) -> promote_bile

big_bile_acid <- rbind(inhibit_bile,
                       promote_bile)

## adding diet key column and taking table from wide to long format
big_bile_acid %>% 
  na.omit() %>% 
  mutate(diet = ifelse(sample_type == 'Ctrl', 'LF/LF', sample_type),
         diet = ifelse(diet == 'Ctrl+F', 'LF/HF', diet),
         diet = ifelse(diet == 'WD', 'HF/LF', diet),
         diet = ifelse(diet == 'WD+F', 'HF/HF', diet)) -> big_bile_acid

## changing all undetectable values to 0 
big_bile_acid$concentration[big_bile_acid$concentration == '<LOD' | big_bile_acid$concentration == '<LOQ'] <- 0

big_bile_acid %>% 
  mutate(concentration = as.numeric(concentration),
         conc_normalized = concentration + 2) -> big_bile_acid
```
**Stats**
```{r}
## kruskal test
big_bile_acid %>% 
  group_by(c_diff_effect, bile_acid) %>% 
  do(tidy(kruskal.test(concentration ~ diet,
             data = .))) %>% 
  ungroup() %>% 
  arrange(p.value) %>% 
  mutate(p.adj = p.adjust(p.value,
                          method = "BH"),
        test_id = paste(c_diff_effect, bile_acid, sep = "_")) -> kruskal

## dunns post hoc test
big_bile_acid %>% 
  group_by(c_diff_effect, bile_acid) %>% 
  mutate(test_id = paste(c_diff_effect, bile_acid, sep = "_")) %>%
  filter(test_id %in% kruskal$test_id) %>%
  dunn_test(concentration ~ diet,
            p.adjust.method = 'BH',
            data = .) %>% 
  add_xy_position(scales = 'free') -> dunn
```

**A plot**
```{r}
big_bile_acid %>% 
  ggplot(aes(x = diet, y = concentration)) +
    geom_boxplot(aes(group = diet), outlier.shape = NA) +
    geom_jitter(alpha = 0.4, width = 0.1, height = 0) +
    theme_bw() +
    facet_wrap(~c_diff_effect,
               scales = "free_y") +
    stat_pvalue_manual(dunn,
                       tip.length = 0.01,
                       label = 'p.adj.signif',
                       hide.ns = TRUE)
```




**A plot**
```{r, fig.width=15, fig.height=5, warning=FALSE}
big_bile_acid %>% 
  ggplot(aes(x = diet, y = conc_normalized)) +
    geom_boxplot(aes(group = diet), outlier.shape = NA) +
    geom_jitter(alpha = 0.4, width = 0.1, height = 0) +
    facet_nested(~c_diff_effect + bile_acid) +
    theme_bw() +
    scale_y_log10()
```


