---
title: "relAbun_plots"
output: html_document
date: "2024-11-06"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(magrittr)
library(broom)
library(apppleplots)
library(rstatix)
library(qiime2R)
```

**Functions**
```{r}
abun_file_prep <- function(metadata_fp,
                                  tax_fp,
                                  otu_table_fp,
                                  tax_level,
                                  wanted_tax){
  ## metadata
  metadata <- read_tsv(metadata_fp)
  names(metadata)[names(metadata) == '#SampleID'] <- 'sampleid'
  ## taxonomy
  taxonomy <- read_qza(tax_fp)$data %>% 
    parse_taxonomy() %>% 
    rownames_to_column('asv')
  ## otu table 
  otu_table <- read_qza(otu_table_fp)$data
  otu_table %>% 
    as_tibble(rownames = 'asv') %>% 
    gather(-asv, key = sampleid, value = abun) %>% 
    group_by(sampleid) %>% 
    mutate(rel_abun = abun/sum(abun)) %>% 
    mutate(rel_abun = rel_abun + 0.000001) -> otu_table
  ## joining all tables together 
  otu_table %>% 
    left_join(metadata, by = 'sampleid') %>% 
    left_join(taxonomy, by = 'asv') -> abun_table
  abun_table %>% 
    group_by(sampleid, diet, mouse_id,
             experiment_set, vendor, mouse_sex, day_post_inf,
             .data[[tax_level]]) %>% 
    summarise(rel_abund = sum(rel_abun)) %>% 
    filter(.data[[tax_level]] %in% wanted_tax) %>% 
    mutate(mouse_fact = as.factor(mouse_id)) -> abun_filt
  ## creating a list for my outputs
  my_list <- list(Metadata = metadata,
                  Taxonomy = taxonomy,
                  OTUTable = otu_table,
                  AbundanceTable = abun_filt)
  return(my_list)
}

## plot function
abun_plots <- function(input_table,
                       x_axis,
                       y_axis,
                       x_axis_breaks,
                       x_axis_labels,
                       x_group_by,
                       fill_by,
                       brewer_palette,
                       legend_name,
                       legend_labels,
                       facet_rows,
                       facet_cols,
                       title,
                       x_name,
                       y_name){
  ## first plot
  input_table %>%
    ggplot(aes(x = .data[[x_axis]], y = .data[[y_axis]])) +
    scale_y_continuous(trans = 'log10') +
    scale_x_continuous(breaks = x_axis_breaks,
                       labels = x_axis_labels) +
    geom_boxplot(aes(group = .data[[x_group_by]]), outlier.shape = NA) +
    geom_jitter(aes(fill = .data[[fill_by]]), width = 0.1, height = 0, alpha = 0.7, pch = 21, size = 3) +
    scale_fill_brewer(palette = brewer_palette, 
                      name = legend_name,
                      labels = legend_labels) +
    theme_bw(base_size = 20) +
    facet_grid(rows = vars(.data[[facet_rows]]),
               cols = vars(.data[[facet_cols]])) +
    theme(strip.text.y.right = element_text(angle = 0)) +
    ggtitle(title) +
    ylab(y_name) +
    xlab(x_name) -> plot
  
  return(plot)
}
```

**File paths**
```{r}
## baseline and day 3 microbiome
d3_metadata_FP <- '../data/misc/oldNew_comp_d15-d3_metadata.tsv'
d3_otu_table_FP <- '../data/baseline_day3_qiime/total_sum_otu_table.qza'
d3_tax_FP <- '../data/baseline_day3_qiime/taxonomy.qza'

## global lists
wanted_family <- c('Enterobacteriaceae', 'Lactobacillaceae', 'Lachnospiraceae', 'Enterococcaceae',
                   'Staphylococcaceae', 'Bacteroidaceae', 'Tannerellaceae', 'Morganellaceae')
wanted_genus <- c('Akkermansia', 'Enterococcus', 'Escherichia-Shigella', 'Proteus', 
                  'Bacteroides', 'Lactobacillus', 'Staphylococcus', 'Muribaculaceae',
                  'Clostridioides')

## new plot labels 
exp_x_labs <- c('Old\nAnschutz\n(2020)',
                'U of\nArizona',
                'New\nAnschutz\n(2024)')

exp_labs <- c('Old Anschutz (2020)',
              'New Anschutz (2024)',
              'U of Arizona')
names(exp_labs) <- c('first_set_anschutz',
                     'new_exp_anschutz',
                     'second_set_arizona')
```

**Data wrangled**
```{r}
## family level
family_abun_files <- abun_file_prep(metadata_fp = d3_metadata_FP,
                                    tax_fp = d3_tax_FP,
                                    otu_table_fp = d3_otu_table_FP,
                                    tax_level = 'Family',
                                    wanted_tax = wanted_family)

family_abun_table <- family_abun_files$AbundanceTable

family_abun_table <- family_abun_table %>% 
  mutate(exp_order = case_when(
    experiment_set == 'first_set_anschutz' ~ 1,
    experiment_set == 'second_set_arizona' ~ 2,
    experiment_set == 'new_exp_anschutz' ~ 3
  ))

## genus level 
genus_abun_files <- abun_file_prep(metadata_fp = d3_metadata_FP,
                                   tax_fp = d3_tax_FP,
                                   otu_table_fp = d3_otu_table_FP,
                                   tax_level = 'Genus',
                                   wanted_tax = wanted_genus)

genus_abun_table <- genus_abun_files$AbundanceTable

genus_abun_table <- genus_abun_table %>% 
  mutate(exp_order = case_when(
    experiment_set == 'first_set_anschutz' ~ 1,
    experiment_set == 'second_set_arizona' ~ 2,
    experiment_set == 'new_exp_anschutz' ~ 3
  ))
```

**Plots**
family level - colored by vendor and diet 
```{r, fig.width=15, fig.height=13}
## vendor 
vendor_familyAbun_plot <- abun_plots(input_table = family_abun_table,
                                     x_axis = 'exp_order',
                                     y_axis = 'rel_abund',
                                     x_axis_breaks = c(1, 2, 3),
                                     x_axis_labels = exp_x_labs,
                                     x_group_by = 'exp_order',
                                     fill_by = 'vendor',
                                     brewer_palette = 'Pastel1',
                                     legend_name = 'Mouse Vendor',
                                     legend_labels = c('Charles River', 'Taconic'),
                                     facet_rows = 'Family',
                                     facet_cols = 'day_post_inf',
                                     title = 'All Exp Microbes by Vendor',
                                     x_name = 'Experiment',
                                     y_name = 'Relative Abundance (log10)')

## diet 
diet_familyAbun_plot <- abun_plots(input_table = family_abun_table,
                                     x_axis = 'exp_order',
                                     y_axis = 'rel_abund',
                                     x_axis_breaks = c(1, 2, 3),
                                     x_axis_labels = exp_x_labs,
                                     x_group_by = 'exp_order',
                                     fill_by = 'diet',
                                     brewer_palette = 'Spectral',
                                     legend_name = 'Mouse Diet',
                                     legend_labels = c('Chow',
                                                       'HFt / HFb',
                                                       'HFt / LFb',
                                                       'LFt / HFb',
                                                       'LFt / LFb'),
                                     facet_rows = 'Family',
                                     facet_cols = 'day_post_inf',
                                     title = 'All Exp Microbes by Diet',
                                     x_name = 'Experiment',
                                     y_name = 'Relative Abundance (log10)')

vendor_familyAbun_plot
diet_familyAbun_plot
```

genus level - colored by vendor and diet
```{r, fig.width=15, fig.height=13}
## vendor 
vendor_genusAbun_plot <- abun_plots(input_table = genus_abun_table,
                                    x_axis = 'exp_order',
                                    y_axis = 'rel_abund',
                                    x_axis_breaks = c(1, 2, 3),
                                    x_axis_labels = exp_x_labs,
                                    x_group_by = 'exp_order',
                                    fill_by = 'vendor',
                                    brewer_palette = 'Pastel1',
                                    legend_name = 'Mouse Vendor',
                                    legend_labels = c('Charles River', 'Taconic'),
                                    facet_rows = 'Genus',
                                    facet_cols = 'day_post_inf',
                                    title = 'All Exp Microbes by Vendor',
                                    x_name = 'Experiment',
                                    y_name = 'Relative Abundance (log10)')

## diet 
diet_genusAbun_plot <- abun_plots(input_table = genus_abun_table,
                                  x_axis = 'exp_order',
                                  y_axis = 'rel_abund',
                                  x_axis_breaks = c(1, 2, 3),
                                  x_axis_labels = exp_x_labs,
                                  x_group_by = 'exp_order',
                                  fill_by = 'diet',
                                  brewer_palette = 'Spectral',
                                  legend_name = 'Mouse Diet',
                                  legend_labels = c('Chow',
                                                    'HFt / HFb',
                                                    'HFt / LFb',
                                                    'LFt / HFb',
                                                    'LFt / LFb'),
                                  facet_rows = 'Genus',
                                  facet_cols = 'day_post_inf',
                                  title = 'All Exp Microbes by Diet',
                                  x_name = 'Experiment',
                                  y_name = 'Relative Abundance (log10)')

vendor_genusAbun_plot
diet_genusAbun_plot
```


```{r, fig.width=12.5, fig.height=8.5}
mini_genusAbun_table <- genus_abun_table %>% 
  filter(Genus == 'Escherichia-Shigella' | Genus == 'Enterococcus' | Genus == 'Proteus' |
           Genus == 'Staphylococcus' | Genus == 'Clostridioides')

## vendor
miniVendor_genusAbun_plot <- abun_plots(input_table = mini_genusAbun_table,
                                        x_axis = 'exp_order',
                                        y_axis = 'rel_abund',
                                        x_axis_breaks = c(1, 2, 3),
                                        x_axis_labels = exp_x_labs,
                                        x_group_by = 'exp_order',
                                        fill_by = 'vendor',
                                        brewer_palette = 'Pastel1',
                                        legend_name = 'Mouse Vendor',
                                        legend_labels = c('Charles River', 'Taconic'),
                                        facet_rows = 'Genus',
                                        facet_cols = 'day_post_inf',
                                        title = 'All Exp Microbes by Vendor',
                                        x_name = 'Experiment',
                                        y_name = 'Relative Abundance (log10)')

## diet
miniDiet_genusAbun_plot <- abun_plots(input_table = mini_genusAbun_table,
                                      x_axis = 'exp_order',
                                      y_axis = 'rel_abund',
                                      x_axis_breaks = c(1, 2, 3),
                                      x_axis_labels = exp_x_labs,
                                      x_group_by = 'exp_order',
                                      fill_by = 'diet',
                                      brewer_palette = 'Spectral',
                                      legend_name = 'Mouse Diet',
                                      legend_labels = c('Chow',
                                                        'HFt / HFb',
                                                        'HFt / LFb',
                                                        'LFt / HFb',
                                                        'LFt / LFb'),
                                      facet_rows = 'Genus',
                                      facet_cols = 'day_post_inf',
                                      title = 'All Exp Microbes by Diet',
                                      x_name = 'Experiment',
                                      y_name = 'Relative Abundance (log10)')

miniVendor_genusAbun_plot
miniDiet_genusAbun_plot
```

**Saving my outputs**
```{r}
## baseline and day 3 microbiome 
## family level
ggsave('../baseline_day3/plots/vendor_famAbun_plot.pdf',
       plot = vendor_familyAbun_plot,
       width = 15, 
       height = 13)
ggsave('../baseline_day3/plots/diet_famAbun_plot.pdf',
       plot = diet_familyAbun_plot,
       width = 15, 
       height = 13)

## genus level 
ggsave('../baseline_day3/plots/vendor_genusAbun_plot.pdf',
       plot = vendor_genusAbun_plot,
       width = 15, 
       height = 13)
ggsave('../baseline_day3/plots/diet_genusAbun_plot.pdf',
       plot = diet_genusAbun_plot,
       width = 15, 
       height = 13)

## smaller version of genus level 
ggsave('../baseline_day3/plots/miniVendor_genusAbun_plot.pdf',
       plot = miniVendor_genusAbun_plot,
       width = 12.5, 
       height = 7)
ggsave('../baseline_day3/plots/miniDiet_genusAbun_plot.pdf',
       plot = miniDiet_genusAbun_plot,
       width = 12.5, 
       height = 7)

## as an .rdat object
save(miniVendor_genusAbun_plot,
     file = '../../figures/miniComparison_vendor_genusAbun_plot.rdat')
save(miniDiet_genusAbun_plot,
     file = '../../figures/miniComparison_diet_genusAbun_plot.rdat')
```

