---
title: "sample_matrix"
output: html_document
date: "2024-01-22"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
```
**Functions**
```{r}
process_data <- function(wanted_table,
                         wanted_col_name){
  wanted_table %>% 
    distinct(mouse_id, .keep_all = TRUE) %>% 
    mutate(binary = paste(1)) %>% 
    select(mouse_id, binary) -> proc_table
  
  names(proc_table)[names(proc_table) == 'binary'] <- wanted_col_name
  return(proc_table)
}
```

**File Paths**
```{r}
## study one is NOT filtered out
metadata_fp <- '../data/misc/d3_filt_comp_metadata.tsv'
bile_acid_fp <- '../../cecum/data/misc/processed_bile_acid.tsv'
toxin_fp <- '../../cecum/data/misc/processed_neatToxin.tsv'
metab_fp <- '../../cecum/data/misc/processed_metabolomics.tsv'
histo_fp <- '../../cecum/data/misc/processed_histopathology.tsv'
hypox_fp <- '../../cecum/data/misc/pimid_fluor.csv'

## labels
diet_labs <- c('Chow',
               'High Fat / High Fiber',
               'High Fat / Low Fiber',
               'Low Fat / High Fiber',
               'Low Fat / Low Fiber')
names(diet_labs) <- c('Chow',
                      'HF/HF',
                      'HF/LF',
                      'LF/HF',
                      'LF/LF')
```

**Reading in Files**
```{r}
metadata <- read_tsv(metadata_fp)
bile_acid <- read_tsv(bile_acid_fp)
toxin <- read_tsv(toxin_fp)
metab <- read_tsv(metab_fp)
histo <- read_tsv(histo_fp)
hypox <- read_csv(hypox_fp)
```

**Data Wrangling**
```{r}
## adding a 1 to the mouse ids for each table to be joined to overall metadata
proc_histo <- process_data(histo,
                           'histopathology')
proc_bile_acid <- process_data(bile_acid,
                               'bile_acid')
proc_toxin <- process_data(toxin,
                           'toxin')
proc_metab <- process_data(metab,
                           'metabolomics')
proc_hypox <- process_data(hypox,
                           'hypoxia')

## joining them to metadata for edge matrix visualization
metadata %>% 
  select(!c('#SampleID', 'day_post_inf')) %>% 
  left_join(proc_histo, by = 'mouse_id') %>% 
  left_join(proc_bile_acid, by = 'mouse_id') %>% 
  left_join(proc_metab, by = 'mouse_id') %>% 
  left_join(proc_toxin, by = 'mouse_id') %>% 
  left_join(proc_hypox, by = 'mouse_id') %>% 
  mutate(histopathology = ifelse(is.na(histopathology), 0, 1),
         bile_acid = ifelse(is.na(bile_acid), 0, 1),
         metabolomics = ifelse(is.na(metabolomics), 0, 1),
         toxin = ifelse(is.na(toxin), 0, 1),
         hypoxia = ifelse(is.na(hypoxia), 0, 1)) %>% 
  mutate(histopathology = ifelse(sample_type == 'colon', 0, histopathology),
         bile_acid = ifelse(sample_type == 'colon', 0, bile_acid),
         metabolomics = ifelse(sample_type == 'colon', 0, metabolomics),
         toxin = ifelse(sample_type == 'colon', 0, toxin),
         hypoxia = ifelse(sample_type == 'colon', 0, hypoxia),
         sequencing = paste(1)) %>% 
  gather(c('histopathology', 'bile_acid', 'metabolomics', 
           'toxin', 'hypoxia', 'sequencing'), 
         key = 'category_from', value = 'n_samples') %>% 
  mutate(mouse_id = as.factor(mouse_id),
         n_samples = as.factor(n_samples)) -> proc_metadata

proc_metadata %>% 
  ungroup() %>% 
  filter(n_samples == 1) %>% 
  count(sample_type, category_from, diet) -> plot_text
```

**Plot**
```{r, fig.height=5, fig.width=15}
proc_metadata %>% 
  ggplot(aes(x = sample_type, y = category_from)) +
  geom_tile(aes(fill = n_samples), color = 'black') +
  scale_fill_brewer(palette = 'Pastel1', limits = c(0.5, 1)) +
  scale_x_discrete(labels = c('Cecal\nSamples',
                              'Stool\nSamples')) +
  scale_y_discrete(labels = c('Bile Acids',
                              'Histopathology',
                              'Hypoxia',
                              'SCFAs',
                              '16S Sequencing',
                              'Toxin')) +
  facet_grid(~diet,
             labeller = labeller(diet = diet_labs)) +
  theme_bw(base_size = 20) +
  theme(legend.position = 'none',
        axis.title.x = element_blank(),
        axis.title.y = element_blank()) +
  ggtitle('Day 3 Cohort Sample Specifics') -> test_plot

test_plot
```
I don't think the stool sample numbers are correct...need to fix those. Actually, I think they are correct but I'm a little confused about if I'm showing them the right way. 
```{r, fig.height=4.5, fig.width=14}
test_plot +
  geom_text(data = plot_text,
            label = plot_text$n,
            color = 'black',
            size = 5) -> sample_spec_plot

sample_spec_plot
```

**Saving my Outputs**
```{r}
ggsave('../plots/sample_spec_table.pdf',
       plot = sample_spec_plot,
       width = 14,
       height = 4.5)
```

