## overall config file for first set of experiments stool sample dataset

dataset_dir: "comparisons/"
qiime_env: "qiime2-2023.5"

## options: yes and no
raw_sequences: "yes"

## 01: demux and dada2
raw_seq_dir: "data/first_set_qiime/"
raw_seqs: ["SEQ016/oldExp_s3-016", "SEQ021/oldExp_s4-021", "SEQ024/oldExp_s5-024"]
barcodes: ["SEQ016/oldExp_s3-016", "SEQ021/oldExp_s4-021", "SEQ024/oldExp_s5-024"] 
dada2_trim_left_for: 13
dada2_trim_left_rev: 13
dada2_trunc_len_for: 230
dada2_trunc_len_rev: 160

## 02/03: phylogeny and total sum scaling
r_script_dir: "scripts/"
biom_table: "data/qiime/merged_table.qza"
rep_seqs: "data/qiime/merged_rep_seqs.qza"

## 04: core metrics analysis
metadata: "data/misc/oldNew_comp_d15_metadata.tsv"
core_metrics_sampling_depth: 99631 ## might need a new sampling depth!

## 05: longitudinal dataset plots/stats in R (you NEED to have measurements at different time points)
## options: yes, no, or no downstream
longitudinal_dataset: "no downstream"
processed_metadata: "data/misc/oldNew_comp_d15_metadata.tsv"

## 06: non-longitudinal dataset plots/stats in R (measurements at only ONE time point)
sampleID_key: NA
mouseID_facil_key: NA
bile_acid: NA
toxin: NA
histo: NA
metab: NA
hypoxia: NA