## overall config file for first set of experiments stool sample dataset

dataset_dir: "new_experiments/"
qiime_env: "qiime2-2023.5"

## --GLOBAL OPTIONS--
## are you starting with raw 16S sequences?
raw_sequences: "yes" ## options: yes and no 

## do you want to run taxonomic classification? chances are yes since you're running this workflow
tax_class: "no" ## options: yes and no, default is yes 

## does your data need to go through total sum scaling? chances are that it doesn't
total_sum_scaling: "no" ## options: yes and no

## do you want to run core metrics analysis on your data to get alpha/beta diversity? you HAVE to run this if you want the microbiome R outputs
core_metrics: "no" ## options: yes and no

## would you like basic R plots/stats for your microbiome data? if so, this requires you to edit your R scripts directory for the exact visualizations you want
## (see more in the tutorial)
microbiome_r_outputs: "no" ## options: yes, no, or no downstream 
## -------------------

## --NEEDED FILE PATHS--
## include if raw_sequences = "yes"
raw_seq_dir: "data/SEQ096/"
raw_seqs: "new_stool" ## assumes that everything after this is "_paired_end_seqs.qza"
barcodes: "new_stool" ## assumes that everything after this is "_barcodes.txt"
dada2_trim_left_for: 13
dada2_trim_left_rev: 13
dada2_trunc_len_for: 230
dada2_trunc_len_rev: 160

## include if tax_class = "yes"
biom_table: NA
rep_seqs: NA
metadata: "data/SEQ096/new_stool_barcodes.txt"

## include if total_sum_scaling = "yes"
r_script_dir: NA

## include if core_metrics = "yes"
core_metrics_sampling_depth: NA ## might need a new sampling depth!

## include if microbiome_r_outputs = "yes"
## r script directory if you haven't already (r_script_dir: "scripts/")
processed_metadata: "data/SEQ096/new_stool_barcodes.txt"
## ---------------------

## madis cecal dataset plots/stats in R (measurements at only ONE time point) - you will NOT use this 
## include if running that analysis 
madis_cecal_analysis: "no"
sampleID_key: NA
mouseID_facil_key: NA
bile_acid: NA
toxin: NA
histo: NA
metab: NA
hypoxia: NA