## config file for arizona and new anschutz experiment stool sample comparisons

dataset_dir: "comparisons/"
qiime_env: "qiime2-2023.5"

## --GLOBAL OPTIONS--
## are you starting with raw 16S sequences?
raw_sequences: "no" ## options: yes and no 

## do you want to run taxonomic classification? chances are yes since you're running this workflow
tax_class: "no" ## options: yes and no, default is yes 

## does your data need to go through total sum scaling? chances are that it doesn't
total_sum_scaling: "no" ## options: yes and no

## do you want to run core metrics analysis on your data to get alpha/beta diversity? you HAVE to run this if you want the microbiome R outputs
core_metrics: "no" ## options: yes and no

## would you like basic R plots/stats for your microbiome data? if so, this requires you to edit your R scripts directory for the exact visualizations you want
## (see more in the tutorial)
microbiome_r_outputs: "yes" ## options: yes and no
## -------------------


## --NEEDED FILE PATHS--
## include if raw_sequences = "yes"
raw_seq_dir: NA
raw_seqs: NA ## assumes that everything after this is "_paired_end_seqs.qza"
barcodes: NA ## assumes that everything after this is "_barcodes.txt"
dada2_trim_left_for: NA
dada2_trim_left_rev: NA
dada2_trunc_len_for: NA
dada2_trunc_len_rev: NA

## include if tax_class = "yes"
biom_table: "data/qiime/allExp_comp_d15_table.qza"
rep_seqs: "data/qiime/allExp_comp_d15_seqs.qza"
metadata: "data/misc/oldNew_comp_d15_metadata.tsv"

## include if total_sum_scaling = "yes"
r_script_dir: "scripts/"

## include if core_metrics = "yes"
core_metrics_sampling_depth: 4437 ## might need a new sampling depth!

## include if microbiome_r_outputs = "yes"
## r script directory if you haven't already (r_script_dir: "scripts/")
processed_metadata: "data/misc/oldNew_comp_d15_metadata.tsv"
## ---------------------

## madis cecal dataset plots/stats in R (measurements at only ONE time point) - you will NOT use this 
## include if running that analysis 
madis_cecal_analysis: "no"
sampleID_key: NA
mouseID_facil_key: NA
bile_acid: NA
toxin: NA
histo: NA
metab: NA
hypoxia: NA
