---
title: "plasma_cytokine_conc_plot"
output: html_document
date: "2025-10-28"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(magrittr)
library(broom)
library(rstatix)
library(apppleplots)
```

**File paths**
```{r}
cytokine_fp <- '../data/misc/immune_cytokines_imputed.csv'

diet_x_labs <- c('HFt/\nHFb',
                      'HFt/\nLFb',
                      'LFt/\nHFb',
                      'LFt/\nLFb')
```

**Reading in file(s)**
```{r}
cytokine_df <- read_csv(cytokine_fp)
```

**Data wrangled**
CXCL1
```{r}
unwanted_cytokines <- c('IL-12p70', 
                        'IL-4', 
                        'IFN-y', 
                        'IL-2', 
                        'IL-5')

filt_cytokine_df <- cytokine_df %>% 
  filter(!(Measure %in% unwanted_cytokines)) %>% 
  mutate(log_value = log10(Value),
         MeasureLabel = ifelse(MeasureLabel == "KC-GRO (pg/mL)", "CXCL1 (pg/mL)", MeasureLabel))
```

**Stats**
comparing for differences in log10 transformed values between diets per cytokine
```{r}
cytokine_stats <- apppleplots::kruskal_dunn_stats(input_table = filt_cytokine_df,
                                                  grouped_by = c('MeasureLabel'),
                                                  adjust_method = 'BH',
                                                  filter_adj_p_value = FALSE,
                                                  formula_left = 'log_value',
                                                  formula_right = 'Diet')

cytokine_kruskal <- cytokine_stats$KruskalTest
cytokine_dunn <- cytokine_stats$DunnTest
```

**Plot**
```{r, fig.width=15, fig.height=8}
(cytokine_plot <- apppleplots::facet_once_plots(input_table = filt_cytokine_df,
                                                stat_on_plot = TRUE,
                                                x_value = 'Diet',
                                                y_value = 'Value',
                                                x_value_type = 'discrete',
                                                grouped_by = 'Diet',
                                                point_alpha = 0.4,
                                                x_labels = diet_x_labs,
                                                facet_by = 'MeasureLabel',
                                                facet_labels = NULL,
                                                stat_table = cytokine_dunn,
                                                x_name = 'Diet',
                                                y_name = 'Concentration (log10)',
                                                title_content = 'Plasma Immune/Sepsis Marker Concentration') +
                    scale_y_continuous(trans = 'log10') +
                    facet_wrap(~MeasureLabel,
                               scales = "free_y",
                               nrow = 2) +
                    theme_bw(base_size = 20))
```

**Saving my outputs**
```{r}
ggsave('../plots/immune_cytokine_plot.pdf',
       plot = cytokine_plot,
       width = 15,
       height = 8)
save(cytokine_plot,
     file = '../../figures/immune_cytokine_plot.RData')
```

