---
title: "alpha_div_plots"
output: html_document
date: "2023-11-07"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggpubr)
library(ggplot2)
library(magrittr)
library(qiime2R)
library(tidyverse)
library(broom)
library(cowplot)
library(viridis)
library(argparse)
library(apppleplots)
```

**Functions**
```{r}
prep_my_files <- function(metadata_fp,
                          faith_fp,
                          shannon_fp){
  ## metadata
  meta <- read_tsv(metadata_fp) %>% 
            mutate(study = as.factor(study))
  ## faith
  faith <- read_tsv(faith_fp) %>% 
              rename('sampleid' = '#SampleID')
  ## shannon
  shannon <- read_tsv(shannon_fp) %>% 
                rename('sampleid' = '...1')
  ## putting tables together
  faith <- faith %>% 
              left_join(meta, by = 'sampleid') %>% 
              mutate(plot_label = paste('Alpha Diversity at Day 3'))
  shannon <- shannon %>% 
                left_join(meta, by = 'sampleid') %>% 
                mutate(plot_label = paste('Alpha Diversity at Day 3'))
  ## creating list of outputs 
  my_list <- list(Faith = faith,
                  Shannon = shannon)
  return(my_list)
}
```

**File Paths**
```{r}
metadata_FP <- '../data/misc/filt_cecal_processed_metadata.tsv'
faith_pd_FP <- '../data/core_outputs/faith_pd.tsv'
shannon_FP <- '../data/core_outputs/shannon_entropy.tsv'

diet_x_labs <- c('Chow',
                 'HFt/\nHFb',
                 'HFt/\nLFb',
                 'LFt/\nHFb',
                 'LFt/\nLFb')
```

**Metadata File**
```{r}
alpha_files <- prep_my_files(metadata_FP,
                             faith_pd_FP,
                             shannon_FP)
faith <- alpha_files$Faith
shannon <- alpha_files$Shannon
```

**Faith's PD**
```{r, fig.height=6, fig.width=9}
faith_title <- "Cecal Sample Faith's Phylogenetic Diversity"

faith_plot <- apppleplots::facet_once_plots(input_table = faith,
                                            stat_on_plot = FALSE,
                                            x_value = 'diet',
                                            y_value = 'faith_pd',
                                            x_value_type = 'discrete',
                                            grouped_by = 'diet',
                                            point_alpha = 0.4,
                                            x_labels = diet_x_labs,
                                            facet_by = 'plot_label',
                                            facet_labels = NULL,
                                            stat_table = NULL,
                                            x_name = "Diet",
                                            y_name = "Faith's PD",
                                            title_content = faith_title)

faith_plot <- faith_plot +
                theme_bw(base_size = 20)
faith_plot
```

**Shannon Entropy**
```{r, fig.height=6, fig.width=9}
shannon_title <- "Cecal Sample Shannon Entropy"

shannon_entropy_plot <- apppleplots::facet_once_plots(input_table = shannon,
                                                      stat_on_plot = FALSE,
                                                      x_value = 'diet',
                                                      y_value = 'shannon_entropy',
                                                      x_value_type = 'discrete',
                                                      grouped_by = 'diet',
                                                      point_alpha = 0.4,
                                                      x_labels = diet_x_labs,
                                                      facet_by = 'plot_label',
                                                      facet_labels = NULL,
                                                      stat_table = NULL,
                                                      x_name = "Diet",
                                                      y_name = "Shannon Entropy",
                                                      title_content = shannon_title)
shannon_entropy_plot <- shannon_entropy_plot +
                          theme_bw(base_size = 20)
shannon_entropy_plot
```

**Saving my Outputs**
```{r}
ggsave('../plots/faith_pd.pdf',
       plot = faith_plot, 
       width = 9, 
       height = 6)

ggsave('../plots/shannon_entropy.pdf',
       plot = shannon_entropy_plot, 
       width = 9, 
       height = 6)
```

