---
title: "beta_div_stats"
output: html_document
date: "2023-11-09"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggpubr)
library(ggplot2)
library(magrittr)
library(qiime2R)
library(tidyverse)
library(broom)
library(cowplot)
library(rstatix)
library(ape)
library(vegan)
library(ggh4x)
library(viridis)
library(argparse)
```

**Functions**
```{r}
##1 
## for distance matrix processing
## for beta diversity statistical analysis 
dist_matrix_prep <- function(metadata_file,
                             dist_matrix_fp){
  ## metadata
  metadata <- metadata_file
  ## distance matrix
  dist <- read_tsv(dist_matrix_fp)
  names(dist)[names(dist) == '...1'] <- 'sampleid'
  dist %>% 
    gather(-sampleid, key = sample_col, value = dist) %>% 
    filter(sampleid %in% metadata$sampleid) %>% 
    filter(sample_col %in% metadata$sampleid) %>% 
    spread(sample_col, dist) -> dist_long
  dist_long %>% 
    select(-sampleid) -> dist_proc
  metadata %>% 
    arrange(sampleid) -> metadata
  metadata %>% 
    filter(sampleid %in% dist_long$sampleid) -> filt_meta
  dist_proc <- as.matrix(dist_proc)
  row.names(dist_proc) <- colnames(dist_proc)
  filt_meta <- filt_meta[order(filt_meta$sampleid),]
  ## list of outputs
  my_list <- list(Metadata = filt_meta,
                  DistanceMatrix = dist_proc)
  return(my_list)
}


## 2
## beta diversity adonis2 testing function
adonis_test <- function(dist_matrix,
                        metadata_file){
  adonis_results <- adonis2(as.dist(dist_matrix) ~ (purified_diet * high_fat * high_fiber) + study,
                            data = metadata_file,
                            permutations = 999, 
                            parallel = 4)
  adonis_results <- tidy(adonis_results)
  adonis_results['signif'] <- symnum(adonis_results$p.value,
                                     cutpoints = c(0, 0.0001, 0.001, 0.01, 0.05, 0.1, 1),
                                     symbols = c("****", "***", "**", "*", "+", "ns"),
                                     abbr.colnames = FALSE,
                                     na = "")
  return(adonis_results)
}
```

**File Paths**
```{r}
metadata_FP <- '../data/misc/filt_cecal_processed_metadata.tsv'
uu_dist_fp <- '../data/core_outputs/uw_dist_matrix.tsv'
wu_dist_fp <- '../data/core_outputs/w_dist_matrix.tsv'
```

**Metadata File**
```{r}
meta <- read_tsv(metadata_FP)
```

**Weighted UniFrac**
```{r}
w_dist_files <- dist_matrix_prep(meta,
                                 wu_dist_fp)

w_dist <- w_dist_files$DistanceMatrix
stat_meta <- w_dist_files$Metadata

w_adonis <- adonis_test(w_dist,
                        stat_meta)
```

**Unweighted UniFrac**
```{r}
uw_dist_files <- dist_matrix_prep(meta,
                                  uu_dist_fp)

uw_dist <- uw_dist_files$DistanceMatrix
stat_meta <- uw_dist_files$Metadata

uw_adonis <- adonis_test(uw_dist,
                         stat_meta)
```

**Saving my Outputs**
```{r}
## writing results out as a .tsv file 
write_tsv(w_adonis, 
          "../stats/w_adonis_results.tsv")
write_tsv(uw_adonis, 
          "../stats/uw_adonis_results.tsv")
```

