---
title: "family_abun_plots"
output: html_document
date: "2023-11-07"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggpubr)
library(ggplot2)
library(magrittr)
library(qiime2R)
library(tidyverse)
library(broom)
library(cowplot)
library(vegan)
library(viridis)
library(argparse)
library(apppleplots)
```

**Functions**
```{r}
## 1
family_abun_file_prep <- function(metadata_fp,
                                  tax_fp,
                                  otu_table_fp,
                                  tax_level,
                                  wanted_tax){
  ## metadata
  metadata <- read_tsv(metadata_fp)
  ## taxonomy
  taxonomy <- read_qza(tax_fp)$data %>% 
    parse_taxonomy() %>% 
    rownames_to_column('asv')
  ## otu table 
  otu_table <- read_qza(otu_table_fp)$data
  otu_table %>% 
    as_tibble(rownames = 'asv') %>% 
    gather(-asv, key = sampleid, value = abun) %>% 
    group_by(sampleid) %>% 
    mutate(rel_abun = abun/sum(abun)) %>% 
    mutate(rel_abun = rel_abun + 0.000001) -> otu_table
  ## joining all tables together 
  otu_table %>% 
    left_join(metadata, by = 'sampleid') %>% 
    left_join(taxonomy, by = 'asv') -> abun_table
  abun_table %>% 
    group_by(sampleid, day_post_inf, diet, mouse_id, 
             purified_diet, high_fat, high_fiber, 
             seq_depth, .data[[tax_level]], facility, study) %>% 
    summarise(rel_abund = sum(rel_abun)) %>% 
    filter(.data[[tax_level]] %in% wanted_tax) %>% 
    mutate(mouse_fact = as.factor(mouse_id),
           day_fact = as.factor(day_post_inf)) -> abun_filt
  ## creating a list for my outputs
  my_list <- list(Metadata = metadata,
                  Taxonomy = taxonomy,
                  OTUTable = otu_table,
                  AbundanceTable = abun_filt)
  return(my_list)
}
```

**File Paths**
```{r}
otu_table_FP <- '../data/cecal_qiime/tax_filt_actual.qza'
tax_FP <- '../data/cecal_qiime/taxonomy.qza'
metadata_FP <- '../data/misc/filt_cecal_processed_metadata.tsv'

diet_labs <- 
  c('Chow', 
    'High Fat / High Fiber', 
    'High Fat / Low Fiber', 
    'Low Fat / High Fiber', 
    'Low Fat / Low Fiber')
names(diet_labs) <- c('Chow', 
                      'HF/HF', 
                      'HF/LF', 
                      'LF/HF', 
                      'LF/LF')
wanted_level <- 'Family'
wanted_family <- c('Enterobacteriaceae', 
                   'Lactobacillaceae', 
                   'Lachnospiraceae', 
                   'Enterococcaceae',
                   'Staphylococcaceae', 
                   'Tannerellaceae', 
                   'Muribaculaceae', 
                   'Bacteroidaceae', 
                   'Marinifilaceae', 
                   'Ruminococcaceae')
diet_x_labs <- c("Chow",
                 "HFt/\nHFb",
                 "HFt/\nLFb",
                 "LFt/\nHFb",
                 "LFt/\nLFb")
```

**Data Wrangling for Plot**
```{r}
abun_files <- family_abun_file_prep(metadata_FP,
                                    tax_FP,
                                    otu_table_FP,
                                    wanted_level,
                                    wanted_family)

## pulling the abundance table out, you can also take metadata, otu table, and taxonomic info
## out of the list output 
abun_filt <- abun_files$AbundanceTable
```

**Plots**
```{r, fig.height=17, fig.width=11}
## scatter plot by wanted microbe families and diet at day 3 in the cecum 
abun1 <- apppleplots::facet_once_plots(input_table = abun_filt,
                                       stat_on_plot = FALSE,
                                       x_value = 'Family',
                                       y_value = 'rel_abund',
                                       x_value_type = NULL,
                                       grouped_by = 'Family',
                                       point_alpha = 0.4,
                                       x_labels = NULL,
                                       facet_by = 'diet',
                                       facet_labels = diet_labs,
                                       stat_table = NULL,
                                       x_name = 'Family',
                                       y_name = 'Relative Abundance',
                                       title_content = "Cecal Microbe Family Relative Abundance at Day 3")

abun1 <- abun1 +
          theme_bw(base_size = 16) +
          theme(strip.text.y = element_text(angle = 0),
                axis.text.x = element_text(angle = 45, hjust = 1)) +
          scale_y_continuous(trans = 'log10')

## scatter plot faceted by wanted microbe families with diet on the x-axis for visual comparisons by diet
abun2 <- apppleplots::facet_once_plots(input_table = abun_filt,
                                       stat_on_plot = FALSE,
                                       x_value = 'diet',
                                       y_value = 'rel_abund',
                                       x_value_type = 'discrete',
                                       grouped_by = 'diet',
                                       point_alpha = 0.4,
                                       x_labels = diet_x_labs,
                                       facet_by = 'Family',
                                       facet_labels = NULL,
                                       stat_table = NULL,
                                       x_name = 'Diet',
                                       y_name = 'Relative Abundance',
                                       title_content = "Cecal Microbe Family Relative Abundance at Day 3")

abun2 <- abun2 +
          facet_wrap(~Family,
                     ncol = 1,
                     strip.position = 'right') +
          theme_bw(base_size = 16) +
          theme(strip.text.y.right = element_text(angle = 0)) +
          scale_y_continuous(trans = 'log10')


abun1
abun2
```


**Saving my Outputs**
```{r}
## option #1
ggsave('../plots/family_abun1.pdf',
       plot = abun1, 
       width = 18, 
       height = 7)
## option #2
ggsave('../plots/family_abun2.pdf',
       plot = abun2, 
       width = 12, 
       height = 17)
```

