---
title: "family_abun_stats"
output: html_document
date: "2023-11-09"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggpubr)
library(ggplot2)
library(magrittr)
library(qiime2R)
library(tidyverse)
library(broom)
library(cowplot)
library(vegan)
library(viridis)
library(rstatix)
library(argparse)
library(apppleplots)
```

**Functions**
```{r}
## function 1
family_abun_file_prep <- function(metadata_fp,
                                  tax_fp,
                                  otu_table_fp,
                                  tax_level,
                                  wanted_tax){
  ## metadata
  metadata <- read_tsv(metadata_fp)
  ## taxonomy
  taxonomy <- read_qza(tax_fp)$data %>% 
    parse_taxonomy() %>% 
    rownames_to_column('asv')
  ## otu table 
  otu_table <- read_qza(otu_table_fp)$data
  otu_table %>% 
    as_tibble(rownames = 'asv') %>% 
    gather(-asv, key = sampleid, value = abun) %>% 
    group_by(sampleid) %>% 
    mutate(rel_abun = abun/sum(abun)) %>% 
    mutate(rel_abun = rel_abun + 0.000001) -> otu_table
  ## joining all tables together 
  otu_table %>% 
    left_join(metadata, by = 'sampleid') %>% 
    left_join(taxonomy, by = 'asv') -> abun_table
  abun_table %>% 
    group_by(sampleid, day_post_inf, diet, mouse_id, 
             purified_diet, high_fat, high_fiber, 
             seq_depth, .data[[tax_level]]) %>% 
    summarise(rel_abund = sum(rel_abun)) %>% 
    filter(.data[[tax_level]] %in% wanted_tax) %>% 
    mutate(mouse_fact = as.factor(mouse_id),
           day_fact = as.factor(day_post_inf)) -> abun_filt
  ## creating a list for my outputs
  my_list <- list(Metadata = metadata,
                  Taxonomy = taxonomy,
                  OTUTable = otu_table,
                  AbundanceTable = abun_filt)
  return(my_list)
}

## 2 
## runs statistics on the large assembled data table for stat visualization
abun_stats <- function(filtered_table,
                       first_group,
                       second_group,
                       mean_value,
                       dunn_test){
  ## editing my dunn's post hoc test to include the difference in means between groups 
  filtered_table %>% 
    group_by(.data[[first_group]], .data[[second_group]]) %>% 
    summarise(mean = mean(.data[[mean_value]])) -> mean_table
  
  dunn_test %>% 
    merge(mean_table, 
          by.x = c('group1',
                   second_group),
          by.y = c(first_group,
                   second_group)) %>% 
    rename_with(~paste0('group1_', mean_value, recycle0 = TRUE), contains('mean')) %>% 
    merge(mean_table,
          by.x = c('group2',
                   second_group),
          by.y = c(first_group,
                   second_group)) %>% 
    rename_with(~paste0('group2_', mean_value, recycle0 = TRUE), contains('mean')) -> int_dunn
  
  group1_col <- paste0('group1_', mean_value)
  group2_col <- paste0('group2_', mean_value)
  
  int_dunn %>% 
    mutate(diff_means = (.data[[group1_col]] - .data[[group2_col]]),
           stat_diff_means = if_else(p.adj > 0.05, 0, diff_means)) -> new_dunn
  
  return(new_dunn)
}
```

**File Paths**
```{r}
otu_table_FP <- '../data/cecal_qiime/tax_filt_actual.qza'
tax_FP <- '../data/cecal_qiime/taxonomy.qza'
metadata_FP <- '../data/misc/filt_cecal_processed_metadata.tsv'
wanted_level <- 'Family'
wanted_family <- c('Enterobacteriaceae', 
                   'Lactobacillaceae', 
                   'Lachnospiraceae', 
                   'Enterococcaceae',
                   'Staphylococcaceae', 
                   'Tannerellaceae', 
                   'Muribaculaceae', 
                   'Bacteroidaceae', 
                   'Marinifilaceae', 
                   'Ruminococcaceae')
diet_x_labs <- c('Chow',
                 'HFt/\nHFb',
                 'HFt/\nLFb',
                 'LFt/\nHFb')
diet_y_labs <- c('HFt / HFb',
                 'HFt / LFb',
                 'LFt / HFb',
                 'LFt / LFb')
```

**Data Wrangling**
```{r}
abun_files <- family_abun_file_prep(metadata_FP,
                                    tax_FP,
                                    otu_table_FP,
                                    wanted_level,
                                    wanted_family)

## can still pull out the metadata, taxonomy, and otu table as well
abun_filt <- abun_files$AbundanceTable
```
**Family Abundance Stat Vis**
```{r, fig.width=12, fig.height=13}
## kruskal wallis and dunns post hoc test 
abun_krDunn <- kruskal_dunn_stats(input_table = abun_filt,
                                  grouped_by = wanted_level,
                                  adjust_method = 'BH',
                                  filter_adj_p_value = TRUE,
                                  formula_left = 'rel_abund',
                                  formula_right = 'diet')

kruskal_test <- abun_krDunn$KruskalTest
dunn_test <- abun_krDunn$DunnTest

new_dunn_test <- abun_stats(filtered_table = abun_filt,
                            first_group = 'diet',
                            second_group = wanted_level,
                            mean_value = 'rel_abund',
                            dunn_test = dunn_test)

## linear model
family_abun_lm <- linear_model(input_table = abun_filt,
                               grouped_by = wanted_level,
                               adjust_method = 'BH',
                               filter_adj_p_value = TRUE,
                               formula_left = 'rel_abund',
                               formula_right = '(purified_diet * seq_depth) + high_fat * high_fiber')


## putting together the statistical visualization based on dunns post hoc test
abun_stat_vis <- apppleplots::stat_heat_plot(input_table = new_dunn_test,
                                             x_value = 'group1',
                                             y_value = 'group2',
                                             x_value_type = 'discrete',
                                             y_value_type = 'discrete',
                                             pairwise = FALSE,
                                             correlation = FALSE,
                                             tile_fill = 'stat_diff_means',
                                             tile_outline_color = 'black',
                                             tile_alpha = 0.6,
                                             text_value = 'p.adj.signif',
                                             low_color = 'blue',
                                             high_color = 'green',
                                             legend_name = 'Group 1 -\nGroup 2',
                                             x_labels = diet_x_labs,
                                             y_labels = diet_y_labs,
                                             facet_by = wanted_level,
                                             facet_labels = NULL,
                                             x_name = 'Group 1',
                                             y_name = 'Group 2', 
                                             title_content = NULL)

abun_stat_vis <- abun_stat_vis +
                  facet_wrap(~Family,
                             ncol = 1,
                             strip.position = 'right') +
                  theme(strip.text.y.right = element_text(angle = 0))

abun_stat_vis
```

**Saving my Outputs**
```{r}
## saving my outputs as a .tsv
write_tsv(family_abun_lm,
          "../stats/family_abun_lm.tsv")
write_tsv(new_dunn_test,
          "../stats/family_abun_dunn.tsv")

## saving statistical visualization
ggsave("../plots/famAbun_stat_vis.pdf",
       plot = abun_stat_vis, 
       width = 12, 
       height = 13)
```

