---
title: "histopathology"
output: html_document
date: "2023-11-09"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggplot2)
library(magrittr)
library(qiime2R)
library(tidyverse)
library(broom)
library(cowplot)
library(rstatix)
library(ggpubr)
library(argparse)
```

**Functions**
```{r}
## 1
histo_file_prep <- function(metadata_fp,
                            histo_fp){
  ## reading in metadata file
  metadata <- read_tsv(metadata_fp)
  ## reading in histo file
  histo <- read_csv(histo_fp) %>% 
    filter(!is.na(mouse_id))
  ## joining them all together for ggplot rendering 
  metadata %>% 
    merge(histo, by = 'mouse_id') %>% 
    gather(cecum, colon, key = tissue, value = score) %>% 
    select(!c(tube_num, date, corr_sample_num)) -> big_histo
  return(big_histo)
}

## 2
## statistical analysis
histo_stats <- function(big_histo){
  ## kruskal-wallis test
  big_histo %>% 
    group_by(tissue) %>% 
    do(tidy(kruskal.test(score ~ diet,
                         data = .))) %>% 
    ungroup() %>%
    arrange(p.value) %>%
    mutate(p.adj = p.adjust(p.value,
                            method = "BH"),
           test_id = paste(tissue)) %>% 
    filter(p.adj <= 0.05) -> kruskal
  ## dunn's post hoc test
  big_histo %>% 
    group_by(tissue) %>% 
    mutate(test_id = paste(tissue)) %>% 
    filter(test_id %in% kruskal$test_id) %>% 
    dunn_test(score ~ diet,
              p.adjust.method = 'BH',
              data =.) %>% 
    add_y_position(scales = 'free_y', step.increase = 0) -> dunn
  ## linear model
  big_histo %>% 
    group_by(tissue) %>% 
    do(glance(lm(score ~ (purified_diet * seq_depth) + high_fat * high_fiber,
                 data =.))) %>% 
    ungroup() %>%
    na.omit() %>%
    mutate(adj.p = p.adjust(p.value,
                            method = "BH"),
           test_id = paste(tissue)) %>% 
    filter(adj.p <= 0.05) -> lm_full
  
  big_histo %>% 
    group_by(tissue) %>% 
    mutate(test_id = paste(tissue)) %>% 
    filter(test_id %in% lm_full$test_id) %>% 
    do(tidy(lm(score ~ (purified_diet * seq_depth) + high_fat * high_fiber,
               data =.))) %>%
    filter(term != '(Intercept)') %>% 
    na.omit() -> linear_model
  
  linear_model['signif'] <- symnum(linear_model$p.value,
                                   cutpoints = c(0, 0.0001, 0.001, 0.01, 0.05, 0.1, 1),
                                   symbols = c("****", "***", "**", "*", "+", "ns"),
                                   abbr.colnames = FALSE,
                                   na = "")
  ## creating a list of my outputs
  my_list <- list(KruskalWallis = kruskal,
                  DunnsPostHoc = dunn,
                  LinearModel = linear_model)
  return(my_list)
}

## 3
histo_plot <- function(big_histo,
                       histo_dunn){
  big_histo %>% 
    mutate(day_post_inf = as.numeric(day_post_inf)) %>% 
    ggplot(aes(x = diet, y = score)) +
    geom_violin(aes(group = diet),  draw_quantiles = c(0.5)) +
    geom_jitter(alpha = 0.4, width = 0.1, height = 0) +
    scale_x_discrete(labels = c('Chow', 
                                'HFt/\nHFb', 
                                'HFt/\nLFb',
                                'LFt/\nHFb', 
                                'LFt/\nLFb')) +
    facet_wrap(~tissue, labeller = labeller(tissue = tissue_labs),
               scales = "free_y") +
    stat_pvalue_manual(histo_dunn,
                       tip.length = 0.01,
                       label = 'p.adj.signif',
                       hide.ns = TRUE,
                       step.increase = 0.1) +
    theme_bw(base_size = 20) +
    xlab('Diet') +
    ylab('Histopathology Score') +
    ggtitle("Cecal Sample Histopathology Score by Diet") -> all_day_plot
  return(all_day_plot)
}
```

**File Paths**
```{r}
metadata_FP <- '../data/misc/filt_cecal_processed_metadata.tsv'
histo_FP <- '../data/misc/histo_data.csv'
tissue_labs <- c('Cecum',
                 'Colon')
names(tissue_labs) <- c('cecum',
                        'colon')
```

**Histopathology Calculations**
```{r, fig.height=6, fig.width=12}
## file prep 
histo <- histo_file_prep(metadata_FP,
                         histo_FP)

## stats 
stats <- histo_stats(big_histo = histo)

kruskal <- stats$KruskalWallis
dunn <- stats$DunnsPostHoc
linear_model <- stats$LinearModel

## plot 
all_day_plot <- histo_plot(histo,
                           dunn)

all_day_plot
```

**Saving my Outputs**
```{r}
ggsave("../plots/histopathology.pdf", 
       plot = all_day_plot,
       width = 12, 
       height = 6)

write_tsv(linear_model,
          "../stats/histopathology_lm.tsv")
write_tsv(dunn,
          "../stats/histopathology_dunn.tsv")

save(all_day_plot,
     file = '../../figures/histo.rdata')
```

