---
title: "hypoxia"
output: html_document
date: "2023-11-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(cowplot)
library(broom)
library(rstatix)
library(ggpubr)
library(glue)
```

**Functions**
```{r}
## this function runs a kruskal test followed by a dunns post hoc test on the data
hypoxia_stats <- function(hypoxia_table,
                          grouped_by,
                          formula_left,
                          formula_right){
  ## kruskal test
  hypoxia_table %>% 
    group_by(hypoxia_table[grouped_by]) %>% 
    do(tidy(kruskal.test(.data[[formula_left]] ~ .data[[formula_right]],
               data = .))) %>% 
    ungroup() %>% 
    arrange(p.value) %>% 
    mutate(p.adj = p.adjust(p.value,
                            method = "BH")) -> kruskal
  ## dunns post hoc test
  rightSide_name <- formula_right
  funky_formula <- reformulate(glue("{rightSide_name}"),glue("{formula_left}"))
  
  hypoxia_table %>% 
    group_by(hypoxia_table[grouped_by]) %>% 
    dunn_test(funky_formula,
              p.adjust.method = 'BH',
              data = .) %>% 
    add_y_position(scales = 'free',
                   fun = 'max') -> dunn
  ## list of outputs
  my_list <- list(KruskalTest = kruskal,
                  DunnTest = dunn)
  return(my_list)
}

## this function plots the data/stats
hypoxia_plots <- function(hypoxia_table,
                          x_value,
                          y_value,
                          grouped_by,
                          x_labels,
                          facet_by,
                          facet_labels,
                          dunn_table,
                          x_name,
                          y_name,
                          title_content){
  hypoxia_table %>% 
    ggplot(aes(x = .data[[x_value]], y = .data[[y_value]])) +
    geom_boxplot(aes(group = .data[[grouped_by]])) +
    geom_jitter(alpha = 0.4, width = 0.1, height = 0) +
    scale_x_discrete(labels = x_labels) +
    theme_bw(base_size = 16) +
    facet_grid(~.data[[facet_by]],
               labeller = labeller(.cols = facet_labels)) +
    stat_pvalue_manual(dunn_table,
                       tip.length = 0.01,
                       label = 'p.adj.signif',
                       hide.ns = TRUE) +
    labs(x = x_name,
         y = y_name,
         title = title_content) -> plot
  return(plot)
}
```

**File Path**
```{r}
hypoxia_fp <- '../data/misc/pimid_fluor.csv'

diet_labs <- c('Chow',
               'High Fat / High Fiber',
               'High Fat / Low Fiber',
               'Low Fat / High Fiber',
               'Low Fat / Low Fiber')
names(diet_labs) <- c('Chow',
                      'HF/HF',
                      'HF/LF',
                      'LF/HF',
                      'LF/LF')

fiber_labs <- c('High Fiber',
                'Low Fiber')
names(fiber_labs) <- c('high_fiber',
                       'low_fiber')

location_labs <- c('Cecum',
                   'Proximal Colon',
                   'Distal Colon')
names(location_labs) <- c(1,
                          2,
                          3)
location_x_labs <- c('Cecum',
                     'Proximal\nColon',
                     'Distal\nColon')
diet_x_labs <- c('Chow',
                 'HFt/\nHFb',
                 'HFt/\nLFb',
                 'LFt/\nHFb',
                 'LFt/\nLFb')

fiber_x_labs <- c('High\nFiber',
                   'Low\nFiber')
```

**Reading in Table**
```{r}
hypoxia <- read_csv(hypoxia_fp)

hypoxia %>% 
  mutate(order = ifelse(location == 'Cecum', 1, location),
         order = ifelse(order == 'Prox_colon', 2, order),
         order = ifelse(order == 'Dist_colon', 3, order)) %>% 
  arrange(order) -> hypoxia
```

# **Statistical Analysis**
```{r}
## between locations by diet
dietLocation_stats <- hypoxia_stats(hypoxia,
                                    'diet',
                                    'fluorescence',
                                    'order')

dietLocation_kruskal <- dietLocation_stats$KruskalTest
dietLocation_dunn <- dietLocation_stats$DunnTest

## between locations by fiber content (high v low)
fiberLocation_stats <- hypoxia_stats(hypoxia,
                                    'fiber',
                                    'fluorescence',
                                    'order')

fiberLocation_kruskal <- fiberLocation_stats$KruskalTest
fiberLocation_dunn <- fiberLocation_stats$DunnTest

## between diets by location (so the opposite of the first one above)
locationDiet_stats <- hypoxia_stats(hypoxia,
                                    'order',
                                    'fluorescence',
                                    'diet')

locationDiet_kruskal <- locationDiet_stats$KruskalTest
locationDiet_dunn <- locationDiet_stats$DunnTest

## between level of fiber content by location (so the opposite of the second one above)
locationFiber_stats <- hypoxia_stats(hypoxia,
                                    'order',
                                    'fluorescence',
                                    'fiber')

locationFiber_kruskal <- locationFiber_stats$KruskalTest
locationFiber_dunn <- locationFiber_stats$DunnTest
```


# **Plots**
```{r}
## location is on the x-axis and faceted by diet
hypoxia_dietLocation_plot <- hypoxia_plots(hypoxia,
                                        'order',
                                        'fluorescence',
                                        'order',
                                        location_x_labs,
                                        'diet',
                                        diet_labs,
                                        dietLocation_dunn,
                                        'Location',
                                        'Fluorescence',
                                        'Intestinal Hypoxia')

## location on x-axis and faceted by fiber content 
hypoxia_fiberLocation_plot <- hypoxia_plots(hypoxia,
                                        'order',
                                        'fluorescence',
                                        'order',
                                        location_x_labs,
                                        'fiber',
                                        fiber_labs,
                                        fiberLocation_dunn,
                                        'Location',
                                        'Fluorescence',
                                        'Intestinal Hypoxia by Dietary Fiber')

## diet on x-axis and faceted by location
hypoxia_locationDiet_plot <- hypoxia_plots(hypoxia,
                                        'diet',
                                        'fluorescence',
                                        'diet',
                                        diet_x_labs,
                                        'order',
                                        location_labs,
                                        locationDiet_dunn,
                                        'Diet',
                                        'Fluorescence',
                                        'Intestinal Hypoxia')

## diet on x-axis and faceted by location CECUM ONLY
hypoxia %>% 
  filter(order == 1) -> hypoxia_cecumOnly

hypoxia_cecum_plot <- hypoxia_plots(hypoxia_cecumOnly,
                                    'diet',
                                    'fluorescence',
                                    'diet',
                                    diet_x_labs,
                                    'order',
                                    location_labs,
                                    locationDiet_dunn,
                                    'Diet',
                                    'Fluorescence',
                                    'Cecum Hypoxia')

## fiber content on x-axis and faceted by location
hypoxia_locationFiber_plot <- hypoxia_plots(hypoxia,
                                            'fiber',
                                            'fluorescence',
                                            'fiber',
                                            fiber_x_labs,
                                            'order',
                                            location_labs,
                                            locationFiber_dunn,
                                            'Fiber Content',
                                            'Fluorescence',
                                            'Intestinal Hypoxia by Dietary Fiber')
```

```{r, fig.height=5, fig.width=15}
hypoxia_dietLocation_plot
```

```{r, fig.height=4, fig.width=8}
hypoxia_fiberLocation_plot
```
```{r, fig.height=5, fig.width=10}
hypoxia_locationDiet_plot
```
```{r, fig.height=4, fig.width=6}
hypoxia_cecum_plot
```

```{r, fig.height=4.5, fig.width=8}
hypoxia_locationFiber_plot
```

# **Saving my Outputs**
```{r}
## as a pdf
ggsave('../plots/hypoxia_diet_facetLocation.pdf',
       plot = hypoxia_locationDiet_plot,
       width = 10, 
       height = 5)
ggsave('../plots/hypoxia_diet_cecumONLY.pdf',
       plot = hypoxia_cecum_plot,
       width = 6, 
       height = 4)
ggsave('../plots/hypoxia_fiber_facetLocation.pdf',
       plot = hypoxia_locationFiber_plot,
       width = 8, 
       height = 4.5)
ggsave('../plots/hypoxia_location_facetDiet.pdf',
       plot = hypoxia_dietLocation_plot,
       width = 15, 
       height = 5)

## as an rdata object
save(hypoxia_locationDiet_plot,
     file = '../../figures/hypoxia_diet_facetLocation.rdata')
save(hypoxia_locationFiber_plot,
     file = '../../figures/hypoxia_fiber_facetLocation.rdata')
save(hypoxia_dietLocation_plot,
     file = '../../figures/hypoxia_location_facetDiet.rdata')
save(hypoxia_cecum_plot,
     file = '../../figures/hypoxia_cecumONLY.rdata')

## stats
write_tsv(dietLocation_dunn,
          '../stats/hypoxia_dietLocation_dunn.tsv')
write_tsv(fiberLocation_dunn,
          '../stats/hypoxia_fiberLocation_dunn.tsv')
```

