---
title: "metab_toxin_comp"
output: html_document
date: "2023-09-19"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(broom)
library(cowplot)
library(magrittr)
library(qiime2R)
library(tidyverse)
library(naniar)
library(ggpubr)
library(rstatix)
library(viridis)
library(apppleplots)
```

**Functions**
```{r}
## runs linear modeling on the table, diet, location, and toxin/metabolite wanted and returns full results
## along with a table containing the r2 and p-value 
## this goes into the following function with a for loop 
r2_value <- function(biom_table,
                     wanted_diet,
                     wanted_metab,
                     tox_col,
                     wanted_tox,
                     wanted_conc_value){
  ## to get r squared value and p value
  biom_table %>% 
    filter(diet == wanted_diet,
           metabolite == wanted_metab,
           .data[[tox_col]] == wanted_tox) %>% 
    do(glance(lm(metab_conc_norm ~ .data[[wanted_conc_value]],
                 data = .))) -> lm_glance
  output <- list(r_squared = lm_glance$r.squared,
                 p_value = lm_glance$p.value)
  ## to get estimate and place it with the overall output table
  biom_table %>% 
    filter(diet == wanted_diet,
           metabolite == wanted_metab,
           .data[[tox_col]] == wanted_tox) %>% 
    do(tidy(lm(metab_conc_norm ~ .data[[wanted_conc_value]],
                 data = .))) %>% 
    filter(term != '(Intercept)') -> lm_full
  output <- as_tibble(output) %>%
            mutate(diet = paste(wanted_diet),
                   metabolite = paste(wanted_metab),
                   toxin = paste(wanted_tox),
                   just_r = sqrt(r_squared),
                   estimate = lm_full$estimate,
                   r_direct = if_else(estimate < 0, just_r * -1, just_r))
  my_list <- list(LinearModel = lm_full,
                  WantedStats = output)
  return(my_list)
}

## creating a nested for loop since running this function individually is a nightmare
r2_value_for_loop <- function(biom_table,
                              wanted_col,
                              wanted_conc) {
  ## nested for loop for the r squared and p values 
  output <- tibble()
  for(i in unique(unlist(biom_table$diet))) {
    for(j in unique(unlist(biom_table$metabolite))) {
      for(k in unique(unlist(biom_table[wanted_col]))) {
        tmp_output <- r2_value(biom_table,
                               i,
                               j,
                               wanted_col,
                               k,
                               wanted_conc)$WantedStats
        output <- bind_rows(output, tmp_output)
      }
    }
  }
  return(output)
}

## putting stats directly on correlation plots 
stat_on_plot <- function(stat_table,
                         wanted_col_list,
                         x_col_name,
                         x_col_value,
                         y_col_name,
                         y_col_value,
                         plot,
                         plot_text_size){
  ## making table conducive to labeling plot 
  proc_stat_table <- stat_table %>% 
    filter(signif != 'ns') %>% 
    select(all_of(wanted_col_list)) %>% 
    ## created columns need to match up with the column names called for the x and y axis in the plot
    ## numeric values added are the x and y coordinates for where the label will sit in the facet block 
    mutate("{x_col_name}" := paste(x_col_value),
           "{x_col_name}" := as.numeric(.data[[x_col_name]]),
           "{y_col_name}" := paste(y_col_value),
           "{y_col_name}" := as.numeric(.data[[y_col_name]]),
           p_value = signif(p_value, digits = 3),
           r_squared = signif(r_squared, digits = 3),
           pVal_rSquare = paste0('p-value: ', p_value, "\n", 
                                 'r2: ', r_squared))
  
  ## putting labels on plot 
  plot_wStats <- plot +
    geom_label(data = proc_stat_table, 
               label = proc_stat_table$pVal_rSquare,
               color = 'black',
               fontface = 'bold',
               size = plot_text_size)
  
  ## creating list of my outputs
  my_list <- list(ProcStatTable = proc_stat_table,
                  PlotwStats = plot_wStats)
  
  return(my_list)
}
```

**File Paths**
```{r}
## reading in processed files so I don't have to reprocess them again
metadata_FP <- '../data/misc/filt_cecal_processed_metadata.tsv'
metab_FP <- '../data/misc/processed_metabolomics.tsv'
toxin_FP <- '../data/misc/processed_neatToxin.tsv'

## lists to redo the diet names on the facet labels of the ggplot created below 
diet_labs <- 
    c('Chow', 
      'High Fat / High Fiber', 
      'High Fat / Low Fiber', 
      'Low Fat / High Fiber', 
      'Low Fat / Low Fiber')

names(diet_labs) <- c('Chow', 'HF/HF', 'HF/LF', 'LF/HF', 'LF/LF')

wanted_metabs <- c('Acetic Acid (ug/g)',
                   'Propanoic Acid (ug/g)',
                   'n-Butanoic Acid (ug/g)')
metab_labs <- c('Acetic Acid',
                'Propanoic Acid',
                'n-Butanoic Acid')
names(metab_labs) <- wanted_metabs

neat_labs <- c('TcdA', 'TcdB')
names(neat_labs) <- c('Total TcA Neat', 'Total TcB Neat')

stat_y_labs <- c("Chow",
                 "HFt/HFb",
                 "HFt/LFb",
                 "LFt/HFb",
                 "LFt/LFb")
```

**File Prep**
```{r}
metadata <- read_tsv(metadata_FP)
metab <- read_tsv(metab_FP)
neat_toxin <- read_tsv(toxin_FP)

## overall table
## adding two so that I don't have any zeroes 
## zeroes get cut off on the plot since I have the axis in log10
## combining metabolite and neat toxin tables
metab %>% 
  select(mouse_id, metabolite, concentration) %>% 
  left_join(neat_toxin, by = 'mouse_id') %>% 
  na.omit() %>% 
  mutate(metab_conc_norm = (concentration + 2),
         neat_conc_norm = (neat_conc + 2)) -> metab_neatTox

## filtered tables for individual plots
metab_neatTox %>% 
  filter(metabolite == 'Acetic Acid (ug/g)') -> acetic_neatTox

metab_neatTox %>% 
  filter(metabolite == 'n-Butanoic Acid (ug/g)') -> butanoic_neatTox

metab_neatTox %>% 
  filter(metabolite == 'Propanoic Acid (ug/g)') -> propanoic_neatTox
```

**Comparison Plots**
Acetic Acid
```{r, warning=FALSE, fig.height=4, fig.width=10}
tox_acetic <- apppleplots::correlation_plots(input_table = acetic_neatTox,
                                             x_value = 'neat_conc_norm',
                                             y_value = 'metab_conc_norm',
                                             x_transform = TRUE,
                                             y_transform = TRUE,
                                             point_alpha = 0.4,
                                             regression_method = 'lm',
                                             facet_rows = 'neat_toxin',
                                             facet_cols = 'diet',
                                             row_labs = neat_labs,
                                             col_labs = diet_labs,
                                             x_name = 'Toxin Concentration (ng/uL) (log10)',
                                             y_name = 'SCFA Concentration (ug/g) (log10)',
                                             title_content = 'C. difficile Toxin by Acetate')
  
tox_acetic
```

n-Butanoic Acid
```{r, warning=FALSE, fig.height=4, fig.width=10}
tox_butanoic <- apppleplots::correlation_plots(input_table = butanoic_neatTox,
                                               x_value = 'neat_conc_norm',
                                               y_value = 'metab_conc_norm',
                                               x_transform = TRUE,
                                               y_transform = TRUE,
                                               point_alpha = 0.4,
                                               regression_method = 'lm',
                                               facet_rows = 'neat_toxin',
                                               facet_cols = 'diet',
                                               row_labs = neat_labs,
                                               col_labs = diet_labs,
                                               x_name = 'Toxin Concentration (ng/uL) (log10)',
                                               y_name = 'SCFA Concentration (ug/g) (log10)',
                                               title_content = 'C. difficile Toxin by Butyrate')
tox_butanoic
```

Propanoic Acid 
```{r, warning=FALSE, fig.height=4, fig.width=10}
tox_propanoic <- apppleplots::correlation_plots(input_table = propanoic_neatTox,
                                                x_value = 'neat_conc_norm',
                                                y_value = 'metab_conc_norm',
                                                x_transform = TRUE,
                                                y_transform = TRUE,
                                                point_alpha = 0.4,
                                                regression_method = 'lm',
                                                facet_rows = 'neat_toxin',
                                                facet_cols = 'diet',
                                                row_labs = neat_labs,
                                                col_labs = diet_labs,
                                                x_name = 'Toxin Concentration (ng/uL) (log10)',
                                                y_name = 'SCFA Concentration (ug/g) (log10)',
                                                title_content = 'C. difficile Toxin by Propionate')

tox_propanoic
```

**Statistical Analysis**
```{r}
stat_table <- r2_value_for_loop(metab_neatTox,
                                "neat_toxin",
                                "neat_conc_norm")
## assigning p value significance
stat_table['signif'] <- symnum(stat_table$p_value,
                               cutpoints = c(0, 0.0001, 0.001, 0.01, 0.05, 1),
                               symbols = c("****", "***", "**", "*", "ns"),
                               abbr.colnames = FALSE,
                               na = "")
```

**Stats on Actual Plot**
```{r,warning=FALSE, fig.height=4, fig.width=10}
names(stat_table)[names(stat_table) == 'toxin'] <- 'neat_toxin'
col_list <- c('diet', 'neat_toxin', 'signif', 'p_value', 'r_squared')

## acetate
stat_table %>% 
  filter(metabolite == 'Acetic Acid (ug/g)') %>% 
  select(-metabolite) -> acetate_stat_table

tox_acetic_list <- stat_on_plot(stat_table = acetate_stat_table,
                                wanted_col_list = col_list,
                                x_col_name = 'neat_conc_norm',
                                x_col_value = '15',
                                y_col_name = 'metab_conc_norm',
                                y_col_value = '5.5',
                                plot = tox_acetic,
                                plot_text_size = 3)

tox_acetic_stats <- tox_acetic_list$PlotwStats

## butyrate
stat_table %>% 
  filter(metabolite == 'n-Butanoic Acid (ug/g)') %>% 
  select(-metabolite) -> butyrate_stat_table

tox_butanoic_list <- stat_on_plot(stat_table = butyrate_stat_table,
                                  wanted_col_list = col_list,
                                  x_col_name = 'neat_conc_norm',
                                  x_col_value = '15',
                                  y_col_name = 'metab_conc_norm',
                                  y_col_value = '12',
                                  plot = tox_butanoic,
                                  plot_text_size = 3)

tox_butanoic_stats <- tox_butanoic_list$PlotwStats

## propionate
stat_table %>% 
  filter(metabolite == 'Propanoic Acid (ug/g)') %>% 
  select(-metabolite) -> propionate_stat_table

tox_propanoic_list <- stat_on_plot(stat_table = propionate_stat_table,
                                  wanted_col_list = col_list,
                                  x_col_name = 'neat_conc_norm',
                                  x_col_value = '15',
                                  y_col_name = 'metab_conc_norm',
                                  y_col_value = '5.5',
                                  plot = tox_propanoic,
                                  plot_text_size = 3)

tox_propanoic_stats <- tox_propanoic_list$PlotwStats

tox_acetic_stats
tox_butanoic_stats
tox_propanoic_stats
```


**Statistical Visualization**
```{r, fig.height=3, fig.width=5.5}
tox_metab_stat_vis <- apppleplots::stat_heat_plot(input_table = stat_table,
                                                  x_value = 'neat_toxin',
                                                  y_value = 'diet',
                                                  x_value_type = 'discrete',
                                                  y_value_type = 'discrete',
                                                  pairwise = FALSE,
                                                  correlation = TRUE,
                                                  tile_fill = 'r_direct',
                                                  tile_outline_color = 'black',
                                                  tile_alpha = 0.6,
                                                  text_value = 'signif',
                                                  low_color = 'blue',
                                                  high_color = 'green',
                                                  legend_name = 'Correlation\nCoefficient',
                                                  x_labels = neat_labs,
                                                  y_labels = stat_y_labs,
                                                  facet_by = 'metabolite',
                                                  facet_labels = metab_labs,
                                                  x_name = 'Toxin',
                                                  y_name = 'Diet',
                                                  title_content = "SCFA and Toxin Concentration Comparisons")


tox_metab_stat_vis
```

**Putting my Plots Together**
```{r, warning=FALSE, fig.height=7, fig.width=18}
plot_grid(tox_acetic_stats, tox_butanoic_stats,
          tox_propanoic_stats, tox_metab_stat_vis,
          nrow = 2,
          labels = c('a)', 'b)', 'c)', 'd)')) -> metab_tox_plots

metab_tox_plots
```

**Saving my Outputs**
```{r}
## as a pdf
ggsave('../plots/metab_tox_comp.pdf',
       plot = metab_tox_plots,
       width = 18,
       height = 7)
ggsave('../plots/toxin_acetateStats_plot.pdf',
       plot = tox_acetic_stats,
       width = 10,
       height = 4)
ggsave('../plots/toxin_butyrateStats_plot.pdf',
       plot = tox_butanoic_stats,
       width = 10,
       height = 4)
ggsave('../plots/toxin_propionateStats_plot.pdf',
       plot = tox_propanoic_stats,
       width = 10,
       height = 4)

## as an rdata object
save(tox_acetic_stats,
     file = '../../figures/tox_metab_acetic.rdata')
save(tox_butanoic_stats,
     file = '../../figures/tox_metab_butanoic.rdata')
save(tox_propanoic_stats,
     file = '../../figures/tox_metab_propanoic.rdata')
save(tox_metab_stat_vis,
     file = '../../figures/tox_metab_stats.rdata')
```

