---
title: "toxin"
output: html_document
date: "2023-11-09"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(broom)
library(cowplot)
library(magrittr)
library(qiime2R)
library(tidyverse)
library(ggpubr)
library(rstatix)
library(glue)
library(argparse)
```

**Functions**
```{r}
## 1
## for toxin file prep
file_prep <- function(metadata_fp,
                      toxin_fp){
  ## toxin data 
  toxin <- read_tsv(toxin_FP)
  wanted_ids <- toxin$mouse_id
  
  ## metadata 
  metadata <- read_tsv(metadata_FP) %>% 
    select(!c(tube_num, date, corr_sample_num))
  
  ## toxin neat concentrations (non_diluted)
  toxin %>% 
    merge(metadata, by = 'mouse_id') %>% 
    select(!c('Total TcA 1:10', 'Total TcB 1:10')) %>% 
    gather('Total TcA Neat', 'Total TcB Neat', 
           key = neat_toxin, value = neat_conc) -> pre_neat_toxin
  
  pre_neat_toxin$neat_conc[pre_neat_toxin$neat_conc == 'BDL'] <- '0'
  
  pre_neat_toxin %>% 
    mutate(neat_conc = as.numeric(neat_conc)) %>% 
    select(!c('Tube_Label',
              'Collection Date',
              'Sample_Type',
              'Extra_Sample')) -> neat_toxin
    
  ## toxin diluted concentrations 
  ## chow is not included in this 
  toxin %>% 
    merge(metadata, by = 'mouse_id') %>% 
    select(!c('Total TcA Neat', 'Total TcB Neat')) %>% 
    gather('Total TcA 1:10', 'Total TcB 1:10',
           key = dil_toxin, value = dil_conc) -> pre_dil_toxin
  
  pre_dil_toxin$dil_conc[pre_dil_toxin$dil_conc == 'BDL'] <- '0'
  pre_dil_toxin$dil_conc[pre_dil_toxin$dil_conc == 'Chow'] <- '0'
  
  pre_dil_toxin %>% 
    mutate(dil_conc = as.numeric(dil_conc)) %>% 
    filter(diet != 'Chow') %>% 
    select(!c('Tube_Label',
              'Collection Date',
              'Sample_Type',
              'Extra_Sample')) -> dil_toxin
  ## creating a list of my outputs
  my_list <- list(Metadata = metadata,
                  NeatToxin = neat_toxin,
                  DilToxin = dil_toxin)
  return(my_list)
}

## 2
## statistical analysis function
stats <- function(biom_table,
                  tox_col,
                  conc_col){
  ## kruskal test
  biom_table %>% 
    group_by(biom_table[tox_col]) %>% 
    do(tidy(kruskal.test(.data[[conc_col]] ~ diet,
                         data = .))) %>% 
    ungroup() %>%
    arrange(p.value) %>%
    mutate(p.adj = p.adjust(p.value,
                            method = "BH"),
           test_id = paste(.data[[tox_col]])) -> kruskal
  ## dunns post hoc test
  diet_name <- 'diet'
  test <- reformulate(glue("{diet_name}"),glue("{conc_col}"))
  
  biom_table %>% 
    group_by(biom_table[tox_col]) %>% 
    mutate(test_id = paste(.data[[tox_col]])) %>% 
    filter(test_id %in% kruskal$test_id) %>% 
    dunn_test(test,
              p.adjust.method = 'BH',
              data = .) %>% 
    add_y_position(scales = 'free_y') -> dunn
  ## linear modeling
  biom_table %>% 
    group_by(biom_table[tox_col]) %>%
    do(glance(lm(.data[[conc_col]] ~ (purified_diet * seq_depth) + high_fat * high_fiber,
                 data = .))) %>% 
    ungroup() %>%
    na.omit() %>%
    mutate(adj.p = p.adjust(p.value,
                            method = "BH"),
           test_id = paste(.data[[tox_col]])) -> lm_full
  biom_table %>% 
    group_by(biom_table[tox_col]) %>% 
    mutate(test_id = paste(.data[[tox_col]])) %>% 
    filter(test_id %in% lm_full$test_id) %>%
    do(tidy(lm(.data[[conc_col]] ~ (purified_diet * seq_depth) + high_fat * high_fiber,
               data = .))) %>% 
    filter(term != '(Intercept)') -> lm
  
  lm['signif'] <- symnum(lm$p.value,
                         cutpoints = c(0, 0.0001, 0.001, 0.01, 0.05, 1),
                         symbols = c("****", "***", "**", "*", "ns"),
                         abbr.colnames = FALSE,
                         na = "")
  ## creating a list of my outputs
  my_list <- list(KruskalTest = kruskal,
                  DunnPostHoc = dunn,
                  LinearModel = lm)
  return(my_list)
}

## 3 
## toxin ggplot function
tox_plot <- function(biom_table,
                     tox_col,
                     conc_col,
                     x_labels,
                     facet_labs,
                     dunn,
                     title){
  biom_table %>% 
    na.omit() %>% 
    ggplot(aes(x = diet, y = .data[[conc_col]])) +
    geom_violin(aes(group = diet), draw_quantiles = c(0.5)) +
    geom_jitter(alpha = 0.4, width = 0.1, height = 0)+
    scale_x_discrete(labels = x_labels) +
    facet_wrap(~.data[[tox_col]],
               labeller = labeller(.cols = facet_labs)) +
    stat_pvalue_manual(dunn,
                       tip.length = 0.01,
                       label = 'p.adj.signif',
                       hide.ns = TRUE) +
    theme_bw(base_size = 14) +
    xlab('Diet') +
    ylab('Concentration') +
    ggtitle(title) -> plot
  return(plot)
}
```

**File Paths**
```{r}
metadata_FP <- '../data/misc/filt_cecal_processed_metadata.tsv'
toxin_FP <- '../data/misc/toxin_final_data.tsv'

## labeling lists
neat_labs <- c('TcdA', 'TcdB')
names(neat_labs) <- c('Total TcA Neat', 'Total TcB Neat')
neat_x_labs <- c('Chow', 
                 'HFt/\nHFb', 
                 'HFt/\nLFb',
                 'LFt/\nHFb', 
                 'LFt/\nLFb')
neat_title <- 'Cecal Toxin Neat Concentration by Mouse Diet'

dil_labs <- c('TcdA', 'TcdB')
names(dil_labs) <- c('Total TcA 1:10', 'Total TcB 1:10')
dil_x_labs <- c('HFt/\nHFb', 
                'HFt/\nLFb',
                'LFt/\nHFb', 
                'LFt/\nLFb')
dil_title <- 'Cecal Toxin Diluted Concentration (1:10) by Mouse Diet'
```

**Data Wrangling**
```{r}
toxin_files <- file_prep(metadata_FP,
                         toxin_FP)

metadata <- toxin_files$Metadata
neat_tox_table <- toxin_files$NeatToxin
dil_tox_table <- toxin_files$DilToxin
```

**Stats**
```{r}
## neat
neat_stats <- stats(neat_tox_table,
                    "neat_toxin",
                    "neat_conc")

neat_dunn <- neat_stats$DunnPostHoc
neat_kruskal <- neat_stats$KruskalTest
neat_lm <- neat_stats$LinearModel

## diluted
dil_stats <- stats(dil_tox_table,
                   "dil_toxin",
                   "dil_conc")

dil_dunn <- dil_stats$DunnPostHoc
dil_kruskal <- dil_stats$KruskalTest
dil_lm <- dil_stats$LinearModel
```

**Plots**
```{r, fig.height=5, fig.width=10}
## neat 
neat_plot <- tox_plot(neat_tox_table,
                      "neat_toxin",
                      "neat_conc",
                      neat_x_labs,
                      neat_labs,
                      neat_dunn,
                      neat_title)
## diluted
dil_plot <- tox_plot(dil_tox_table,
                      "dil_toxin",
                      "dil_conc",
                      dil_x_labs,
                      dil_labs,
                      dil_dunn,
                      dil_title)

neat_plot
dil_plot
```

**Saving my Outputs**
```{r}
## plots
ggsave("../plots/neat_toxin.pdf",
       plot = neat_plot,
       width = 8,
       height = 5)

ggsave("../plots/dil_toxin.pdf",
       plot = dil_plot,
       width = 8,
       height = 5)

## as an Rdata object for manuscript figures
save(neat_plot,
     file = '../../figures/neat_toxin.rdata')
save(dil_plot,
     file = '../../figures/dil_toxin.rdata')

## stats
write_tsv(neat_kruskal,
          "../stats/neatToxin_kruskal_test.tsv")
write_tsv(neat_dunn,
          "../stats/neatToxin_dunn_test.tsv")
write_tsv(dil_kruskal,
          "../stats/dilToxin_kruskal_test.tsv")
write_tsv(dil_dunn,
          "../stats/dilToxin_dunn_test.tsv")
```

