---
title: "metab_toxin_comp"
output: html_document
date: "2023-09-19"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(broom)
library(cowplot)
library(magrittr)
library(qiime2R)
library(tidyverse)
library(naniar)
library(ggpubr)
library(rstatix)
library(viridis)
```

**File Prep and Plot Functions**
```{r}
file_prep <- function(metadata_fp,
                      metab_fp,
                      metab_col_filter,
                      metab_filter,
                      toxin_fp){
  ## metadata file
  metadata <- read_tsv(metadata_fp)
  ## metabolomics file
  metab <- read_csv(metab_fp)
  wanted_metab_ids <- metab$mouse_id
  metadata %>% 
    group_by(mouse_id) %>% 
    filter(mouse_id %in% wanted_metab_ids) %>% 
    left_join(metab, by = 'mouse_id') %>% 
    select(-(all_of(metab_col_filter))) %>% 
    gather(metab_filter, key = metabolite, value = concentration) %>% 
    filter(!is.na(mouse_id)) -> pre_metab
  ## changes all 'ND' values in the concentration column to 0 
  pre_metab$concentration[pre_metab$concentration == 'ND'] <- 0
  pre_metab %>% 
    filter(!is.na(concentration)) %>% 
    mutate(concentration = as.numeric(concentration)) %>% 
    distinct(mouse_id, concentration, .keep_all = TRUE) -> big_metab
  ## toxin file
  toxin <- read_tsv(toxin_fp)
  wanted_toxin_ids <- toxin$mouse_id
  metadata %>% 
    group_by(mouse_id) %>% 
    filter(mouse_id %in% wanted_toxin_ids) -> meta_filt
  toxin %>% 
    left_join(meta_filt, by = 'mouse_id') %>% 
    gather('Total TcA Neat', 'Total TcB Neat', 
           key = neat_toxin, value = neat_conc) %>% 
    gather('Total TcA 1:10', 'Total TcB 1:10',
           key = dil_toxin, value = dil_conc) -> pre_toxin
  
  pre_toxin$neat_conc[pre_toxin$neat_conc == 'BDL'] <- '0'
  pre_toxin$dil_conc[pre_toxin$dil_conc == 'BDL'] <- '0'
  pre_toxin$dil_conc[pre_toxin$dil_conc == 'Chow'] <- '0'
  
  pre_toxin %>% 
    filter(!is.na(dil_conc),
           !is.na(neat_conc)) %>%
    mutate(neat_conc = as.numeric(neat_conc),
           dil_conc = as.numeric(dil_conc)) %>% 
    select(-'Extra_Sample', -'Tube_Label', -'Collection Date',
           -'Sample_Type') -> big_toxin
  big_toxin %>% 
    distinct(mouse_id, dil_conc, .keep_all = TRUE) %>% 
    filter(diet != 'Chow') -> dil_toxin
  big_toxin %>%
    distinct(mouse_id, neat_conc, .keep_all = TRUE) -> neat_toxin 
  ## creating a list of my outputs
  my_list <- list(Metadata = metadata,
                  Metabolomics = big_metab,
                  Toxin = big_toxin,
                  NeatToxin = neat_toxin,
                  DilToxin = dil_toxin)
  return(my_list)
}

## histo plot comparison function
comp_plot <- function(metab_table,
                      ## toxin or metabolomics?
                       wanted_table,
                       ## this is what you want your x axis to be (neat, diluted, or concentration)? 
                       wanted_x,
                       ## this is toxin/metabolite column you want to filter by (neat or diluted)?
                       wanted_y,
                       ## what is the toxin/metabolite you want to filter by called in the table?
                       wanted_y_name,
                       diet_labels,
                       tox_labels,
                       title){
  ## putting tables together
  metab_table %>% 
    select(mouse_id, metabolite, concentration) %>% 
    left_join(wanted_table, by = 'mouse_id') %>% 
    na.omit() -> compiled_table
  ## constructing plot
  compiled_table %>% 
    filter(.data[[wanted_y]] == wanted_y_name) %>% 
    na.omit() %>% 
    ggplot(aes(x = .data[[wanted_x]], y = concentration)) +
    scale_x_continuous(trans = 'log10') +
    geom_jitter(alpha = 0.4, width = 0.1, height = 0) +
    geom_smooth(method = 'lm', se = FALSE) +
    facet_grid(neat_toxin~diet,
               labeller = labeller(neat_toxin = tox_labels,
                                   diet = diet_labels),
               scales = 'free_y') +
    theme_bw() +
    theme(strip.text.y = element_text(angle = 0)) +
    xlab('Toxin Concentration') +
    ylab('Metabolite Concentration') +
    ggtitle(title) -> plot
  return(plot)
}
```

**Statisitical Analysis Functions**
```{r}
## runs linear modeling on the table, diet, location, and toxin/metabolite wanted and returns full results 
## along with a table containing the r2 and p-value 
## this goes into the following function with a for loop 
r2_value <- function(biom_table,
                     wanted_diet,
                     wanted_metab,
                     tox_col,
                     wanted_tox,
                     wanted_conc_value){
  biom_table %>% 
    filter(diet == wanted_diet,
           metabolite == wanted_metab,
           .data[[tox_col]] == wanted_tox) %>% 
    do(glance(lm(concentration ~ .data[[wanted_conc_value]],
                 data = .))) -> lm_results
  output <- list(r_squared = lm_results$r.squared,
                 p_value = lm_results$p.value)
  output <- as_tibble(output) %>%
            mutate(diet = paste(wanted_diet),
                   metab = paste(wanted_metab),
                   toxin = paste(wanted_tox),
                   just_r = sqrt(r_squared))
  my_list <- list(LinearModel = lm_results,
                  WantedStats = output)
  return(my_list)
}

## creating a nested for loop since running this function individually is a nightmare
r2_value_for_loop <- function(biom_table,
                              wanted_col,
                              wanted_conc) {
  ## nested for loop for the r squared and p values 
  output <- tibble()
  for(i in unique(unlist(biom_table$diet))) {
    for(j in unique(unlist(biom_table$metabolite))) {
      for(k in unique(unlist(biom_table[wanted_col]))) {
        tmp_output <- r2_value(biom_table,
                               i,
                               j,
                               wanted_col,
                               k,
                               wanted_conc)$WantedStats
        output <- bind_rows(output, tmp_output)
      }
    }
  }
  return(output)
}

## statistical visualization plot function
stat_plot <- function(stat_table,
                      wanted_labels,
                      title){
  stat_table %>% 
    ggplot(aes(x = toxin, y = diet)) +
    geom_tile(aes(fill = just_r), color = 'black', alpha = 0.6) +
    geom_text(aes(label = signif)) +
    scale_fill_viridis(option = "H", name = "Correlation\nCoefficient") +
    scale_x_discrete(labels = c("TcdA",
                                "TcdB")) +
    scale_y_discrete(labels = c("Chow",
                                "HFt/HFb",
                                "HFt/LFb",
                                "LFt/HFb",
                                "LFt/LFb")) +
    facet_wrap(~metab,
               labeller = labeller(metab = wanted_labels)) +
    theme_bw() +
    xlab("Toxin") +
    ylab("Diet") +
    ggtitle(title) -> plot
  return(plot)
  }
```

**File Paths**
```{r}
metadata_FP <- '../data/misc/processed_metadata.tsv'
metab_FP <- '../data/misc/metabolomics.csv'
toxin_FP <- '../data/misc/toxin_final_data.tsv'

## lists to redo the diet names on the facet labels of the ggplot created below 
diet_labs <- 
    c('Chow', 
      'High Fat / High Fiber', 
      'High Fat / Low Fiber', 
      'Low Fat / High Fiber', 
      'Low Fat / Low Fiber')

names(diet_labs) <- c('Chow', 'HF/HF', 'HF/LF', 'LF/HF', 'LF/LF')

wanted_metabs <- c('Acetic Acid (ug/g)',
                   'Propanoic Acid (ug/g)',
                   'n-Butanoic Acid (ug/g)')
unwanted_columns <- c('2-methyl-propanoic acid (ug/g)',
                     'Isopentanoic Acid (ug/g)',
                     '2-methyl-Butanoic Acid (ug/g)',
                     'Pentanoic Acid (ug/g)',
                     'Notes',
                     'Sample Group',
                     'SCFA Data File',
                     'Acq. Date-Time',
                     'Tube_Label',
                     'Sample_Type',
                     'Collection Date',
                     'Dil.')
metab_labs <- c('Acetic Acid',
                'Propanoic Acid',
                'n-Butanoic Acid')
names(metab_labs) <- wanted_metabs
neat_labs <- c('TcdA', 'TcdB')
names(neat_labs) <- c('Total TcA Neat', 'Total TcB Neat')

dil_labs <- c('TcdA', 'TcdB')
names(dil_labs) <- c('Total TcA 1:10', 'Total TcB 1:10')
```

**File Prep**
```{r}
comp_files <- file_prep(metadata_FP,
                        metab_FP,
                        unwanted_columns,
                        wanted_metabs,
                        toxin_FP)

metadata <- comp_files$Metadata
metab <- comp_files$Metabolomics
big_toxin <- comp_files$Toxin
dil_toxin <- comp_files$DilToxin
neat_toxin <- comp_files$NeatToxin
```


**Comparison Plots**
Acetic Acid
```{r, warning=FALSE, fig.height=4, fig.width=8}
tox_acetic <- comp_plot(metab,
                        neat_toxin,
                        "neat_conc",
                        "metabolite",
                        "Acetic Acid (ug/g)",
                        diet_labs,
                        neat_labs,
                        "Acetic Acid")
tox_acetic
```

n-Butanoic Acid
```{r, warning=FALSE, fig.height=4, fig.width=8}
tox_butanoic <- comp_plot(metab,
                        neat_toxin,
                        "neat_conc",
                        "metabolite",
                        "n-Butanoic Acid (ug/g)",
                        diet_labs,
                        neat_labs,
                        "n-Butanoic Acid")
tox_butanoic
```

Propanoic Acid 
```{r, warning=FALSE, fig.height=4, fig.width=8}
tox_propanoic <- comp_plot(metab,
                          neat_toxin,
                          "neat_conc",
                          "metabolite",
                          "Propanoic Acid (ug/g)",
                          diet_labs,
                          neat_labs,
                          "Propanoic Acid")
tox_propanoic
```

**Statistical Analysis**
```{r}
metab %>% 
    select(mouse_id, metabolite, concentration) %>% 
    left_join(neat_toxin, by = 'mouse_id') %>% 
    na.omit() %>% 
    ungroup() -> metab_tox

stat_table <- r2_value_for_loop(metab_tox,
                                "neat_toxin",
                                "neat_conc")
## assigning p value significance
stat_table['signif'] <- symnum(stat_table$p_value,
                               cutpoints = c(0, 0.0001, 0.001, 0.01, 0.05, 0.1, 1),
                               symbols = c("****", "***", "**", "*", "+", "ns"),
                               abbr.colnames = FALSE,
                               na = "")
```


**Statistical Visualization**
```{r}
stat_plot(stat_table,
          metab_labs,
          "Metabolite and Toxin Concentration Comparisons") -> tox_metab_stat_vis

tox_metab_stat_vis
```

**Putting my Plots Together**
```{r, warning=FALSE, fig.height=7, fig.width=15}
plot_grid(tox_acetic, tox_butanoic,
          tox_propanoic, tox_metab_stat_vis,
          nrow = 2,
          labels = c('a)', 'b)', 'c)', 'd)')) -> metab_tox_plots

metab_tox_plots
```

**Saving my Outputs**
```{r}
ggsave('metab_tox_comp.pdf',
       plot = metab_tox_plots,
       width = 15,
       height = 7,
       path = '../plots')
```

