---
title: "metadata_wrangling"
output: html_document
date: "2023-11-01"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(magrittr)
library(broom)
library(qiime2R)
```

**File Paths**
```{r}
colon_meta_fp <- '../data/misc/processed_metadata.tsv'
cecum_meta_fp <- '../cecum/data/misc/cecal_processed_metadata.tsv'
preProc_cecum_fp <- '../cecum/data/misc/cecal_metadata.tsv'
updated_meta_fp <- '../cecum/data/misc/updated_cecal_metadata.tsv'
```

**Reading in Files**
```{r}
colon_meta <- read_tsv(colon_meta_fp)
cecum_meta <- read_tsv(cecum_meta_fp)
preProc_cecum <- read_tsv(preProc_cecum_fp)
updated_meta <- read_tsv(updated_meta_fp)
```

**Putting together cecum and colon metadata files**
```{r}
cecum_meta %>% 
  select(!c(tube_num,
            date,
            corr_sample_num)) -> mini_cecum_meta

colon_meta %>% 
  select(-diet_true) %>% 
  filter(day_post_inf != 3) -> mini_colon_meta

rbind(mini_cecum_meta,
      mini_colon_meta) -> combined_metadata
```

**Adding study (batch/replicates to pre-processed cecal metadata)**
```{r}
cecum_meta %>% 
  select(sampleid, facility, study) -> to_join_preProc

names(to_join_preProc)[names(to_join_preProc) == 'sampleid'] <- '#SampleID'

preProc_cecum %>% 
  left_join(to_join_preProc) %>% 
  filter(study != 1) -> new_preProc_cecum
```

**Adding study (batch/replicates) to updated cecal metadata**
This one is needed for metadata processing
```{r}
updated_meta %>% 
  left_join(to_join_preProc) %>% 
  filter(study != 1) -> new_updated_meta
```

**Saving my outputs**
```{r}
write_tsv(combined_metadata,
          '../data/misc/combined_metadata.tsv')
write_tsv(new_preProc_cecum,
          '../cecum/data/misc/filt_cecal_metadata.tsv')
write_tsv(new_updated_meta,
          '../cecum/data/misc/filt_updated_cecal_metadata.tsv')
```

