---
title: "micro_abun_correlations"
output: html_document
date: "2023-10-11"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(qiime2R)
library(cowplot)
library(magrittr)
library(rstatix)
library(vegan)
library(broom)
```

**Functions**
```{r}
## abundance file prep and filtering function
## combines all files into one large table
abun_file_prep <- function(metadata_fp,
                                  tax_fp,
                                  otu_table_fp,
                                  histo_fp,
                                  tax_level,
                                  wanted_tax){
  ## metadata
  metadata <- read_tsv(metadata_fp)
  ## histopathology scores
  histo <- read_csv(histo_fp)
  ## taxonomy
  taxonomy <- read_qza(tax_fp)$data %>% 
  parse_taxonomy() %>% 
  rownames_to_column('asv')
  ## otu table 
  otu_table <- read_qza(otu_table_fp)$data
  otu_table %>% 
    as_tibble(rownames = 'asv') %>% 
    gather(-asv, key = sampleid, value = abun) %>% 
    group_by(sampleid) %>% 
    mutate(rel_abun = abun/sum(abun)) %>% 
    mutate(rel_abun = rel_abun + 0.000001) -> otu_table
  ## joining all tables together 
  otu_table %>% 
    left_join(metadata, by = 'sampleid') %>% 
    left_join(taxonomy, by = 'asv') %>% 
    merge(histo, by = 'mouse_id') %>% 
    group_by(mouse_id) %>% 
    filter(day_post_inf == max(day_post_inf)) %>% 
    ungroup() %>% 
    gather(cecum, colon, key = tissue, value = score) -> abun_table
  
  abun_table %>% 
    group_by(sampleid, day_post_inf, diet, mouse_id, 
             purified_diet, high_fat, high_fiber, 
             seq_depth, .data[[tax_level]], asv, tissue, score) %>% 
    summarise(rel_abund = sum(rel_abun)) %>% 
    filter(.data[[tax_level]] %in% wanted_tax) %>% 
    mutate(mouse_fact = as.factor(mouse_id),
           day_fact = as.factor(day_post_inf)) -> abun_filt
  ## creating a list for my outputs
  my_list <- list(Metadata = metadata,
                  Taxonomy = taxonomy,
                  OTUTable = otu_table,
                  Histo = histo,
                  AbundanceTable = abun_filt)
  return(my_list)
}
```

**Input File Paths**
```{r}
otu_table_FP <- '../data/qiime/taxonomy_filtered.qza'
tax_FP <- '../data/qiime/taxonomy.qza'
metadata_FP <- '../data/misc/processed_metadata.tsv'
histo_FP <- '../data/misc/histo_data.csv'
tmp_meta_fp <- '../data/misc/updated_metadata.tsv'

## diet only file paths
ancombc_pVal_fp <- '../data/qiime/ancombc_diet_only/p_val_slice.csv'
ancombc_qVal_fp <- '../data/qiime/ancombc_diet_only/q_val_slice.csv'
ancombc_wSlice_fp <- '../data/qiime/ancombc_diet_only/w_slice.csv'
ancombc_seSlice_fp <- '../data/qiime/ancombc_diet_only/se_slice.csv'
ancombc_lfcSlice_fp <- '../data/qiime/ancombc_diet_only/lfc_slice.csv'

wanted_family <- c('Enterobacteriaceae', 
                         'Enterococcaceae', 
                         'Staphylococcaceae',
                         'Lachnospiraceae',
                         'Ruminococcaceae',
                         'Bacteroidaceae',
                         'Marinifilaceae',
                         'Peptostreptococcaceae')
wanted_level <- 'Family'
```

**Processing my Files into One Giant Table**
```{r}
abun_files <- abun_file_prep(metadata_FP,
                             tax_FP,
                             otu_table_FP,
                             histo_FP,
                             wanted_level,
                             wanted_family)

abun_filt <- abun_files$AbundanceTable
tax <- abun_files$Taxonomy
otu <- abun_files$OTUTable
```

```{r}
abun_filt %>% 
  na.omit() %>% 
  group_by(diet, tissue, Family) %>% 
  do(glance(lm(score ~ rel_abund,
             data = .)))
  # mutate(adj.p = p.adjust(p.value,
  #                         method = 'BH')) %>% 
  # filter(p.value <= 0.05,
  #        term != '(Intercept)')
```
## **ANCOMBC results for ASV by Diet Only**
**Reading in ANCOMBC results for ASV by Diet**
these are all calculated relative to chow as the baseline diet (I'm not sure how to turn the reference level off)
```{r}
new_col_names <- c('asv',
                   'intercept',
                   'HF/HF',
                   'HF/LF',
                   'LF/HF',
                   'LF/LF')
## p-values
p_val <- read_csv(ancombc_pVal_fp,
                  skip = 1,
                  col_names = new_col_names)

## adjusted p-values
q_val <- read_csv(ancombc_qVal_fp,
                  skip = 1,
                  col_names = new_col_names)

## test statistic
w_slice <- read_csv(ancombc_wSlice_fp,
                    skip = 1,
                    col_names = new_col_names)

## standard errors
se_slice <- read_csv(ancombc_seSlice_fp,
                     skip = 1,
                     col_names = new_col_names)

## log fold changes
lfc <- read_csv(ancombc_lfcSlice_fp,
                skip = 1,
                col_names = new_col_names)
```
**Log-fold-change Visualization**
```{r, fig.width=20, fig.height=8}
## putting log fold change data with taxonomic information
lfc %>% 
  select(-intercept) %>% 
  gather(-asv, key = diet, value = lfc) %>% 
  inner_join(tax, by = 'asv') -> lfc_w_tax

lfc_w_tax %>% 
  filter(Family %in% wanted_family) %>% 
  ggplot(aes(x = asv, y = Family)) +
  geom_tile(aes(fill = lfc)) +
  scale_fill_gradient2(low = 'blue', high = 'red', name = 'Log Fold Change') +
  # geom_text(aes(label = lfc)) +
  facet_wrap(~diet) +
  theme_bw() +
  theme(axis.text.x = element_blank()) +
  xlab('ASV') -> lfc_tax_plot

lfc_tax_plot
```


**Editing my updated_metadata.tsv to include the histopathology scoring**
```{r}
tmp_meta <- read_tsv(tmp_meta_fp)
histo <- read_csv(histo_FP)

histo %>%
  mutate(mouse_id = as.character(mouse_id),
         cecum = as.character(cecum),
         colon = as.character(colon)) %>%
  add_row(mouse_id = 'numeric',
          cecum = 'numeric',
          colon = 'numeric',
          .before = 1) -> histo

tmp_meta %>%
  left_join(histo, by = 'mouse_id') %>% 
  na.omit() -> histo_meta

write_tsv(histo_meta,
          '../data/misc/histo_updated_metadata.tsv')
```

