---
title: "acetate_propionate_comp_redo"
output: html_document
date: "2024-12-18"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(broom)
library(magrittr)
library(cowplot)
library(apppleplots)
library(viridis)
```

**Functions**
```{r}
## will give the r2 and p values for each value in the specified column 
lm_r2_p_value <- function(input_table,
                          wanted_col1,
                          wanted_col2 = NULL,
                          formula_left,
                          formula_right){
  if (is.character(wanted_col1) & is.character(wanted_col2)) {
    output <- tibble()
    for(i in unique(unlist(input_table[wanted_col1]))) {
      for(j in unique(unlist(input_table[wanted_col2]))) {
        funky_formula <- paste(formula_left, formula_right, sep = "~")
        lm <- input_table %>% 
                filter(.data[[wanted_col1]] == i,
                       .data[[wanted_col2]] == j) %>%
                do(glance(lm(as.formula(funky_formula),
                             data = .))) %>% 
              mutate("{wanted_col1}" := paste(i),
                     "{wanted_col2}" := paste(j))
        output <- bind_rows(output, lm)
        
        stat_table <- output %>% 
          select(r.squared, p.value, .data[[wanted_col1]], .data[[wanted_col2]]) %>% 
          rename(r_squared = r.squared,
                 p_value = p.value) %>% 
          mutate(p_value = if_else(is.na(p_value), 1, p_value))
      }
    }
    
  } else {
    output <- tibble()
    for(i in unique(unlist(input_table[wanted_col1]))){
        funky_formula <- paste(formula_left, formula_right, sep = "~")
        lm <- input_table %>% 
                filter(.data[[wanted_col1]] == i) %>%
                do(glance(lm(as.formula(funky_formula),
                             data = .))) %>% 
              mutate("{wanted_col1}" := paste(i))
        output <- bind_rows(output, lm)
        
        ## putting together actual stat table 
        stat_table <- output %>% 
          select(r.squared, p.value, .data[[wanted_col1]]) %>% 
          rename(r_squared = r.squared,
                 p_value = p.value) %>% 
          mutate(p_value = if_else(is.na(p_value), 1, p_value))
    }
  }
  
  stat_table['signif'] <- symnum(stat_table$p_value,
                                 cutpoints = c(0, 0.0001, 0.001, 0.01, 0.05, 1),
                                 symbols = c("****", "***", "**", "*", "ns"),
                                 abbr.colnames = FALSE,
                                 na = "")
  return(stat_table)
}

## putting stats directly on correlation plots 
stat_on_plot <- function(stat_table,
                         wanted_col_list,
                         x_col_name,
                         x_col_value,
                         y_col_name,
                         y_col_value,
                         plot,
                         plot_text_size){
  ## making table conducive to labeling plot 
  proc_stat_table <- stat_table %>% 
    filter(signif != 'ns') %>% 
    select(all_of(wanted_col_list)) %>% 
    ## created columns need to match up with the column names called for the x and y axis in the plot
    ## numeric values added are the x and y coordinates for where the label will sit in the facet block 
    mutate("{x_col_name}" := paste(x_col_value),
           "{x_col_name}" := as.numeric(.data[[x_col_name]]),
           "{y_col_name}" := paste(y_col_value),
           "{y_col_name}" := as.numeric(.data[[y_col_name]]),
           p_value = signif(p_value, digits = 3),
           r_squared = signif(r_squared, digits = 3),
           pVal_rSquare = paste0('p-value: ', p_value, "\n", 
                                 'r2: ', r_squared))
  
  ## putting labels on plot 
  plot_wStats <- plot +
    geom_label(data = proc_stat_table, 
               label = proc_stat_table$pVal_rSquare,
               color = 'black',
               fontface = 'bold',
               size = plot_text_size)
  
  ## creating list of my outputs
  my_list <- list(ProcStatTable = proc_stat_table,
                  PlotwStats = plot_wStats)
  
  return(my_list)
}
```

**File paths**
```{r}
histo_metabTox_fp <- '../data/misc/histoMetabToxin_results_comb.tsv'

## plot relabeling variables
tox_labs <- c('TcdA',
              'TcdB')
names(tox_labs) <- c('Total TcA Neat',
                     'Total TcB Neat')

metab_labs <- c('Acetate',
                'Propionate')
names(metab_labs) <- c('Acetic Acid (ug/g)',
                       'Propanoic Acid (ug/g)')

cecum_labs <- c('Cecum')
names(cecum_labs) <- c('cecum')
```

**Data wrangled**
```{r}
histo_metabTox_table <- read_tsv(histo_metabTox_fp)

## pulling out toxin data only 
histo_metabTox_table %>% 
  filter(tissue == 'cecum',
         microbe_product == "Total TcA Neat" | microbe_product == 'Total TcB Neat') %>% 
  select(mouse_id, microbe_product, conc_normalized, diet) %>% 
  rename(comp_value = microbe_product,
         conc_score = conc_normalized) -> toxOnly_table

## pulling out cecal histopathology scores only 
## making column names the same as table above so I can rbind them together 
histo_metabTox_table %>% 
  filter(microbe_product == 'Total TcA Neat',
         tissue == 'cecum') %>% 
  select(mouse_id, tissue, score, diet) %>% 
  rename(comp_value = tissue,
         conc_score = score) -> cecal_histoOnly_table

## the rbinding in question
## I also initially wanted to put these in the same plot with facets but that didn't work out 
## so that's why you later see me filtering for either toxin or histopathology later
histoTox_only_table <- rbind(toxOnly_table,
                             cecal_histoOnly_table)

## prepping metabolomics data and combining it with histo and tox table
histo_metabTox_table %>% 
  select(mouse_id, microbe_product, conc_normalized) %>% 
  filter(microbe_product == 'Acetic Acid (ug/g)' | microbe_product == 'Propanoic Acid (ug/g)') %>% 
  left_join(histoTox_only_table, by = 'mouse_id',
            relationship = "many-to-many") -> all_metab_table
```

**Toxin comparison plot**
```{r, fig.width=10, fig.height=8}
## only pulling out toxin data
metab_tox_table <- all_metab_table %>% 
  filter(comp_value != "cecum") %>% 
  mutate(log_conc_norm = log10(conc_normalized),
         log_conc_score = log10(conc_score))

metab_tox_plot <- apppleplots::correlation_plots(input_table = metab_tox_table,
                                                    x_value = 'conc_normalized',
                                                    y_value = 'conc_score',
                                                    x_transform = TRUE,
                                                    y_transform = TRUE,
                                                    point_alpha = 0,
                                                    regression_method = 'none',
                                                    facet_rows = 'microbe_product',
                                                    facet_cols = 'comp_value',
                                                    row_labs = metab_labs,
                                                    col_labs = tox_labs,
                                                    x_name = ' ',
                                                    y_name = 'Toxin Concentration (ng/uL) (log10)',
                                                    title_content = 'Cecum Acetate and Propionate Comparisons')

metab_tox_plot  <- metab_tox_plot +
  ## this adds the black outline to the regression lines so you can see them better 
  geom_smooth(aes(group = diet), color = 'black', 
              linewidth = 1.5, method = 'lm', se = FALSE) +
  ## this is the actual regression lines 
  geom_smooth(aes(group = diet, color = diet), method = 'lm', se = FALSE) +
  scale_color_viridis(option = 'C',
                      discrete = TRUE,
                      guide = 'none') +
  geom_jitter(aes(fill = diet), pch = 21, alpha = 0.7, size = 3) +
  scale_fill_viridis(option = 'C',
                     discrete = TRUE,
                     guide = 'none') +
  theme_bw(base_size = 20) +
  theme(strip.text.y.right = element_text(angle = 0)) +
  ## changed y-axis limits so I could fit the stat label in all facet blocks
  expand_limits(y = c(0, 1500)) +
  labs(subtitle = 'C. difficile Toxin')

## stats
metab_tox_stats <- lm_r2_p_value(input_table = metab_tox_table,
                                 wanted_col1 = 'comp_value',
                                 wanted_col2 = 'microbe_product',
                                 formula_left = 'log_conc_score',
                                 formula_right = 'log_conc_norm * diet')


## stats on plot
metab_tox_list <- stat_on_plot(stat_table = metab_tox_stats,
                               wanted_col_list = colnames(metab_tox_stats),
                               x_col_name = 'conc_normalized',
                               x_col_value = '10',
                               y_col_name = 'conc_score',
                               y_col_value = '1500',
                               plot = metab_tox_plot,
                               plot_text_size = 3.5)

metab_toxStats_plot <- metab_tox_list$PlotwStats

metab_toxStats_plot
```

**Histopathology comparisons**
```{r, fig.width=10, fig.height=8}
## only pulling out cecal histopathology data
metab_histo_table <- all_metab_table %>% 
  filter(comp_value == "cecum") %>% 
  mutate(log_conc_norm = log10(conc_normalized))

metab_histo_plot <- apppleplots::correlation_plots(input_table = metab_histo_table,
                                                      x_value = 'conc_normalized',
                                                      y_value = 'conc_score',
                                                      x_transform = TRUE,
                                                      y_transform = FALSE,
                                                      point_alpha = 0,
                                                      regression_method = 'none',
                                                      facet_rows = 'microbe_product',
                                                      facet_cols = 'comp_value',
                                                      row_labs = metab_labs,
                                                      col_labs = cecum_labs,
                                                      x_name = ' ',
                                                      y_name = 'Score',
                                                      title_content = '')

metab_histo_plot <- metab_histo_plot +
  ## this adds the black outline to the regression lines so you can see them better 
  geom_smooth(aes(group = diet), color = 'black', 
              linewidth = 1.5, method = 'lm', se = FALSE) +
  ## this is the actual regression lines 
  geom_smooth(aes(group = diet, color = diet), method = 'lm', se = FALSE) +
  scale_color_viridis(option = 'C',
                      discrete = TRUE,
                      guide = 'none') +
  geom_jitter(aes(fill = diet), pch = 21, alpha = 0.7, size = 3) +
  scale_fill_viridis(option = 'C',
                     discrete = TRUE,
                     name = 'Mouse Diet',
                     labels = c('Chow',
                               'HFt / HFb',
                               'HFt / LFb',
                               'LFt / HFb',
                               'LFt / LFb')) +
  theme_bw(base_size = 20) +
  theme(strip.text.y.right = element_text(angle = 0)) +
  labs(subtitle = 'Histopathology')

## stats
metab_histo_stats <- lm_r2_p_value(input_table = metab_histo_table,
                                    wanted_col1 = 'comp_value',
                                    wanted_col2 = 'microbe_product',
                                    formula_left = 'conc_score',
                                    formula_right = 'log_conc_norm * diet')


## stats on plot
metab_histo_list <- stat_on_plot(stat_table = metab_histo_stats,
                               wanted_col_list = colnames(metab_histo_stats),
                               x_col_name = 'conc_normalized',
                               x_col_value = '5',
                               y_col_name = 'conc_score',
                               y_col_value = '5.75',
                               plot = metab_histo_plot,
                               plot_text_size = 3.5)

metab_histoStats_plot <- metab_histo_list$PlotwStats

metab_histo_plot
metab_histoStats_plot
```

**Putting the plots together**
```{r, fig.width=19, fig.height=8}
## creating universal y axis label since the y axis is the same for both plots 
y_axis_label <- ggdraw() +
  draw_label('SCFA Concentration (ug/g) (log10)',
             size = 20,
             hjust = 0.5,
             y = 1)

all_metab_plots <- plot_grid(metab_toxStats_plot, metab_histoStats_plot,
                              nrow = 1,
                              rel_widths = c(1, 0.8))

all_metab_plotsWithlab <- plot_grid(all_metab_plots,
                                     y_axis_label,
                                     ncol = 1,
                                     rel_heights = c(1, 0.05),
                                     align = c('hv'),
                                     axis = c('tblr'))

all_metab_plotsWithlab
```

**Creating supplemental figure 3 for the paper**
combining the correlation comparisons with the acetate/propionate concentration plot 
```{r, fig.width=19, fig.height=14.5}
supp_fig2bc_top_row <- plot_grid(notButy_plot, NULL,
                                 nrow = 1,
                                 rel_widths = c(1, 0.11))
  

supp_fig2bc <- plot_grid(supp_fig2bc_top_row,
          all_metab_plotsWithlab,
          labels = c('b)', 'c)'),
          label_size = 20,
          ncol = 1,
          rel_heights = c(0.8, 1),
          axis = 'tblr',
          align = 'hv')

supp_fig2bc
```

**Saving my outputs**
```{r}
ggsave('../plots/supp_acetProp_comp_plot.pdf',
       plot = supp_fig2bc,
       width = 19,
       height = 14.5)

save(supp_fig2bc,
     file = '../../figures/supp_fig2bc.rdat')
```

