---
title: "hypoxia"
output: html_document
date: "2023-11-30"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(tidyverse)
library(cowplot)
library(broom)
library(rstatix)
library(ggpubr)
library(glue)
library(apppleplots)
```

**File Path**
```{r}
hypoxia_fp <- '../data/misc/pimid_fluor.csv'

diet_labs <- c('Chow',
               'High Fat / High Fiber',
               'High Fat / Low Fiber',
               'Low Fat / High Fiber',
               'Low Fat / Low Fiber')
names(diet_labs) <- c('Chow',
                      'HF/HF',
                      'HF/LF',
                      'LF/HF',
                      'LF/LF')

fiber_labs <- c('High Fiber',
                'Low Fiber')
names(fiber_labs) <- c('high_fiber',
                       'low_fiber')

location_labs <- c('Cecum',
                   'Proximal Colon',
                   'Distal Colon')
names(location_labs) <- c(1,
                          2,
                          3)
location_x_labs <- c('Cecum',
                     'Proximal\nColon',
                     'Distal\nColon')
diet_x_labs <- c('Chow',
                 'HFt/\nHFb',
                 'HFt/\nLFb',
                 'LFt/\nHFb',
                 'LFt/\nLFb')

fiber_x_labs <- c('High\nFiber',
                   'Low\nFiber')
```

**Reading in Table**
```{r}
hypoxia <- read_csv(hypoxia_fp)

hypoxia %>% 
  mutate(order = ifelse(location == 'Cecum', 1, location),
         order = ifelse(order == 'Prox_colon', 2, order),
         order = ifelse(order == 'Dist_colon', 3, order)) %>% 
  arrange(order) -> hypoxia

hypoxia %>% 
  filter(order == 1) -> hypoxia_cecumOnly
```

# **Statistical Analysis**
```{r}
## between locations by diet
dietLocation_stats <- apppleplots::kruskal_dunn_stats(input_table = hypoxia,
                                                      grouped_by = 'diet',
                                                      adjust_method = 'BH',
                                                      filter_adj_p_value = FALSE,
                                                      formula_left = 'fluorescence',
                                                      formula_right = 'order')

dietLocation_kruskal <- dietLocation_stats$KruskalTest
dietLocation_dunn <- dietLocation_stats$DunnTest

## between locations by fiber content (high v low)
fiberLocation_stats <- apppleplots::kruskal_dunn_stats(input_table = hypoxia,
                                                       grouped_by = 'fiber',
                                                       adjust_method = 'BH',
                                                       filter_adj_p_value = FALSE,
                                                       formula_left = 'fluorescence',
                                                       formula_right = 'order')

fiberLocation_kruskal <- fiberLocation_stats$KruskalTest
fiberLocation_dunn <- fiberLocation_stats$DunnTest

## between diets by location (so the opposite of the first one above)
locationDiet_stats <- apppleplots::kruskal_dunn_stats(input_table = hypoxia,
                                                      grouped_by = 'order',
                                                      adjust_method = 'BH',
                                                      filter_adj_p_value = FALSE,
                                                      formula_left = 'fluorescence',
                                                      formula_right = 'diet')

locationDiet_kruskal <- locationDiet_stats$KruskalTest
locationDiet_dunn <- locationDiet_stats$DunnTest

## between level of fiber content by location (so the opposite of the second one above)
locationFiber_stats <- apppleplots::kruskal_dunn_stats(input_table = hypoxia,
                                                       grouped_by = 'order',
                                                       adjust_method = 'BH',
                                                       filter_adj_p_value = FALSE,
                                                       formula_left = 'fluorescence',
                                                       formula_right = 'fiber')

locationFiber_kruskal <- locationFiber_stats$KruskalTest
locationFiber_dunn <- locationFiber_stats$DunnTest
```

# **Plots**
```{r}
## location is on the x-axis and faceted by diet
hypoxia_dietLocation_plot <- apppleplots::facet_once_plots(input_table = hypoxia,
                                                           stat_on_plot = TRUE,
                                                           x_value = 'order',
                                                           y_value = 'fluorescence',
                                                           x_value_type = 'discrete',
                                                           grouped_by = 'order',
                                                           point_alpha = 0.4,
                                                           x_labels = location_x_labs,
                                                           facet_by = 'diet',
                                                           facet_labels = diet_labs,
                                                           stat_table = dietLocation_dunn,
                                                           x_name = 'Location',
                                                           y_name = 'Fluorescence',
                                                           title_content = 'Intestinal Hypoxia')


## location on x-axis and faceted by fiber content 
hypoxia_fiberLocation_plot <- apppleplots::facet_once_plots(input_table = hypoxia,
                                                            stat_on_plot = TRUE,
                                                            x_value = 'order',
                                                            y_value = 'fluorescence',
                                                            x_value_type = 'discrete',
                                                            grouped_by = 'order',
                                                            point_alpha = 0.4,
                                                            x_labels = location_x_labs,
                                                            facet_by = 'fiber',
                                                            facet_labels = fiber_labs,
                                                            stat_table = fiberLocation_dunn,
                                                            x_name = 'Location',
                                                            y_name = 'Fluorescence',
                                                            title_content = 'Intestinal Hypoxia by Dietary Fiber')

## diet on x-axis and faceted by location
hypoxia_locationDiet_plot <- apppleplots::facet_once_plots(input_table = hypoxia,
                                                           stat_on_plot = TRUE,
                                                           x_value = 'diet',
                                                           y_value = 'fluorescence',
                                                           x_value_type = 'discrete',
                                                           grouped_by = 'diet',
                                                           point_alpha = 0.4,
                                                           x_labels = diet_x_labs,
                                                           facet_by = 'order',
                                                           facet_labels = location_labs,
                                                           stat_table = locationDiet_dunn,
                                                           x_name = 'Diet',
                                                           y_name = 'Fluorescence',
                                                           title_content = 'Intestinal Hypoxia')


## diet on x-axis and faceted by location CECUM ONLY
cecum_hypox_table <- hypoxia %>% 
  filter(location == 'Cecum')

hypoxia_cecum_plot <- apppleplots::facet_once_plots(input_table = cecum_hypox_table,
                                                    stat_on_plot = TRUE,
                                                    x_value = 'diet',
                                                    y_value = 'fluorescence',
                                                    x_value_type = 'discrete',
                                                    grouped_by = 'diet',
                                                    point_alpha = 0.4,
                                                    x_labels = diet_x_labs,
                                                    facet_by = 'order',
                                                    facet_labels = location_labs,
                                                    stat_table = locationDiet_dunn,
                                                    x_name = 'Diet',
                                                    y_name = 'Fluorescence',
                                                    title_content = 'Cecum Hypoxia')
  

## fiber content on x-axis and faceted by location
hypoxia_locationFiber_plot <- apppleplots::facet_once_plots(input_table = hypoxia,
                                                            stat_on_plot = TRUE,
                                                            x_value = 'fiber',
                                                            y_value = 'fluorescence',
                                                            x_value_type = 'discrete',
                                                            grouped_by = 'fiber',
                                                            point_alpha = 0.4,
                                                            x_labels = fiber_x_labs,
                                                            facet_by = 'order',
                                                            facet_labels = location_labs,
                                                            stat_table = locationFiber_dunn,
                                                            x_name = 'Fiber Content',
                                                            y_name = 'Fluorescence',
                                                            title_content = 'Intestinal Hypoxia by Dietary Fiber')
```

```{r, fig.height=5, fig.width=15}
hypoxia_dietLocation_plot
```

```{r, fig.height=4, fig.width=8}
hypoxia_fiberLocation_plot
```
```{r, fig.height=5, fig.width=10}
hypoxia_locationDiet_plot
```
```{r, fig.height=4, fig.width=6}
hypoxia_cecum_plot
```

```{r, fig.height=4.5, fig.width=8}
hypoxia_locationFiber_plot
```

# **Saving my Outputs**
```{r}
## as a pdf
ggsave('../plots/hypoxia_diet_facetLocation.pdf',
       plot = hypoxia_locationDiet_plot,
       width = 10, 
       height = 5)
ggsave('../plots/hypoxia_diet_cecumONLY.pdf',
       plot = hypoxia_cecum_plot,
       width = 6, 
       height = 4)
ggsave('../plots/hypoxia_fiber_facetLocation.pdf',
       plot = hypoxia_locationFiber_plot,
       width = 8, 
       height = 4.5)
ggsave('../plots/hypoxia_location_facetDiet.pdf',
       plot = hypoxia_dietLocation_plot,
       width = 15, 
       height = 5)

## as an rdata object
save(hypoxia_locationDiet_plot,
     file = '../../figures/hypoxia_diet_facetLocation.rdata')
save(hypoxia_locationFiber_plot,
     file = '../../figures/hypoxia_fiber_facetLocation.rdata')
save(hypoxia_dietLocation_plot,
     file = '../../figures/hypoxia_location_facetDiet.rdata')
save(hypoxia_cecum_plot,
     file = '../../figures/hypoxia_cecumONLY.rdata')

## stats
write_tsv(dietLocation_dunn,
          '../stats/hypoxia_dietLocation_dunn.tsv')
write_tsv(fiberLocation_dunn,
          '../stats/hypoxia_fiberLocation_dunn.tsv')
```

