---
title: "metabolomics"
output: html_document
date: "2023-11-09"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(broom)
library(cowplot)
library(magrittr)
library(qiime2R)
library(tidyverse)
library(ggpubr)
library(rstatix)
library(glue)
library(argparse)
library(apppleplots)
```

**File Paths**
Metabolomics file has already been joined with the metadata so it doesn't need to be read in. 
```{r}
# metab_FP <- '../data/misc/processed_metabolomics.tsv'
metab_FP <- '../data/misc/v2_proc_metab.tsv'

metab_labs <- c('Acetate',
                'Propionate',
                'Butyrate')
names(metab_labs) <- c('Acetic Acid (ug/g)',
                       'Propanoic Acid (ug/g)',
                       'n-Butanoic Acid (ug/g)')

metab_x_labs <- c('Chow', 
                 'HFt/\nHFb', 
                 'HFt/\nLFb',
                 'LFt/\nHFb', 
                 'LFt/\nLFb')

metab_title <- 'Cecum SCFA Concentration'
```

**Reading in Needed File**
- taking out samples that were not quantified due to insufficient tissue size
```{r}
metab <- read_tsv(metab_FP) %>% 
  filter(concentration != "not_enough_sample") %>% 
  mutate(concentration = as.numeric(concentration))
```

**Stats**
```{r}
## kruskal wallis and dunn's post hoc test
metab_krDunn <- apppleplots::kruskal_dunn_stats(input_table = metab,
                                                grouped_by = 'metabolite',
                                                adjust_method = 'BH',
                                                filter_adj_p_value = FALSE,
                                                formula_left = 'concentration',
                                                formula_right = 'diet')

kruskal <- metab_krDunn$KruskalTest
dunn <- metab_krDunn$DunnTest

## linear modeling
# linear_model <- apppleplots::linear_model(input_table = metab,
#                                           grouped_by = 'metabolite',
#                                           adjust_method = 'BH',
#                                           filter_adj_p_value = FALSE,
#                                           formula_left = 'concentration',
#                                           formula_right = '(purified_diet * seq_depth) + high_fat * high_fiber')
```

**Plot**
```{r, fig.height=12, fig.width=6}
## had to free y-axis scales which the function doesn't do
## but its a ggplot so you can add layers
(metab_plot <- apppleplots::facet_once_plots(input_table = metab,
                                            stat_on_plot = FALSE,
                                            x_value = 'diet',
                                            y_value = 'concentration',
                                            x_value_type = 'discrete',
                                            grouped_by = 'diet',
                                            point_alpha = 0.4,
                                            x_labels = metab_x_labs,
                                            facet_by = 'metabolite',
                                            facet_labels = metab_labs,
                                            stat_table = NULL,
                                            x_name = 'Diet',
                                            y_name = 'Concentration (ug/g)',
                                            title_content = metab_title) +
                theme_bw(base_size = 20) +
                facet_wrap(~metabolite,
                           scales = "free_y",
                           nrow = 3,
                           labeller = labeller(metabolite = metab_labs)) +
                stat_pvalue_manual(dunn,
                                   step.group.by = c('metabolite'),
                                   hide.ns = TRUE,
                                   label = 'p.adj.signif'))
```

butyrate only plot
```{r, fig.height=5.5, fig.width=6}
## filtering metabolites to only include butyrate
butyrate_table <- metab %>% 
  filter(metabolite == "n-Butanoic Acid (ug/g)")

butyrate_dunn <- dunn %>% 
  filter(metabolite == "n-Butanoic Acid (ug/g)",
         p.adj.signif != 'ns') %>% 
  add_xy_position(scales = "free_y",
                  step.increase = 0.02)

butyrateOnly_plot <- apppleplots::facet_once_plots(input_table = butyrate_table,
                                                  stat_on_plot = FALSE,
                                                  x_value = 'diet',
                                                  y_value = 'concentration',
                                                  x_value_type = 'discrete',
                                                  grouped_by = 'diet',
                                                  point_alpha = 0.4,
                                                  x_labels = metab_x_labs,
                                                  facet_by = 'metabolite',
                                                  facet_labels = metab_labs,
                                                  stat_table = butyrate_dunn,
                                                  x_name = 'Diet',
                                                  y_name = 'Concentration (ug/g)',
                                                  title_content = metab_title)

## had to free y-axis scales which the function doesn't do
## but its a ggplot so you can add layers
butyrateOnly_plot <- butyrateOnly_plot + 
                      theme_bw(base_size = 20) +
                      facet_wrap(~metabolite,
                                 scales = "fixed",
                                 labeller = labeller(metabolite = metab_labs)) +
                      stat_pvalue_manual(butyrate_dunn,
                                         tip.length = 0.01,
                                         step.increase = 0.01,
                                         label = 'p.adj.signif',
                                         hide.ns = TRUE)

butyrateOnly_plot
```

acetate and propionate only plot
```{r, fig.height=5.5, fig.width=10}
## filtering metabolites to only include butyrate
notButy_table <- metab %>% 
  filter(metabolite != "n-Butanoic Acid (ug/g)")

notButy_dunn <- dunn %>% 
  filter(metabolite != "n-Butanoic Acid (ug/g)")

notButy_plot <- apppleplots::facet_once_plots(input_table = notButy_table,
                                                  stat_on_plot = TRUE,
                                                  x_value = 'diet',
                                                  y_value = 'concentration',
                                                  x_value_type = 'discrete',
                                                  grouped_by = 'diet',
                                                  point_alpha = 0.4,
                                                  x_labels = metab_x_labs,
                                                  facet_by = 'metabolite',
                                                  facet_labels = metab_labs,
                                                  stat_table = notButy_dunn,
                                                  x_name = 'Diet',
                                                  y_name = 'Concentration (ug/g)',
                                                  title_content = metab_title)

## had to free y-axis scales which the function doesn't do
## but its a ggplot so you can add layers
notButy_plot <- notButy_plot + 
                      theme_bw(base_size = 20) +
                      facet_wrap(~metabolite,
                                 scales = "free_y",
                                 labeller = labeller(metabolite = metab_labs))

notButy_plot
```


**Saving my Outputs**
```{r}
## plot
ggsave("../plots/metabolomics.pdf",
       plot = metab_plot,
       width = 12,
       height = 5)
ggsave('../plots/butyrateOnly_metab.pdf',
       plot = butyrateOnly_plot,
       width = 6,
       height = 5.5)
ggsave('../plots/noButyrate_metab.pdf',
       plot = notButy_plot,
       width = 10,
       height = 5.5)

## as an rdata object
save(metab_plot,
     file = '../../../figures/metab.rdata')
save(butyrateOnly_plot,
     file = '../../../figures/butyrateOnly_metab.rdat')
save(notButy_plot,
     file = '../../../figures/noButyrate_metab.rdat')

## statistical tests 
write_tsv(linear_model,
          "../stats/metab_linear_model.tsv")
write_tsv(dunn,
          "../stats/metab_dunn_test.tsv")
write_tsv(kruskal,
          "../stats/metab_kruskal_test.tsv")
```

