---
title: "obAnaerobe_investigation"
output: html_document
date: "2024-12-09"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(qiime2R)
library(tidyverse)
library(cowplot)
library(magrittr)
library(vegan)
library(viridis)
library(broom)
library(rstatix)
library(ggpubr)
library(ggh4x)
library(apppleplots)
```

**Functions**
```{r}
## abundance file prep and filtering function
## combines all files into one large table
abun_file_prep <- function(metadata_fp,
                           tax_fp,
                           otu_table_fp,
                           tax_level,
                           wanted_tax){
  ## metadata
  metadata <- read_tsv(metadata_fp)
  names(metadata)[names(metadata) == '#SampleID'] <- 'sampleid'
  ## taxonomy
  taxonomy <- read_qza(tax_fp)$data %>% 
  parse_taxonomy() %>% 
  rownames_to_column('asv')
  ## otu table 
  otu_table <- read_qza(otu_table_fp)$data
  otu_table %>% 
    as_tibble(rownames = 'asv') %>% 
    gather(-asv, key = sampleid, value = abun) %>% 
    group_by(sampleid) %>% 
    mutate(rel_abun = abun/sum(abun)) %>% 
    mutate(rel_abun = rel_abun + 0.000001) -> otu_table
  ## joining all tables together 
  otu_table %>% 
    left_join(metadata, by = 'sampleid') %>% 
    left_join(taxonomy, by = 'asv') -> abun_table
  abun_table %>% 
    group_by(sampleid, day_post_inf, diet, mouse_id,
             .data[[tax_level]], Genus) %>% 
    summarise(rel_abund = sum(rel_abun)) %>% 
    filter(.data[[tax_level]] %in% wanted_tax) %>% 
    mutate(mouse_fact = as.factor(mouse_id),
           day_fact = as.factor(day_post_inf)) %>% 
    filter(!is.na(diet)) -> abun_filt
  ## creating a list for my outputs
  my_list <- list(Metadata = metadata,
                  Taxonomy = taxonomy,
                  OTUTable = otu_table,
                  AbundanceTable = abun_filt)
  return(my_list)
}
```

**File paths**
```{r}
otu_table_FP <- '../data/comp_qiime/tax_s1_filt.qza'
tax_FP <- '../data/comp_qiime/taxonomy.qza'
metadata_FP <- '../data/misc/s1_filt_comp_metadata.tsv'

diet_labs <- 
  c('Chow', 
    'High Fat / High Fiber', 
    'High Fat / Low Fiber', 
    'Low Fat / High Fiber', 
    'Low Fat / Low Fiber')
names(diet_labs) <- c('Chow', 
                      'HF/HF', 
                      'HF/LF', 
                      'LF/HF', 
                      'LF/LF')

wanted_level <- 'Family'

wanted_family <- c('Lachnospiraceae',
                   'Ruminococcaceae',
                   'Enterobacteriaceae',
                   'Peptostreptococcaceae',
                   'Enterococcaceae',
                   'Staphylococcaceae')
```

**Data wrangled**
```{r}
abun_files <- abun_file_prep(metadata_fp = metadata_FP,
                             tax_fp = tax_FP,
                             otu_table_fp = otu_table_FP,
                             tax_level = wanted_level,
                             wanted_tax = wanted_family)

abun_table <- abun_files$AbundanceTable
```

lachnospiraceae
```{r}
top_lachno <- abun_table %>% 
  filter(Family == 'Lachnospiraceae') %>% 
  group_by(Genus) %>% 
  summarise(sum_abund = round(sum(rel_abund), digits = 3)) %>% 
  slice_max(sum_abund, n = 15)

top_lachno
```

ruminococcaceae
```{r}
top_rumino <- abun_table %>% 
  filter(Family == 'Ruminococcaceae') %>% 
  group_by(Genus) %>% 
  summarise(sum_abund = round(sum(rel_abund), digits = 3)) %>% 
  slice_max(sum_abund, n = 15)

top_rumino
```

**Yay a plot!!**
lachnospiraceae
```{r, fig.width=12, fig.height=5}
lachno_order <- c("Lachnospiraceae_NK4A136_group",
                  NA,
                  "Lachnoclostridium",
                  "Blautia",
                  "Roseburia",
                  "uncultured",
                  "Marvinbryantia",
                  "[Eubacterium]_fissicatena_group",
                  "A2",
                  "Lachnospiraceae_UCG-001")
  

lachno_plot <- top_lachno %>% 
  ggplot(aes(x = Genus, y = sum_abund)) +
  geom_bar(aes(group = Genus, fill = Genus), stat = 'identity', color = 'black') +
  geom_text(aes(label = sum_abund), nudge_y = 0.25, fontface = 'bold') +
  scale_x_discrete(limit = lachno_order) +
  scale_y_continuous(expand = c(0.025, 0.025)) +
  scale_fill_discrete(breaks = lachno_order) +
  theme_bw(base_size = 20) +
  theme(legend.title = element_blank(),
        axis.text.x = element_blank()) +
  labs(x = 'Genus',
       y = 'Sum Abundance',
       title = 'Lachnospiraceae')

lachno_plot
```

ruminococcaceae
```{r, fig.width=12, fig.height=5}
rumino_order <- c("Incertae_Sedis",
                  "Anaerotruncus",
                  "UBA1819",
                  "uncultured",
                  "Paludicola",
                  "Ruminococcaceae",
                  "CAG-352",
                  NA,
                  "Ruminococcus",
                  "Caproiciproducens")

rumino_plot <- top_rumino %>% 
  ggplot(aes(x = Genus, y = sum_abund)) +
  geom_bar(aes(group = Genus, fill = Genus), stat = 'identity', color = 'black') +
  geom_text(aes(label = sum_abund), nudge_y = 0.05, fontface = 'bold') +
  scale_x_discrete(limit = rumino_order) +
  scale_y_continuous(expand = c(0.025, 0.025)) +
  scale_fill_discrete(breaks = rumino_order) +
  theme_bw(base_size = 20) +
  theme(legend.title = element_blank(),
        axis.text.x = element_blank()) +
  labs(x = 'Genus',
       y = 'Sum Abundance',
       title = 'Ruminococcaceae')

rumino_plot
```

**Putting plots together**
```{r, fig.width=12, fig.height=10}
obAnaerobe_plots <- plot_grid(lachno_plot,
                              rumino_plot,
                              ncol = 1,
                              align = 'hv',
                              axis = 'tblr')

obAnaerobe_plots
```

**Relative abundance plots**
lachnospiraceae
```{r, fig.width=20, fig.height=5}
wanted_lachno <- c('Lachnospiraceae_NK4A136_group', 
                   'unclassified',
                   'Lachnoclostridium', 
                   'Blautia', 
                   'Roseburia')

lachno_abun_table <- abun_table %>% 
  mutate(Genus = ifelse(is.na(Genus), 'unclassified', Genus)) %>% 
  filter(Family == 'Lachnospiraceae',
         Genus %in% wanted_lachno)

lachno_abun_plot <- lachno_abun_table %>% 
  ggplot(aes(x = day_post_inf, y = rel_abund)) +
  geom_smooth(aes(group = Genus), color = 'black',
              linewidth = 1.5, method = 'loess', se = FALSE) +
  geom_smooth(aes(group = Genus, color = Genus), se = FALSE, method = 'loess') +
  scale_color_brewer(palette = 'BuPu',
                     breaks = wanted_lachno,
                     labels = c('Lachnospiraceae\nNK4A136 group', 
                                'Unclassified',
                                'Lachnoclostridium', 
                                'Blautia', 
                                'Roseburia')) +
  theme_bw(base_size = 20) +
  scale_y_continuous(transform = 'log10') +
  scale_x_continuous(breaks = c(-15, -8, -3, 0, 3),
                     labels = c(-15, -8, -3, 0, 3)) +
  facet_wrap(~diet,
             nrow = 1,
             labeller = labeller(diet = diet_labs)) +
  labs(y = 'Relative Abundance (log10)',
       x = 'Days Relative to Infection',
       title = 'Lachnospiraceae')

lachno_abun_plot
```

ruminococcaceae
```{r, fig.width=20, fig.height=5}
wanted_rumino <- c('Incertae_Sedis',
                   'Anaerotruncus',
                   'UBA1819',
                   'uncultured')

rumino_abun_table <- abun_table %>% 
  filter(Family == 'Ruminococcaceae',
         Genus %in% wanted_rumino)

rumino_abun_plot <- rumino_abun_table %>% 
  ggplot(aes(x = day_post_inf, y = rel_abund)) +
  geom_smooth(aes(group = Genus), color = 'black', 
              linewidth = 1.5, method = 'loess', se = FALSE) +
  geom_smooth(aes(group = Genus, color = Genus), se = FALSE, method = 'loess') +
  scale_color_brewer(palette = 'RdPu',
                     breaks = wanted_rumino,
                     labels = c('Incertae Sedis',
                                'Anaerotruncus',
                                'UBA1819',
                                'Uncultured')) +
  theme_bw(base_size = 20) +
  scale_y_continuous(transform = 'log10') +
  scale_x_continuous(breaks = c(-15, -8, -3, 0, 3),
                     labels = c(-15, -8, -3, 0, 3)) +
  facet_wrap(~diet,
             nrow = 1,
             labeller = labeller(diet = diet_labs)) +
  labs(x = 'Days Relative to Infection',
       y = 'Relative Abundance (log10)',
       title = 'Ruminococcaceae')

rumino_abun_plot
```

escherichia-shigella, enterococcus, staphylococcus, and clostridioides
```{r, fig.width=16, fig.height=8}
wanted_pathogens <- c('Clostridioides',
                      'Enterococcus',
                      'Escherichia-Shigella',
                      'unclassified_Enterobacteriaceae',
                      'Staphylococcus')

path_labs <- c('Clostridioides',
               'Enterococcus',
               'Escherichia-Shigella',
               'Unclassified\nEnterobacteriaceae',
               'Staphylococcus')
names(path_labs) <- wanted_pathogens

path_families <- c('Enterobacteriaceae',
                   'Peptostreptococcaceae',
                   'Enterococcaceae',
                   'Staphylococcaceae')

path_abun_table <- abun_table %>% 
  filter(Family %in% path_families) %>% 
  mutate(Genus = ifelse(is.na(Genus), paste('unclassified', Family, sep = "_"), Genus)) %>% 
  filter(Genus %in% wanted_pathogens)

path_abun_plot <- apppleplots::facet_twice_plots(input_table = path_abun_table,
                                                 x_value = 'day_post_inf',
                                                 y_value = 'rel_abund',
                                                 x_value_type = 'numeric',
                                                 y_transform = TRUE,
                                                 x_labels = c(-15, -8, -3, 0, 3),
                                                 box_group_by = 'day_post_inf',
                                                 line_group_by = 'mouse_id',
                                                 point_alpha = 0.4,
                                                 facet_rows = 'Genus',
                                                 facet_cols = 'diet',
                                                 row_labs = NULL,
                                                 col_labs = diet_labs,
                                                 x_name = 'Days Relative to Infection',
                                                 y_name = 'Relative Abundance (log10)',
                                                 title_content = 'Potential Pathogen Relative Abundance') +
  theme_bw(base_size = 20) +
  facet_grid(cols = vars(diet),
             rows = vars(factor(Genus, levels = wanted_pathogens)),
             labeller = labeller(diet = diet_labs, Genus = path_labs)) +
  theme(strip.text.y.right = element_text(angle = 0))

path_abun_plot
```


**Putting relative abundance plots together**
```{r, fig.width=22, fig.height=20}
plots_together_top <- plot_grid(lachno_abun_plot +
                                  theme(axis.title.x = element_blank()) +
                                  labs(y = '',
                                       subtitle = 'Lachnospiraceae',
                                       title = 'Obligate Anaerobe Relative Abundance'),
                                rumino_abun_plot +
                                  theme(plot.title = element_blank()) +
                                  labs(x = 'Days Relative to Infection',
                                       y = '',
                                       subtitle = 'Ruminococcaceae'),
                                ncol = 1,
                                align = 'hv',
                                axis = 'tblr')

plots_together_top_withLabs <- ggdraw(plots_together_top) +
  draw_label('Relative Abundace (log10)', x = 0, y = 0.5, angle = 90, size = 20, vjust = 1.5)

plots_together <- plot_grid(plots_together_top_withLabs,
                            path_abun_plot,
                            ncol = 1,
                            labels = c('a)', 'b)'),
                            label_size = 20)

plots_together
```

**Saving my outputs**
```{r}
ggsave('../plots/top_lachno_rumino.pdf',
       plot = obAnaerobe_plots,
       width = 12,
       height = 10)
ggsave('../plots/lachno_genera_by_day.pdf',
       plot = lachno_abun_plot,
       width = 20,
       height = 5)
ggsave('../plots/rumino_genera_by_day.pdf',
       plot = rumino_abun_plot,
       width = 20,
       height = 5)
ggsave('../plots/potential_new_fig6.pdf',
       plot = plots_together,
       width = 22,
       height = 20)
```


