---
title: "lactococcus_relAbun"
output: html_document
date: "2024-11-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(qiime2R)
library(tidyverse)
library(cowplot)
library(magrittr)
library(vegan)
library(viridis)
library(broom)
library(rstatix)
library(ggpubr)
library(ggh4x)
```

**Functions**
```{r}
## combines all files into one large table
abun_file_prep <- function(metadata_fp,
                                  tax_fp,
                                  otu_table_fp,
                                  tax_level,
                                  wanted_tax){
  ## metadata
  metadata <- read_tsv(metadata_fp)
  names(metadata)[names(metadata) == '#SampleID'] <- 'sampleid'
  ## taxonomy
  taxonomy <- read_qza(tax_fp)$data %>% 
  parse_taxonomy() %>% 
  rownames_to_column('asv')
  ## otu table 
  otu_table <- read_qza(otu_table_fp)$data
  otu_table %>% 
    as_tibble(rownames = 'asv') %>% 
    gather(-asv, key = sampleid, value = abun) %>% 
    group_by(sampleid) %>% 
    mutate(rel_abun = abun/sum(abun)) %>% 
    mutate(rel_abun = rel_abun + 0.000001) -> otu_table
  ## joining all tables together 
  otu_table %>% 
    left_join(metadata, by = 'sampleid') %>% 
    left_join(taxonomy, by = 'asv') -> abun_table
  abun_table %>% 
    group_by(sampleid, day_post_inf, diet, mouse_id, 
             purified_diet, high_fat, high_fiber, study,
             seq_depth, .data[[tax_level]]) %>% 
    summarise(rel_abund = sum(rel_abun)) %>% 
    filter(.data[[tax_level]] %in% wanted_tax) %>% 
    mutate(mouse_fact = as.factor(mouse_id),
           day_fact = as.factor(day_post_inf)) %>% 
    filter(!is.na(diet)) -> abun_filt
  ## creating a list for my outputs
  my_list <- list(Metadata = metadata,
                  Taxonomy = taxonomy,
                  OTUTable = otu_table,
                  AbundanceTable = abun_filt)
  return(my_list)
}
```

**File paths**
using the otu table pre-lactococcus filtering so I can catch the lactococcus signal
```{r}
metadata_FP <- '../data/misc/comp_metadata.tsv'
tax_FP <- '../data/comp_qiime/taxonomy.qza'
otu_table_FP <- '../data/comp_qiime/taxonomy_filtered.qza'

diet_labs <- 
  c('Chow', 
    'High Fat / High Fiber', 
    'High Fat / Low Fiber', 
    'Low Fat / High Fiber', 
    'Low Fat / Low Fiber')

names(diet_labs) <- c('Chow',
                      'HF/HF',
                      'HF/LF',
                      'LF/HF',
                      'LF/LF')
```

**Data wrangled**
```{r}
lacto_files <- abun_file_prep(metadata_fp = metadata_FP,
                              tax_fp = tax_FP,
                              otu_table_fp = otu_table_FP,
                              tax_level = 'Genus',
                              wanted_tax = 'Lactococcus')

lacto_abun <- lacto_files$AbundanceTable %>% 
  filter(diet != 'Chow')

av_lacto_abun <- lacto_abun %>% 
  group_by(diet) %>% 
  summarise(av_rel_abund = mean(rel_abund))
```

**Attempt at a plot**
```{r, fig.height=4, fig.width=12}
all_timeline_plot <- apppleplots::facet_twice_plots(input_table = lacto_abun,
                                                    x_value = 'day_post_inf',
                                                    y_value = 'rel_abund',
                                                    x_value_type = 'numeric',
                                                    y_transform = FALSE,
                                                    x_labels = c(-15, -8, -3, 0, 3),
                                                    box_group_by = 'day_post_inf',
                                                    line_group_by = 'mouse_id',
                                                    point_alpha = 0.4,
                                                    facet_rows = 'Genus',
                                                    facet_cols = 'diet',
                                                    row_labs = NULL,
                                                    col_labs = diet_labs,
                                                    x_name = 'Days Relative to Infection',
                                                    y_name = 'Relative Abundance',
                                                    title_content = 'Lactococcus Relative Abundance')

all_timeline_plot <- all_timeline_plot +
  theme_bw(base_size = 20) +
  theme(strip.text.y.right = element_text(angle = 0))

all_timeline_plot
```
probably not using this one...
```{r, fig.width=7, fig.height=4.5}
av_lacto_abun %>% 
  ggplot(aes(x = diet, y = av_rel_abund)) +
  geom_bar(aes(group = diet, fill = diet), stat = 'identity', position = 'stack', 
           color = 'black', alpha = 0.7) +
  theme_bw(base_size = 20) +
  scale_fill_brewer(palette = 'Spectral',
                    guide = 'none') +
  scale_x_discrete(labels = c('HFt/\nHFb',
                              'HFt/\nLFb',
                              'LFt/\nHFb',
                              'LFt/\nLFb')) +
  labs(x = 'Diet',
       y = 'Average Relative Abundance',
       title = 'Lactococcus Relative Abundance')
```

**Saving my Outputs**
```{r}
ggsave('../plots/lacto_relAbun_diet.pdf',
       plot = all_timeline_plot,
       width = 12,
       height = 4)
```

