---
title: "alpha_div_plots"
output: html_document
date: "2023-11-07"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(ggpubr)
library(ggplot2)
library(magrittr)
library(qiime2R)
library(tidyverse)
library(broom)
library(cowplot)
library(viridis)
library(argparse)
```

**Functions**
```{r}
## faith's pd plot 
## assumes that the files is a .tsv
faith_pd_plot <- function(faith_fp,
                          metadata_file,
                          labels,
                          names_labels,
                          title){
  faith <- read_tsv(faith_fp)
  names(faith)[names(faith) == '#SampleID'] <- 'sampleid'
  metadata_file %>% 
    left_join(faith, by = 'sampleid') %>% 
    mutate(study = as.factor(study)) -> faith_pd
   ## what you want the grid labels to be (list)
  labs <- (labels) 
  ## what grid labels currently are (list)
  names(labs) <- (names_labels) 
  faith_pd %>%
    filter(!is.na(diet)) %>% 
    ggplot(aes(x = day_post_inf, y = faith_pd)) +
    geom_boxplot(aes(group = day_post_inf), outlier.shape = NA) +
    geom_line(aes(group = mouse_id), alpha = 0.1) +
    geom_jitter(width = 0.1, height = 0, alpha = 0.4) +
    scale_x_continuous(breaks = c(-15, -8, -3, 0, 3)) +
    # geom_smooth(se = FALSE) +
    theme_bw(base_size = 20) +
    facet_grid(~diet, labeller = labeller(diet = labs) ) +
    ggtitle(title) +
    xlab('Days Relative to Infection') +
    ylab("Faith's PD") -> faith_plot
  return(faith_plot)
}


## shannon entropy plot
## assumes that the file is a .tsv
shannon_plot <- function(shannon_fp,
                         metadata_file,
                         labels,
                         names_labels,
                         title){
  shannon <- read_tsv(shannon_fp)
  names(shannon)[names(shannon) == '...1'] <- 'sampleid'
  metadata_file %>% 
    left_join(shannon, by = 'sampleid') %>% 
    mutate(study = as.factor(study)) -> shannon_entropy
  ## what you want the grid labels to be (list)
  labs <- (labels) 
  ## what grid labels currently are (list)
  names(labs) <- (names_labels) 
  shannon_entropy %>%
    filter(!is.na(diet)) %>% 
    ggplot(aes(x = day_post_inf, y = shannon_entropy)) +
    geom_boxplot(aes(group = day_post_inf), outlier.shape = NA) +
    geom_line(aes(group = mouse_id), alpha = 0.1) +
    geom_jitter(width = 0.1, height = 0, alpha = 0.4) +
    scale_x_continuous(breaks = c(-15, -8, -3, 0, 3)) +
    # geom_smooth(se = FALSE) +
    theme_bw(base_size = 20) +
    facet_grid(~diet, labeller = labeller(diet = labs) ) +
    ggtitle(title) +
    xlab('Days Relative to Infection') +
    ylab("Shannon Entropy") -> shannon_plot
  return(shannon_plot)
}
```

**File Paths**
```{r}
metadata_FP <- '../data/misc/s1_filt_comp_metadata.tsv'
faith_pd_FP <- '../data/s1_filt_core/faith_pd.tsv'
shannon_FP <- '../data/s1_filt_core/shannon_entropy.tsv'

## day 3 filtered out of stool samples and replaced with cecal samples
filt_metadata_FP <- '../data/misc/d3_filt_comp_metadata.tsv'
filt_faith_pd_FP <- '../data/day3_filt_core/faith_pd.tsv'
filt_shannon_FP <- '../data/day3_filt_core/shannon_entropy.tsv'

diet_labs <- 
  c('Chow', 
    'High Fat / High Fiber', 
    'High Fat / Low Fiber', 
    'Low Fat / High Fiber', 
    'Low Fat / Low Fiber')

diet_names_labels <- c('Chow', 
                       'HF/HF', 
                       'HF/LF', 
                       'LF/HF', 
                       'LF/LF')
```

# **Colon and Cecum Data Combined with Day 3 Filtered out of the Colon Samples AND Batch 1 Filtered Out**

**Metadata File**
```{r}
metadata <- read_tsv(metadata_FP)
names(metadata)[names(metadata) == '#SampleID'] <- 'sampleid'
```

**Faith's PD**
```{r, fig.height=4.5, fig.width=14, warning=FALSE}
faith_title <- "Faith's Phylogenetic Diversity"

faith_plot <- faith_pd_plot(faith_pd_FP,
                            metadata,
                            diet_labs,
                            diet_names_labels,
                            faith_title)

faith_plot
```

**Shannon Entropy**
```{r, fig.height=4.5, fig.width=14, warning=FALSE}
shannon_title <- "Shannon Entropy"

shannon_entropy_plot <- shannon_plot(shannon_FP,
                                     metadata,
                                     diet_labs,
                                     diet_names_labels,
                                     shannon_title)
shannon_entropy_plot
```

# **Cecum and Colon Data Combined with ONLY Day 3 Filtered out of the Colon Samples**

**Metadata File**
```{r}
filt_metadata <- read_tsv(filt_metadata_FP)
names(filt_metadata)[names(filt_metadata) == '#SampleID'] <- 'sampleid'
```

**Faith's PD**
```{r, fig.height=4.5, fig.width=14, warning=FALSE}
filt_faith_title <- "Day 3 Filtered Faith's Phylogenetic Diversity"

filt_faith_plot <- faith_pd_plot(filt_faith_pd_FP,
                                filt_metadata,
                                diet_labs,
                                diet_names_labels,
                                filt_faith_title)

filt_faith_plot
```

**Shannon Entropy**
```{r, fig.height=4.5, fig.width=14, warning=FALSE}
filt_shannon_title <- "Day 3 Filtered Shannon Entropy"

filt_shannon_entropy_plot <- shannon_plot(filt_shannon_FP,
                                         filt_metadata,
                                         diet_labs,
                                         diet_names_labels,
                                         filt_shannon_title)
filt_shannon_entropy_plot
```

**Saving my Outputs**
```{r}
## plots with day 3 replaced by the cecal data but replicate one isn't filtered out
# ggsave('../day3_filt_plots/faith_pd.pdf',
#        plot = filt_faith_plot, 
#        width = 14, 
#        height = 4.5)
# 
# ggsave('../day3_filt_plots/shannon_entropy.pdf',
#        plot = filt_shannon_entropy_plot, 
#        width = 14, 
#        height = 4.5)

## plots where replicate one IS filtered out
ggsave('../plots/faith_pd.pdf',
       plot = faith_plot, 
       width = 14, 
       height = 4.5)

ggsave('../plots/shannon_entropy.pdf',
       plot = shannon_entropy_plot, 
       width = 14, 
       height = 4.5)

## as an rdata object
save(faith_plot,
     file = '../../../figures/faith_pd.rdata')
save(shannon_entropy_plot,
     file = '../../../figures/shannon.rdata')
```