---
title: "lactococcus_relAbun"
output: html_document
date: "2024-11-20"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(qiime2R)
library(tidyverse)
library(cowplot)
library(magrittr)
library(vegan)
library(viridis)
library(broom)
library(rstatix)
library(ggpubr)
library(ggh4x)
library(apppleplots)
```

**Functions**
```{r}
## combines all files into one large table
abun_file_prep <- function(metadata_fp,
                                  tax_fp,
                                  otu_table_fp,
                                  tax_level,
                                  wanted_tax){
  ## metadata
  metadata <- read_tsv(metadata_fp)
  names(metadata)[names(metadata) == '#SampleID'] <- 'sampleid'
  ## taxonomy
  taxonomy <- read_qza(tax_fp)$data %>% 
  parse_taxonomy() %>% 
  rownames_to_column('asv')
  ## otu table 
  otu_table <- read_qza(otu_table_fp)$data
  otu_table %>% 
    as_tibble(rownames = 'asv') %>% 
    gather(-asv, key = sampleid, value = abun) %>% 
    group_by(sampleid) %>% 
    mutate(rel_abun = abun/sum(abun)) %>% 
    mutate(rel_abun = rel_abun + 0.000001) -> otu_table
  ## joining all tables together 
  otu_table %>% 
    left_join(metadata, by = 'sampleid') %>% 
    left_join(taxonomy, by = 'asv') -> abun_table
  abun_table %>% 
    group_by(sampleid, day_post_inf, diet, mouse_id, 
             purified_diet, high_fat, high_fiber, study,
             seq_depth, .data[[tax_level]]) %>% 
    summarise(rel_abund = sum(rel_abun)) %>% 
    filter(.data[[tax_level]] %in% wanted_tax) %>% 
    mutate(mouse_fact = as.factor(mouse_id),
           day_fact = as.factor(day_post_inf)) %>% 
    filter(!is.na(diet)) -> abun_filt
  ## creating a list for my outputs
  my_list <- list(Metadata = metadata,
                  Taxonomy = taxonomy,
                  OTUTable = otu_table,
                  AbundanceTable = abun_filt)
  return(my_list)
}

## editing my dunn's post hoc test to include the difference in means between groups 
edit_dunn_test <- function(filtered_table,
                           first_group,
                           second_group,
                           mean_value,
                           dunn_test){
  filtered_table %>% 
    group_by(filtered_table[first_group], filtered_table[second_group]) %>% 
    summarise(mean = mean(.data[[mean_value]])) -> mean_table
  
  dunn_test %>% 
    merge(mean_table, 
          by.x = c('group1',
                   second_group),
          by.y = c(first_group,
                   second_group)) %>% 
    rename_with(~paste0('group1_', mean_value, recycle0 = TRUE), contains('mean')) %>% 
    merge(mean_table,
          by.x = c('group2',
                   second_group),
          by.y = c(first_group,
                   second_group)) %>% 
    rename_with(~paste0('group2_', mean_value, recycle0 = TRUE), contains('mean')) -> int_dunn
  
  group1_col <- paste0('group1_', mean_value)
  group2_col <- paste0('group2_', mean_value)
  
  int_dunn %>% 
    mutate(diff_means = (.data[[group1_col]] - .data[[group2_col]]),
           stat_diff_means = if_else(p.adj > 0.05, 0, diff_means)) -> new_dunn
  
  return(new_dunn)
}
```

**File paths**
using the otu table pre-lactococcus filtering so I can catch the lactococcus signal
```{r}
metadata_FP <- '../data/misc/comp_metadata.tsv'
tax_FP <- '../data/comp_qiime/taxonomy.qza'
otu_table_FP <- '../data/comp_qiime/taxonomy_filtered.qza'

diet_labs <- 
  c('Chow', 
    'High Fat / High Fiber', 
    'High Fat / Low Fiber', 
    'Low Fat / High Fiber', 
    'Low Fat / Low Fiber')

names(diet_labs) <- c('Chow',
                      'HF/HF',
                      'HF/LF',
                      'LF/HF',
                      'LF/LF')
```

**Data wrangled**
```{r}
lacto_files <- abun_file_prep(metadata_fp = metadata_FP,
                              tax_fp = tax_FP,
                              otu_table_fp = otu_table_FP,
                              tax_level = 'Genus',
                              wanted_tax = 'Lactococcus')

lacto_abun <- lacto_files$AbundanceTable %>% 
  filter(diet != 'Chow')

av_lacto_abun <- lacto_abun %>% 
  group_by(diet, day_post_inf) %>% 
  summarise(av_rel_abund = mean(rel_abund),
            perc_av_relAbund = paste0(round(av_rel_abund * 100, digits = 3), '%'))

## keith wanted the lacto relative abundance percentages at days -3, 0 and 3 so this is me getting them and 
## making the table pretty for him 
keiths_perc <- av_lacto_abun %>% 
  filter(day_post_inf == -3 | day_post_inf == 0 | day_post_inf == 3) %>% 
  select(diet, day_post_inf, perc_av_relAbund) %>% 
  spread(diet, perc_av_relAbund)

keiths_perc
```

**Plot**
```{r, fig.height=4, fig.width=12}
lacto_contam_plot <- apppleplots::facet_twice_plots(input_table = lacto_abun,
                                                    x_value = 'day_post_inf',
                                                    y_value = 'rel_abund',
                                                    x_value_type = 'numeric',
                                                    y_transform = FALSE,
                                                    x_labels = c(-15, -8, -3, 0, 3),
                                                    box_group_by = 'day_post_inf',
                                                    line_group_by = 'mouse_id',
                                                    point_alpha = 0.4,
                                                    facet_rows = 'Genus',
                                                    facet_cols = 'diet',
                                                    row_labs = NULL,
                                                    col_labs = diet_labs,
                                                    x_name = 'Days Relative to Infection',
                                                    y_name = 'Relative Abundance',
                                                    title_content = 'Lactococcus Relative Abundance')

(lacto_contam_plot <- lacto_contam_plot +
  theme_bw(base_size = 20) +
  theme(strip.text.y.right = element_text(angle = 0)))
```

**Stats**
```{r}
lacto_krDunn_stats <- apppleplots::kruskal_dunn_stats(input_table = lacto_abun,
                                                      grouped_by = c('Genus', 'day_post_inf'),
                                                      adjust_method = 'BH',
                                                      filter_adj_p_value = FALSE,
                                                      formula_left = 'rel_abund',
                                                      formula_right = 'diet')
lacto_kruskal <- lacto_krDunn_stats$KruskalTest
lacto_dunn <- lacto_krDunn_stats$DunnTest

new_lacto_dunn <- edit_dunn_test(filtered_table = lacto_abun,
                                 first_group = 'diet',
                                 second_group = c('day_post_inf', 'Genus'),
                                 mean_value = 'rel_abund',
                                 dunn_test = lacto_dunn)
```

statistical visualization
```{r, fig.width=12, fig.height=4}
stat_y_labs <- c('HFt / LFb',
                 'LFt / HFb',
                 'LFt / LFb')
stat_x_labs <- c(-15, -8, -3, 0, 3)

lacto_stat_plot <- apppleplots::stat_heat_plot(input_table = new_lacto_dunn,
                                               x_value = 'day_post_inf',
                                               y_value = 'group2',
                                               x_value_type = 'continuous',
                                               y_value_type = 'discrete',
                                               pairwise = TRUE,
                                               tile_fill = 'stat_diff_means',
                                               text_value = 'p.adj.signif',
                                               low_color = "#0D0887FF",
                                               high_color = "#CC4678FF",
                                               legend_name = 'Group 1 -\nGroup2',
                                               x_labels = stat_x_labs,
                                               y_labels = stat_y_labs,
                                               facet_by = 'group1',
                                               facet_labels = diet_labs,
                                               x_name = 'Days Relative to Infection',
                                               y_name = 'Group 2',
                                               title_content = 'Lactococcus Comparisons')

lacto_stat_plot <- lacto_stat_plot +
  theme_bw(base_size = 20) +
  theme(plot.subtitle = element_text(hjust = 0.5))

lacto_stat_plot
```

**Putting Plots Together**
```{r, fig.width=12, fig.height=8}
lacto_abun_plots <- plot_grid(lacto_contam_plot,
                              lacto_stat_plot,
                              labels = c('a)', 'b)'),
                              label_size = 20,
                              ncol = 1)

lacto_abun_plots
```


**Saving my Outputs**
```{r}
ggsave('../plots/lacto_relAbun_diet.pdf',
       plot = lacto_contam_plot,
       width = 12,
       height = 4)
ggsave('../plots/lacto_relbun_stats.pdf',
       plot = lacto_stat_plot,
       width = 12,
       height = 4)
ggsave('../plots/lacto_relAbun_withStats.pdf',
       plot = lacto_abun_plots,
       width = 12,
       height = 8)

## as an rdat object for figure construction
save(lacto_contam_plot,
     file = '../../../figures/lacto_contam_relAbun.rdat')
save(lacto_stat_plot,
     file = '../../../figures/lacto_contam_relAbun_stats.rdat')
```

